### ISSUE TITLE
How to stop RR server using command line?

### ISSUE THREAD

**Issue by AlexPravdin** [spiral/roadrunner#100]
Hello.
How to stop RR server using command line?

**Comment by wolfy-j** [comment]
Send it SIGTERM or SIGKILL.

**Comment by AlexPravdin** [comment]
Before that I have to get PID, right?
What about Windows?

**Comment by wolfy-j** [comment]
I'm not sure what is the proper sequence to stop it on windows, but principle is the same. Usually you sasve the process pid on service start.

**Comment by AlexPravdin** [comment]
It seems it would be very nice to have a way to stop it like all others. At least nginx and apache have such commands.

**Comment by wolfy-j** [comment]
Actually nginx is stopped exactly same way: https://www.keycdn.com/support/nginx-commands

The reason why it looks easier cos you have service wrapper which provides shortcut like `service nginx stop`.

**Comment by AlexPravdin** [comment]
Yes, I see. Could you add the similar command please?

**Comment by wolfy-j** [comment]
Up to next release.

**Comment by wolfy-j** [comment]
Command `rr stop` available in 1.4.0

**Comment by lda** [comment]
The `stop` command does not work. It fails with error:
```
Stopping RoadRunner: Error: reading body rpc: can't find method system.Detach
``` 
I'm sure it is [this line]( https://github.com/spiral/roadrunner/blob/8be4061d13a28d92bce4b2364049b8579b776d5d/cmd/rr/cmd/stop.go#L46).

**Comment by wolfy-j** [comment]
Hmm, sounds like something messed us with Goland. Fixing now.

**Comment by wolfy-j** [comment]
Fixed in 1.4.2

**Comment by lda** [comment]
👏

**Comment by lanlin** [comment]
the `stop` command not work for me.

RoadRunner, PHP Application Server
Version: 1.8.4, 2020-10-21T14:07:46+0300

php 7.4.4
osx 10.15.7

after run `stop`, it shows:

```shell
DEBU[0000] [headers]: disabled                          
DEBU[0000] [static]: disabled                           
Stopping RoadRunner: done
```

it just removes the RPC Unix socket file,
but the rr & php workers process still there
