### ISSUE TITLE
Improve Laravel integration performance

### ISSUE THREAD

**Issue by wolfy-j** [spiral/roadrunner#103]
Guys, please take a loot at this solution https://github.com/swooletw/laravel-swoole/blob/master/config/swoole_http.php#L92-L120

Looks like to make roadrunner integration with Laravel to be most flexible and fast, it should implement same logics (service providers and instances restarters + cached instances sandbox).

Thank you!

_Originally posted by @barbushin in https://github.com/spiral/roadrunner/issues/96#issuecomment-457801446_

**Comment by wolfy-j** [comment]
test github ticket comment

**Comment by Hunternnm** [comment]
Hello! Here I did the integration back in February, ready for production and is actively used there. Can anyone check? https://github.com/Hunternnm/laravel-roadrunner

Example https://github.com/Hunternnm/laravel-roadrunner-example

**Comment by assurrussa** [comment]
> Hello! Here I did the integration back in February, ready for production and is actively used there. Can anyone check? https://github.com/Hunternnm/laravel-roadrunner
> 
> Example https://github.com/Hunternnm/laravel-roadrunner-example

A nice simple package for integrating Laravel with RoadRunner.

I wanted to write my integration package, but this package is enough for me. There are no problems with the sessions, nor with any other difficulties.

For more than 1.5 months, the site has been working in production, there are no problems with this package https://github.com/Hunternnm/laravel-radronner. Everything works perfectly.

**Comment by rauanmayemir** [comment]
@Hunternnm Can confirm that your package works great.

It needs more care due to the use of resetters, but once the config is taken care of, I'm seeing the performance boost I was expecting to get. (I did not see any perf improvement with https://github.com/avto-dev/roadrunner-laravel)

I still need to confirm it in production, but this feels like the right approach.

**Comment by wolfy-j** [comment]
Feel free to add integration badges and notes here: https://github.com/spiral/roadrunner-docs/blob/master/integration/laravel.md

I assume we can close this issue now :)
