### ISSUE TITLE
[etc][laravel] dd() and dump() functions can works!

### ISSUE THREAD

**Issue by tarampampam** [spiral/roadrunner#107]
> This can be usefull for somebody

Using Laravel + RoadRunner you cannot use `dd()` and `dump()` functions in your applications for fast code debugging (you will catch error like `... possible echo ...`). But, with small changes in your code (or install one package into your `dev` dependencies) - you can :)

Without many words, look next commits:

- https://github.com/avto-dev/dev-tools/commit/20689dce1455bde58e2c351963ec5903809e7026
- https://github.com/avto-dev/dev-tools/commit/5d79e8bcbcbabbe49ea4f9ac31a2a96c1709ea5a (previous commit a little bit fixed =) )

Package with this (and not only) feature: https://github.com/avto-dev/dev-tools

**Comment by wolfy-j** [comment]
You can post it (and i can pin it at our Discord service), this is not the issue :)

**Comment by wolfy-j** [comment]
Discord link located in README.md file, also check this way of dumping as well: https://github.com/spiral/roadrunner/wiki/Debugging

**Comment by tarampampam** [comment]
Sure, this is not issue ("tag" `etc` says about it, i think)! But a lot of people at first look for answer into issues :)

**Comment by wolfy-j** [comment]
Well, this ticket will be here forever now, so they will find it

**Comment by tarampampam** [comment]
And thank you very much for the RR. This is awesome!
