### ISSUE TITLE
[IDEA] I have thoughts about the .rr config

### ISSUE THREAD

**Issue by fenric** [spiral/roadrunner#108]
Do you plan to implement loading configurations from files:
`.rr.yml.dist` – Store it in GIT. Not a priority file. Default config.
`.rr.yml` – For local. Priority file/config.

Example usage:
```bash
git pull origin master
cp .rr.yml.dist .rr.yml 
```

**Comment by wolfy-j** [comment]
I do not plan to implement such feature as it might cause unexpected results when handled properly.

**Comment by fenric** [comment]
> I do not plan to implement such feature as it might cause unexpected results when handled properly.

I understand you, thank you very much for the quick answer. I will use `.rr.yml.example` :)
