### ISSUE TITLE
[Idea] FastCGI listener

### ISSUE THREAD

**Issue by Alex-Bond** [spiral/roadrunner#115]
Hey!

How about FastCGI listener instead of regular HTTP? I think it gonna be a faster and probably more advanced solution because most of the people still want to place Nginx in from of RR.

**Comment by AlexPravdin** [comment]
I support this suggestion :)

**Comment by BunnyHolder** [comment]
I run in production with symfony4.2 in docker container. I share mysql and redis resource with unix sock via docker volumes.  And I really would love that i could do that backwards.

I don't have skills in go, yet, but i can test in ubuntu/centos/docker setup in low and very high tier servers.

**Comment by wolfy-j** [comment]
This is possible to implement using the same communication method between RR and PHP but the new frontend interface. https://golang.org/pkg/net/http/fcgi/ it sounds like Go MIGHT support FastCGI out of the box and compatible with net/http.

**Comment by AlexPravdin** [comment]
I think an ability to have such option will be great.

**Comment by donparapidos** [comment]
For sure you would gain bigger audience if t FastCGI would be supported

**Comment by wolfy-j** [comment]
That's has been planned for 1.5.0 release. I'm also glad to accept anyone's help to deliver this feature. I can consult how to implement it.

The RR **feature** development is currently at rest since I have to complete the documentation for another large OS project.

**Comment by wolfy-j** [comment]
Regarding FastCGI being faster: https://gist.github.com/hgfischer/7965620

**Comment by wolfy-j** [comment]
If no issues found it will be shipped with next version.
