### ISSUE TITLE
Working directory config

### ISSUE THREAD

**Issue by AlexPravdin** [spiral/roadrunner#116]
Hello.
Thank you for the very good app.
But working with it in different environments (local dev, staging, prod) can makes it hard to run RR from the serving directory. And I didn't found any CLI/config command to set it up. Is there such command/config? Would you add it if there is no such comand? For example `http.rootDir`.

**Comment by wolfy-j** [comment]
RR automatically detects the root directory based on the location of .rr config file, all of the paths are relative to this configuration.

**Comment by AlexPravdin** [comment]
This require to store config files where the service wants and applies restriction. What if I don't want to store the config file in the web root but somewhere else where it is convenient for me?

**Comment by wolfy-j** [comment]
I can add a flag to specify working dir directly then.

**Comment by AlexPravdin** [comment]
Yes, it would be very appreciated, thanks!

**Comment by wolfy-j** [comment]
Expect in 1.3.5

**Comment by AlexPravdin** [comment]
Thanks a lot!
