### ISSUE TITLE
Remove colors from console output when stdout is not a terminal

### ISSUE THREAD

**Issue by AlexPravdin** [spiral/roadrunner#117]
When RR is run in Docker container and logs are written to plain text then text log messages have non-printing chars and reading logs become very painful:

> [36mINFO[0m[0058] [96m61.45.206.236[0m [1;90m{32.6ms}[0m [32m200[0m [1;97mGET[0m http://****/health-check

As I understand it is possible to check output pipe type does it support colors or not. Because I saw when an application output to visual console have colors, but output to a text file don't. Or add an option to remove exsessive formatting.

I need to keep access log with all the requests processed by the service.

Edit:
It seems this can be easily implemented using something like this: https://rosettacode.org/wiki/Check_output_device_is_a_terminal#Go

**Comment by wolfy-j** [comment]
Expect in 1.3.5
