### ISSUE TITLE
Confusing config parameter name http.maxRequest

### ISSUE THREAD

**Issue by AlexPravdin** [spiral/roadrunner#121]
Hello,
Thanks for your gread job! But I found confusing the http.maxRequest parameter name. Intuitively this name relates to the maxumim number of requests. But it defines the maxumim size. Is it possible to rename it to someting like `maxRequestSize`?

**Comment by wolfy-j** [comment]
Unfortunately, it will cause BC on config level, this option will stay in config in this form till next Major release.

**Comment by wolfy-j** [comment]
Ok, my friend just got the same confusion. But confirmed.

**Comment by AlexPravdin** [comment]
We can support both names until the next major release.

**Comment by AlexPravdin** [comment]
And print a hint on startup that the old one is deprecated.

**Comment by wolfy-j** [comment]
Available in 1.4.0, see sample config for configuration example https://github.com/spiral/roadrunner/blob/master/.rr.yaml
