### ISSUE TITLE
A way to define max execution time

### ISSUE THREAD

**Issue by speller** [spiral/roadrunner#122]
Hi,
Is there a way to define request max execution time? If a script will enter an infinite loop (for example) it seems it will never be killed.

**Comment by Alex-Bond** [comment]
Thats actually really good question. @wolfy-j lets add TTK config maybe?

**Comment by wolfy-j** [comment]
If you acknowledge that I can only KILL worker process (i.e. cause data corruption on looooong queries) - I'm fine doing that.

**Comment by Alex-Bond** [comment]
We can do TTK for request processing. If worker spend more than 60 seconds (for example) we will kill the worker and send 504 error to the client

**Comment by wolfy-j** [comment]
That is correct, I'm pointing that I will have to physically KILL workers. Meaning you would have to be careful setting TTK.

**Comment by Alex-Bond** [comment]
It is kind of the same as max_execution_time but for RR.

**Comment by wolfy-j** [comment]
Correct. I can work on it and on TTL as well.

**Comment by speller** [comment]
Yes, killing a worker will be good approach. Thanks! Let's set 60 sec timeout by default.

**Comment by BunnyHolder** [comment]
Maybe RR could use some of php.ini settings as default value for RR. Drop in experience could get better.

**Comment by wolfy-j** [comment]
We do not read php.ini in RR service at the moment. I'm currently planning to implement functionality to provide much more flexible control on worker livecycle in rr server, it will open the gate to functionality like max lifetime, proactive memory monitoring and adaptive scalers.

**Comment by wolfy-j** [comment]
Available in 1.4.0, see sample config for configuration example https://github.com/spiral/roadrunner/blob/master/.rr.yaml

**Comment by camohob** [comment]
> Available in 1.4.0, see sample config for configuration example https://github.com/spiral/roadrunner/blob/master/.rr.yaml

execTTL is solution for http service, but if i using `roadrunner.Server` directly, how can i use exec TTL?

**Comment by wolfy-j** [comment]
Hi,

you can attach the controller to any Server:

https://github.com/spiral/roadrunner/blob/master/server.go#L67
https://github.com/spiral/roadrunner/blob/master/controller.go#L4

You can implement any control logic inside it... or use the controller from Limit service:

https://github.com/spiral/roadrunner/tree/master/service/limit (you'll have to grab it from the config).

Or you can make your service expose Service() method and then you can point limit to it.
