### ISSUE TITLE
[Feature Request] Ability to output logs in raw format

### ISSUE THREAD

**Issue by acelot** [spiral/roadrunner#124]
At this time, the `rr` controls the format of the log output. We have `colorized`, `plain` and `json` output formats. Unfortunately, the underlying PHP application cannot specify the log level, except `WARNING` and `ERROR`. But applications can write to the log different message types such as `INFO`, `NOTICE`, `CRITICAL`, `ALERT` etc. In addition, developers can have their own `json` log formats, and the `rr` imposes its own format `{"level":"debug","msg":"new worker pool","time":"2019-02-18T02:28:49Z"}`.

Based on these thoughts, can the `rr` give more transparent control over the logging mechanism?
Maybe some `raw` type of logging? Or implement `PSR/LoggerInterface` by `RoadRunner\Worker`?

**Comment by Alex-Bond** [comment]
Duplicates #77

**Comment by wolfy-j** [comment]
Do you mean mix RR log and application specific logging? This is possible via custom logger service in RR.

**Comment by acelot** [comment]
@wolfy-j How to use custom logger? I can not find information about this in wiki.

**Comment by wolfy-j** [comment]
There is no such thing as a custom logger, but it can be created as a service. I was referring to such possibility. Probably will add into CE.

**Comment by wolfy-j** [comment]
I would like to merge this issue with #77
