### ISSUE TITLE
Ability to log real client ip address instead of load balancer

### ISSUE THREAD

**Issue by AlexPravdin** [spiral/roadrunner#125]
Hi,
When using RR app in AWS behind ELB (application load balancer) the RR log records looks like this:

> time="2019-02-20T06:30:48Z" level=info msg="10.0.13.180 {327ms} 200 POST http://******.ap-northeast-1.elb.amazonaws.com/working-url"

In the IP address field we can see the ELB IP address. It would be great if it will be possible to insert the real client IP address here instead of ELB.

**Comment by sonu27** [comment]
@wolfy-j Just need to use `X-Forwarded-For` header (https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html)

Both client and proxy IPs should be recorded though.

**Comment by wolfy-j** [comment]
Available in 1.4.0, see sample config to configure trusted proxies https://github.com/spiral/roadrunner/blob/master/.rr.yaml
