### ISSUE TITLE
kill -1 pid

### ISSUE THREAD

**Issue by 514366607** [spiral/roadrunner#128]
when I kill -1 pid and restart ./rr serve -v then output this error.

ERRO[0000] [http]: unable to connect to worker: unexpected response, header is missing: signal: killed

**Comment by Alex-Bond** [comment]
Hey!

You sure you kill the right process? To me, it looks like you killing the worker, not master.

**Comment by 514366607** [comment]
I be sure the ./rr process。

**Comment by 514366607** [comment]
root      4966  1927  3 05:46 pts/1    00:00:06 ./rr serve -v

kill -1 4966

**Comment by Alex-Bond** [comment]
Ok. Why you killing with -1? Why not -9?

**Comment by 514366607** [comment]
yet , kill -1(SIGHUP)

**Comment by Alex-Bond** [comment]
-1 will not correctly stop worker (bindings https://github.com/spiral/roadrunner/blob/master/cmd/rr/cmd/serve.go).

**Comment by 514366607** [comment]
but I can't find php process to kill.......

ps -ef|grep php

**Comment by wolfy-j** [comment]
Have you tried http:workers command? It will give you list of your php workers with their pids. Why do you want to kill rr? I’m planning adding command to stop it remotely and gracefully, hope it will help.

**Comment by 514366607** [comment]
./rr http:workers
Error: dial tcp 127.0.0.1:6001: connect: connection refused

I think signal(SIGHUP) can be reload rr service...
forget ./rr http:reset to reset php worker....
kill -1 pid then service don't work now.....

**Comment by 514366607** [comment]
invalid data found in the buffer (possible echo)

true error is this.

**Comment by Alex-Bond** [comment]
> invalid data found in the buffer (possible echo)
> 
> true error is this.

Check your app. Probably you have some panic and exception

**Comment by 514366607** [comment]
sorry , I'm test file on development environment ,files being delete.....
protocol.go  37   no dispose err,I don't know if it was intentional？
```
body, p, err := rl.Receive()
if !p.HasFlag(goridge.PayloadControl) {
	return 0, fmt.Errorf("unexpected response, header is missing")
}
```

**Comment by wolfy-j** [comment]
hmm, good catch. but i believe the error will be related to broken pipe and won't help much, i will improve this part.
