### ISSUE TITLE
[FEATURE REQUEST] Lazy (deferred/late/on demand) run workers

### ISSUE THREAD

**Issue by 4n70w4** [spiral/roadrunner#131]
Hi! I use nginx + php-fpm in docker containers and migrate to roadrunner.
But during the migration process I encountered the problem of building and running images.

My current pipeline:

- Build images 
- Add volumes with app code
- Run containers
- Run service commands: `composer install`, etc
- Add nginx ip to external balancer

And all work ok.

But with roadrunner this pipeline dont work, i get exception because roadrunner start worker script before composer install dependencies. Remake pipeline is very hard. It would be nice to be able to delay the start of the worker.

`docker-compose logs -f --tail 20 php`

```
Attaching to alfa_php_1
php_1        | Stack trace:
php_1        | #0 {main}
php_1        |   thrown in /var/www/app/current/worker.php on line 43
php_1        | Fatal error: Uncaught Error: Class 'Spiral\Goridge\StreamRelay' not found in /var/www/app/current/worker.php:43
php_1        | Stack trace:
php_1        | #0 {main}
php_1        |   thrown in /var/www/app/current/worker.php on line 43
php_1        | DEBU[0000] [rpc]: stopped
php_1        | DEBU[0000] [static]: disabled
php_1        | DEBU[0000] [rpc]: started
php_1        | DEBU[0000] [http]: started
php_1        | ERRO[0000] [http]: unable to connect to worker: PHP Fatal error:  Uncaught Error: Class 'Spiral\Goridge\StreamRelay' not found in /var/www/app/current/worker.php:43
php_1        | Stack trace:
php_1        | #0 {main}
php_1        |   thrown in /var/www/app/current/worker.php on line 43
php_1        | Fatal error: Uncaught Error: Class 'Spiral\Goridge\StreamRelay' not found in /var/www/app/current/worker.php:43
php_1        | Stack trace:
php_1        | #0 {main}
php_1        |   thrown in /var/www/app/current/worker.php on line 43
php_1        | DEBU[0000] [rpc]: stopped
alfa_php_1 exited with code 0
```

**Comment by wolfy-j** [comment]
I'm not sure what will be the proper way to implement it, timeout based? If so why not just start command after some time.

**Comment by 4n70w4** [comment]
The main idea is that the roadrunner does not have to exit on errors in the worker.

I run RR in docker as command, so it is important that RR does not exit so that the container does alive. But now if the code of the worker cannot be executed - the RR is exited and the container dies. This does not allow run additional commands to initialize the application to be executed in the exited container.

**Comment by wolfy-j** [comment]
OK, i will think what can be done there.

**Comment by sonu27** [comment]
@4n70w4 ideally when you run your containers the dependencies should be built already.

**Comment by 4n70w4** [comment]
@sonu27 in the development environment it is difficult to do.

php-fpm containers can be start without pre-build and assembled after build.
It is very flexible and convenient.

**Comment by nocive** [comment]
Agree, this is also a blocker for us.
I'm currently thinking about shipping a default dummy worker but the fact the RR's configuration is not modular (ie, as seen in fpm with pool.d/fpm.d include directories) makes it hard to dynamically configure workers for each app using the same base image.

**Comment by wolfy-j** [comment]
Your blocker is not modular configuration or lazy loading workers?

**Comment by nocive** [comment]
Both, in a way.

If the configuration was more modular it would be easier to work around the fact that workers aren't lazy.

Ideally if we could have the server listening without any workers defined and then drop the worker configuration in a `worker.d/` directory, it believe it would be a non issue.

What I'm currently doing is using s6 overlay and template the configuration on startup based on env environments, but that wasn't a stretch to achieve since I was already leveraging s6 with fpm anyway.

**Comment by wolfy-j** [comment]
@nocive you can use modular configuration since 1.4.4

**Comment by nocive** [comment]
@wolfy-j this is great, thanks! Also love the new fastcgi interface and the prometheus/metrics features you added recently! Cheers! :+1: :palm_tree:

**Comment by 48d90782** [comment]
To allocate an additional worker we can create a pool's interface `AddWorker`method to add additional workers. But it will be reset to the initial number after `./rr reset` command. And call that method from the HTTP plugin RPC bus.

**Comment by 48d90782** [comment]
@4n70w4 feel free to reopen the issue if #638 won't solve your problem. RR1 currently out-of-date and will receive only security issues.

**Comment by 4n70w4** [comment]
Thank you. Unfortunately, there is no way to check now. I am engaged in other projects and other technologies. But I will keep in mind.
