### ISSUE TITLE
Hosts definition, ssl certs, SNI

### ISSUE THREAD

**Issue by sinitsa** [spiral/roadrunner#134]
Hello everybody,

I did not find information on this issue in the documentation and other discussions, probably the answers are simply obvious to everyone, so please tell me where to look.

Is it possible to specify in the configuration parameters - domain, not IP?
Is it possible to start one server for several domains and accordingly, different ssl-certificates and their substitution (is it possible to use SNI here)?

And if I need to run several related applications (for example, app for website.com and app for subdomain for images - images.website.com), will there be a correct way, to push everything into one RoadRunner server? And in general, can I have several pools for different workers for different subdomains, or better to run applications in different RR servers on different ports (or IP) with loadbalancer (NGINX or HAProxy etc.) standing in front of everything?
What architecture is expected here?

PS: Thank you for the great product, a rare case when it is really pleasant to use (especially in the PHP world ;)

**Comment by wolfy-j** [comment]
Hi @sinitsa, thank you for your question.

In our concept RoadRunner is not really web-server to replace nginx on the top level, instead, it is an application server which supposes to have deep integration with each underlying project. Basically, it is designed to be easily customized for each specific use-case.

We practice using nginx as reverse-proxy at top of multiple rr applications, each located in the different containers.

**Comment by sinitsa** [comment]
Thank you very much!

PS: Did I understand correctly that, if desired, I can also run several rr applications within the same container, on different ports with different workers (specifying different configurations at startup), can they live together?

**Comment by wolfy-j** [comment]
Yes, this is correct.

**Comment by itsursujit** [comment]
@wolfy-j If we do rever-proxy with nginx, won't that affect overall performance of application running on rr?

**Comment by wolfy-j** [comment]
It will affect it a little bit but not significant, nginx won’t be a bottle neck in this case.
