### ISSUE TITLE
How about create repository "awesome roadrunner list"?

### ISSUE THREAD

**Issue by Ostap34JS** [spiral/roadrunner#137]
And there to group all the repositories that are associated with roadrunner.

**Comment by Ostap34JS** [comment]
for example, like this: https://github.com/chiraggude/awesome-laravel

**Comment by wolfy-j** [comment]
We are currently working on the website which is going to be live syncing the documentation from there:
https://github.com/spiral/roadrunner-docs

This will allow you to PR any changes to docs or add links to external libraries. :)

**Comment by wolfy-j** [comment]
Sneak peak: http://prntscr.com/n1bz89

**Comment by Ostap34JS** [comment]
Cool, thanks
