### ISSUE TITLE
Perfomance degradation on Laravel 5.8

### ISSUE THREAD

**Issue by Sho0terInfo** [spiral/roadrunner#138]
I think, RR not ready for production use with Laravel

i7-7700k 64 GB DDR4 Debian
>
>ab -kc 4 -t 60
>
>RR 1.3.7 (32 piped workers) / PHP 7.3.3 / LARAVEL 5.8 (NO MEMLEAKS, memory usage stable)
>
>Requests per second:    149.45 [#/sec] (mean)
>Requests per second:    71.93 [#/sec] (mean)
>Requests per second:    55.46 [#/sec] (mean)
>Requests per second:    46.01 [#/sec] (mean)
>Requests per second:    41.42 [#/sec] (mean)
>Requests per second:    37.43 [#/sec] (mean)
>Requests per second:    33.59 [#/sec] (mean)
>Requests per second:    32.06 [#/sec] (mean)
>Requests per second:    29.99 [#/sec] (mean)
>Requests per second:    28.61 [#/sec] (mean)
>
>PHP-FPM 7.3.3 / LARAVEL 5.8 
>Requests per second:    325.42 [#/sec] (mean)
>Requests per second:    327.17 [#/sec] (mean)
>Requests per second:    326.85 [#/sec] (mean)
>Requests per second:    322.50 [#/sec] (mean)
>Requests per second:    325.70 [#/sec] (mean)
>...etc

```
<?php

use Spiral\Goridge\StreamRelay;
use Spiral\RoadRunner\Worker;
use Spiral\RoadRunner\PSR7Client;
use Nyholm\Psr7\Factory\Psr17Factory;
use Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory;
use Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\Http\Kernel;
use Kernel\Http\Request;

require_once(__DIR__ . '/../vendor/autoload.php');

class RoadRunner
{
    protected $psr7;
    protected $requester;
    protected $responder;
    protected $app;
    protected $kernel;

    public function __construct()
    {
        $this->psr7 = new PSR7Client(
            new Worker(
                new StreamRelay(STDIN, STDOUT)
            )
        );
        $this->requester = new HttpFoundationFactory;
        $this->responder = new PsrHttpFactory($psr17 = new Psr17Factory, $psr17, $psr17, $psr17);
        $this->app = require_once(__DIR__ . '/../bootstrap/app.php');
        $this->kernel = $this->app[Illuminate\Contracts\Http\Kernel::class];
    }

    public function handle(): void
    {
        while ($psr7Request = $this->psr7->acceptRequest()) {

            $_SERVER['REQUEST_TIME_FLOAT'] = $_SERVER['REQUEST_TIME_FLOAT'] ?? \microtime(true);

            try {

                $this->psr7->respond(
                    $psr7Response = $this->responder->createResponse(
                        $response = $this->kernel->handle(
                            $request = Request::createFromBase(
                                $this->requester->createRequest($psr7Request)
                            )
                        )
                    )
                );

                $this->kernel->terminate($request, $response);

            } catch (\Throwable $e) {

                $this->psr7->getWorker()->error((string) $e);
            }
        }
    }
}

(new RoadRunner)->handle();
```

**Comment by wolfy-j** [comment]
Can you provide a bit more information about underlying application?

**Comment by wolfy-j** [comment]
Also, have you tried integrations where you don’t need to covert from one request format to another?

**Comment by Sho0terInfo** [comment]
> Also, have you tried integrations where you don’t need to covert from one request format to another?
I dont know how to use laravel with pure psr7 request.


> Can you provide a bit more information about underlying application?
Its hello-world-like application without any orm modelso or somethink heavy. All time wokrer use less then 16 mb RAM. But first requests TTFB takes near 2ms and during the test its up to 200ms without load.

**Comment by wolfy-j** [comment]
That is odd. Can you try one of the following integrations:
https://packagist.org/packages/avto-dev/roadrunner-laravel
https://packagist.org/packages/cubekode/roadrunner-laravel
https://packagist.org/packages/hunternnm/laravel-roadrunner
https://packagist.org/packages/updg/roadrunner-laravel

There is definitely something withing "terminate".

**Comment by Sho0terInfo** [comment]
> That is odd. Can you try one of the following integrations:
> https://packagist.org/packages/avto-dev/roadrunner-laravel

Does not support laravel 5.8

> https://packagist.org/packages/cubekode/roadrunner-laravel

Got error, because this bridge does not suppert overriden laravel-reqeust

> https://packagist.org/packages/hunternnm/laravel-roadrunner
> https://packagist.org/packages/updg/roadrunner-laravel
> 
> There is definitely something withing "terminate".

**Comment by Sho0terInfo** [comment]
UPD: yea, you're right, probleam near "terminate" method.
I will explore further.

**Comment by Sho0terInfo** [comment]
I am found a problem: its https://github.com/rcrowe/TwigBridge
Migrating to native laravel's Blade solved perfomance degradation
Its not solution for me, so i will be explore twigbridge package
P.S. Terminate not a problem, without it app throws 500 erorr wich rendering by blade instead of twig

**Comment by Sho0terInfo** [comment]
SO, final solution. Its no RR issue, but...
Laravel has some introduction features, like needs to reload Session and Auth service providers for reload its state. I have some Service Providers (like determinate current request language) wich needs to reload. In this service provider I am definening some view composers. AND problem here. In each request service provider add view comporsers wich NOT REPLACE and with each next request Template Endinge do more callbacks for each composed view. Its cause linear perfomance degradation.
Be careful with long-life services :)

**Comment by Sho0terInfo** [comment]
> That is odd. Can you try one of the following integrations:
> https://packagist.org/packages/avto-dev/roadrunner-laravel
> https://packagist.org/packages/cubekode/roadrunner-laravel
> https://packagist.org/packages/hunternnm/laravel-roadrunner
> https://packagist.org/packages/updg/roadrunner-laravel
> 
> There is definitely something withing "terminate".

SO, final solution. Its no RR issue, but...
Laravel has some introduction features, like needs to reload Session and Auth service providers for reload its state. I have some Service Providers (like determinate current request language) wich needs to reload. In this service provider I am definening some view composers. AND problem here. In each request service provider add view comporsers wich NOT REPLACE and with each next request Template Endinge do more callbacks for each composed view. Its cause linear perfomance degradation.
Be careful with long-life services :)
