### ISSUE TITLE
about usage of die/exit

### ISSUE THREAD

**Issue by littlexiang** [spiral/roadrunner#139]
Is it true that should avoid using die/exit for it quits the worker
so how to deal with things like image output
for example
`
echo $imagick->outputPNG();
exit()
`

**Comment by wolfy-j** [comment]
Yes, the whole concept of not dying workers is that they should not die. :)

Try to find the method which will return you image body as string/bytes or use ob_start().

**Comment by littlexiang** [comment]
Thanks a lot. I'm using rr with Laravel, I'll find a way by using standard Response object.
I think this should be written into readme alone with the is_uploaded_file part.
thanks for the great job, it's quite convenient and amazing.

**Comment by wolfy-j** [comment]
Added to wiki. Thank you

**Comment by littlexiang** [comment]
in Laravel for example
the usually way, NOT OK
`
header('Content-Disposition: attachment;filename=foo.xlsx"');
header('Cache-Control: max-age=0');
$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
$writer->save('php://output');
exit();
`

instead
`
ob_start();
$writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
$writer->save('php://output');
$content = ob_get_clean();
return response()->make($content, 200, $headers_array);
`

**Comment by gyf19** [comment]
https://www.php.net/manual/zh/swoole-http-response.end.php   Can develop features?  @wolfy-j

**Comment by wolfy-j** [comment]
@gyf19 the `respond` method is essentially doing the same thing.

**Comment by gyf19** [comment]
@wolfy-j  This feature is what I need 。 
Swoole\Http\Response::end function
Send data for the HTTP request and 《 finish the response 》，  
finish the response , php code will not continue to execute.  This feature is what I need

**Comment by wolfy-j** [comment]
Try to use ->stop() method of worker.

**Comment by gyf19** [comment]
thank you for your reply  @wolfy-j 

Use ->stop() method to restart the worker   ，Affect performance

**Comment by wolfy-j** [comment]
This is correct, stop and restart is an expensive operation. Why do you need it exactly?

**Comment by gyf19** [comment]
@wolfy-j  
  1.  The original code will use the exit() method  
 2.  Developers also accidentally use the exit() method

**Comment by wolfy-j** [comment]
@gyf19 unfortunately, RR can not handle applications like that. Any die() or exit() call with stop the worker and will completely eliminate the performance boost. In scenarios like that you have to use classic php-fpm setup or rewrite code to remove exit() calls.

**Comment by gyf19** [comment]
@wolfy-j  thank
