### ISSUE TITLE
Request: additional documentation for config file and RPC

### ISSUE THREAD

**Issue by Firehed** [spiral/roadrunner#14]
Right now, there's little clear documentation about the RPC services that Roadrunner offers (nor what they offer) - really just how to enable it. From a comment in the reddit thread introducing this, being able to gather metrics are tangentially mentioned (prometheus was in an example) but it's unclear what can be exposed, how it can be extended, etc.

Related via #12 - guidelines for higher-level settings to run this successfully (e.g. `php.ini`, worker count, etc) would also be really helpful. Coming from php-fpm, it's hard to know what translates across or, more generally, what best practices are.

**Comment by wolfy-j** [comment]
We will create more documentation for that, in a meantime:
1) This is RPC service which is provided by HTTP service: https://github.com/spiral/roadrunner/blob/master/service/http/rpc.go
2) The easiest way to connect to use Goridge/RPC over the socket configured in RPC section of config:
```php
$relay = new Goridge\SocketRelay('localhost', 6001);
$rpc = new Goridge\RPC($relay);

print_r($rpc->call('http.Workers', true));
//print_r($rpc->call('http.Reset', true));
```

Same method used in `rr http:workers` command: https://github.com/spiral/roadrunner/blob/master/cmd/rr/http/workers.go#L107

You can create your own Golang services with RPC exposure using the same approach as here:
https://github.com/spiral/roadrunner/blob/master/service/http/service.go#L60

```golang
if r, ok := c.Get(rpc.ID); ok >= service.StatusConfigured {
		if h, ok := r.(*rpc.Service); ok {
			h.Register("myService", &rpcServer{s})
		}
	}
```

RPC server must be written based on net/rpc rules: https://golang.org/pkg/net/rpc/

**Comment by wolfy-j** [comment]
see updated README
