### ISSUE TITLE
When building w/ Composer/Docker: Unable to find image 'spiralscout/rr-build:latest' locally

### ISSUE THREAD

**Issue by mattjwhelan** [spiral/roadrunner#140]
I installed spiral/roadrunner in a new PHP project using Composer, then tried to run vendor/bin/rr-build in my project directory per the Quick Builds instructions in the documentation:

https://roadrunner.dev/docs/intro-quick-builds

I should note that I am logged into Docker Hub registry when running command.

Here's what I receive:

```
Unable to find image 'spiralscout/rr-build:latest' locally
docker: Error response from daemon: pull access denied for spiralscout/rr-build, repository does not exist or may require 'docker login'.
```
I was able to successfully build the binary using the make command and my local Go environment.

**Comment by wolfy-j** [comment]
Can you try now? Docker privacy settings were broken. :(

**Comment by mattjwhelan** [comment]
Thanks, that fixed it. Successfully built just now.
