### ISSUE TITLE
How about fatfree integration?

### ISSUE THREAD

**Issue by NetLancer** [spiral/roadrunner#148]
Hi there! I'm kina new to this product and to server sophisticated internals so beg your pardon aforehand for possible personal misperceptions :).
Has it been tested with fatfree php code (or maybe better to put: has been fatfree code tested for correct behaviour within roadrunner)? And if not, are there plans to extend integrations?
Thanx for promising web platform guys!

**Comment by BunnyHolder** [comment]
What is fat-free php code? You mean without PSR request handler implementation? If so, probably no. Because this is the main reason you can get more performance.

**Comment by wolfy-j** [comment]
PSR-7 is not required to make an integration, you can use underlying `HttpClient` to get access to raw request data. The main question is if fat-free supports request-response flow. Which is doesn't: https://github.com/bcosca/fatfree/blob/master/lib/base.php#L1589
https://github.com/bcosca/fatfree/blob/master/lib/base.php#L143

Fat free can't work in stateless mode (at least without major modifications).

**Comment by NetLancer** [comment]
Thanks for clear response guys :)
