### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by lda** [spiral/roadrunner#149]
As for now fatal errors are [printed to stdout](https://github.com/spiral/roadrunner/blob/master/cmd/rr/cmd/root.go#L101). I would like to rewrite these pieces of code so that errors are written to stderr. 

Will it be ok if I just add a new method to the `util` package (e.g. PrintfToStderr)?

**Comment by wolfy-j** [comment]
Sure, maybe it will be better to make util.Panicf (of Fatalf)? It can mimic the behavior of log.Panic and stop the application automatically.

**Comment by wolfy-j** [comment]
Similar way as in https://github.com/spiral/roadrunner/blob/master/service/http/config.go#L69

**Comment by lda** [comment]
Ok, I've opned #151
