### ISSUE TITLE
Array configuration in commandline

### ISSUE THREAD

**Issue by ThisIsAreku** [spiral/roadrunner#150]
I tried to define multiple extensions using command-line but it seems to only take the last one
```
rr serve \
    -o "http.address=:80" \
    -o "http.workers.pool.numWorkers=1" \
    -o "http.workers.command='php worker.php'" \
    -o "static.dir='web'" \
    -o "static.forbid='.php'" \
    -o "static.forbid='.htaccess'"
```

Is there a special syntax for array ?

_EDIT: fixed example after @spudro228 comment_

**Comment by wolfy-j** [comment]
Hmmm, there is no specific syntax for array yet (we have to create it). :( I wonder if it might be easier to ensure default values for static.forbid config https://github.com/spiral/roadrunner/blob/master/service/static/config.go#L26

I assume most of the people would like to hide .php, .htacess files.

**Comment by wolfy-j** [comment]
Similar way as in https://github.com/spiral/roadrunner/blob/master/service/http/config.go#L69

**Comment by wolfy-j** [comment]
RR now support modular configuration, is this issue still an issue?

**Comment by ThisIsAreku** [comment]
What do you mean by modular configuration ? The `include` option ?

**Comment by spudro228** [comment]
Maybe was missed " symbols

rr serve \
    -o "http.address=:80" \
    -o "http.workers.pool.numWorkers=1" \
    -o "http.workers.command='php worker.php'" \
    -o "static.dir='web'" \
    -o "static.forbid='.php'" \
    -o "static.forbid='.htaccess'"

**Comment by wolfy-j** [comment]
> What do you mean by modular configuration ? The `include` option ?
Yes.

Can you please check @spudro228 response, is this still an issue?

**Comment by ThisIsAreku** [comment]
The missing quotes were not present in my command line originally , i've edited the issue.
From what I understand, the _include_ directive allow to define others YAML files to be merged into the final configuration.
It still doesn't allow to define multiple times the same option in the command line.

I could add a yaml file with some defaults, but in my use case I only add a `Dockerfile` to the project with all the options defined inside, so i can bootstrap a new project by copying just a single file.

**Comment by wolfy-j** [comment]
![gif](https://i.makeagif.com/media/4-03-2017/LTnIcf.gif)

**Comment by wolfy-j** [comment]
See 1.5.3
