### ISSUE TITLE
Support for zend-diactoros v2.x

### ISSUE THREAD

**Issue by dkuhnert** [spiral/roadrunner#155]
In v1.4.0 the `http-interop/http-factory-diactoros` dependency has been re-introduced and prevents using roadrunner with zend-diactoros v2.x.
The specific commit is e303434db0930339bb7aa89b904848e92483703f

Previous Issue: #59
Merge of pull request #82 (c7dbbb682e272c9eace7cf9d7d8fbdeba8ad2636) or more specific 40d66629617f7a96b9005df356b94ab3b4dfb98f

To me, this looks like an error while resolving merge conflicts 😅

Any ideas?

**Comment by wolfy-j** [comment]
Yes, this seems to be a merge issue, the dependency must not be used anymore. Will be addressed in the next update, if you can create PR in the meantime it will be appreciated.

**Comment by dkuhnert** [comment]
That was a quick! PR is opened, thanks.

**Comment by wolfy-j** [comment]
fixed in 1.4.3
