### ISSUE TITLE
[RR2, STATIC] send Etag header in Response for static files

### ISSUE THREAD

**Issue by ihipop** [spiral/roadrunner#16]
I‘v noticed that there is no `Etag` returned in `static files`  response , any plans to add support for it?
Or, add a config item for it.

**Comment by wolfy-j** [comment]
Hi, we are currently using default net/http file handler. Let me check if we can expose caching capabilities.

**Comment by wolfy-j** [comment]
OK, this can be done: https://github.com/spiral/roadrunner/blob/master/service/static/service.go

**Comment by ihipop** [comment]
There already are some `caching capabilities` exposed, for example `Last-Modified` and `Date`, In most case,this is enough. 
I'm just asking the possibility  as an alternative  config item for this. (some times we don't want `Etag`,some times we did)
Thanks for your great work.

**Comment by wolfy-j** [comment]
Yes, this is definitely doable, I will keep this issue open for if someone want to help. Otherwise, we can consider adding this feature in a future release.

**Comment by Shikachuu** [comment]
Is this about `Etag` response header only or we are talking about also `If-Match` and `If-None-Match` request headers?

**Comment by 48d90782** [comment]
@Shikachuu I am open to suggestions :) I can implement both )

**Comment by Shikachuu** [comment]
@48d90782 I think that `If-Match` and `If-None-Match` is out of context for a static file serving.
I was asking, cause soon I'll have some freetime and this issue seems like a good match to shake up my rusty go skills.
Seems like `Etag` hasn't got any specific requirements for hash algorithm, is plain old sha1 fine?

**Comment by 48d90782** [comment]
@Shikachuu Yeah, according to the RFC https://tools.ietf.org/html/rfc7232#section-2.3, the hash algorithm is not defined, but according to the google docs https://cloud.google.com/storage/docs/hashes-etags#_ETags, MD5 is historically used as the hash for the `Etag`.
> I was asking, cause soon I'll have some freetime and this issue seems like a good match to shake up my rusty go skills.

Awesome :smile: 
Make sure, that the target branch for the RR2 is https://github.com/spiral/roadrunner/tree/2.0

**Comment by 48d90782** [comment]
Done in the #646
