### ISSUE TITLE
Wiki DNS broken

### ISSUE THREAD

**Issue by lucasantarella** [spiral/roadrunner#161]
Hey guys, I think the DNS on your wki sight is broken. DNS is supposed to resolve to https://34.229.58.67 but theres no DNS entry found for roadrunner.dev

**Comment by wolfy-j** [comment]
DNS is OK, http://whois.domaintools.com/roadrunner.dev Maybe your ISP blocks it?

**Comment by lucasantarella** [comment]
@wolfy-j You're right. Switched DNS providers and works fine. My bad.
