### ISSUE TITLE
Request error send error to sentry

### ISSUE THREAD

**Issue by pshirmanov** [spiral/roadrunner#165]
|---|Version|
|---|--|
|PHP| 7.1.30|
|Laravel|5.8.24|
|RR|1.4.3|

I used
`"updg/roadrunner-laravel": "^1.0"`

Don't send errors to sentry server from Road Runner docker container, when I put command `php artisan sentry:test` I saw sended error is good

```
[root@7ea88854ed88 www]# php artisan sentry:test
[sentry] Client DSN discovered!
[sentry] Generating test event
[sentry] Sending test event
[sentry] Event sent with ID: 1e10f4e5ecc74dda821943ed06fa974d
```
But the error ID: 1e10f4e5ecc74dda821943ed06fa974d does not appear on the sentry server
I looked code and error message was sended async to sentry server, maybe so RR did not show error

I wrote next code and stared in docker container with RR
```
 $data = [
            'event_id'  => '$EVENT_ID',
            'culprit'   => "Error",
            'timestamp' => '$EVENT_TIMESTAMP',
            'message'   => "Сообщение об ошибке",
            'tags'      => [
                'shell'       => '$SHELL',
                'server_name' => 'hostname',
                'path'        => 'pwd'
            ],
            'exception' => [
                [
                    'type'   => 'ScriptError',
                    'value'  => '$MESSAGE',
                    'module' => 'builtins'
                ]
            ]
        ];
        
        $jsonData = json_encode($data);
        $context  = stream_context_create([
            'http' => [
                'method'           => 'POST',
                'header'           => "Content-type: application/json\r\n" .
                    "X-Sentry-Auth: Sentry sentry_version=7, sentry_key=12a9dfe30f0040e08a108c33f09d2246, sentry_client=raven-bash/0.1\r\n" .
                    "Accept: application/json\r\n" .
                    "Connection: close\r\n" .
                    "Content-length: " . strlen($jsonData) . "\r\n",
                'protocol_version' => 1.1,
                'content'          => $jsonData
            ],
            'ssl'  => [
                'verify_peer'      => false,
                'verify_peer_name' => false
            ]
        ]);
        
        $rawdata = file_get_contents('https://sentry.my-soft.ru/api/27/store/', false, $context);
        
        dd($rawdata);
```
After execute code I saw next error
`worker error: invalid data found in the buffer (possible echo)`

I think so not impossible send request from container with RR

**Comment by wolfy-j** [comment]
Do not use dd as it will dump to STDOUT which is used for communication. Try error_log or send to SDTERR. Or switch worker to use sockets.

**Comment by pshirmanov** [comment]
Yes, I remove `dd` and use `error_log`, was message show on sentry server, but if use standard library  `"sentry/sentry-laravel": "^1.0.0"`, noticed that was message appeared on sentry server after shuting down the road runner server

May need to use https://github.com/UPDG/roadrunner-sentry?

**Comment by wolfy-j** [comment]
Does sentry/sentry-laravel have shutdown handler?

**Comment by wolfy-j** [comment]
The https://github.com/UPDG/roadrunner-sentry will report errors on golang end, it won't be able to handle exceptions in PHP.

**Comment by wolfy-j** [comment]
I have confirmed that Sentry works fine within RR workers using official https://packagist.org/packages/sentry/sentry . Make sure that your library does not handle exceptions using shutdown_handler, such approach won't work with the long-running application.
