### ISSUE TITLE
unable to allocate worker: worker timeout (1m0s)

### ISSUE THREAD

**Issue by fenric** [spiral/roadrunner#167]
I constantly get the following problem (on day 3-5 cases):

```
unable to allocate worker: worker timeout (1m0s)
```

I have the following server parameters:

```
RR: 1.4.3
CPU: 2
Memory: 2 GB
```

I have the following RR config:

```yaml
http:
  address: 127.0.0.1:8001
  workers:
    command: "php worker.php"
    pool:
      numWorkers: 2
      maxJobs: 1000
```

I have the following nginx config:

```
server {
    listen 80;
    server_name api.example.com;

    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}
```

I have the following systemd unit config:

```ini
[Unit]
After=network.target

[Service]
Type=simple
User=arus
Group=arus
WorkingDirectory=/home/arus/www/gateway
ExecStart=/usr/local/bin/rr serve -d
ExecReload=/usr/local/bin/rr http:reset
ExecStop=/bin/kill -s TERM $MAINPID
Restart=always

[Install]
WantedBy=multi-user.target
```

I have the following request handling logic (short example):

```php
while ($request = $client->acceptRequest()) {
    try {
        $response = $this->getRouter()->handle($request);
    } catch (Throwable $error) {
        $this->logFatalError($error, $request);

        $response = $this->getResponseFactory()->createResponse(500);
    }

    $client->respond($response);

    $entityManager = $this->getEntityManager();
    $entityManager->clear();
    $entityManager->getConnection()->close();
}

gc_collect_cycles();
```

I have the following worker logic:

```php
declare(strict_types=1);

use App\Http\Application;

require __DIR__ . '/vendor/autoload.php';

$container = require __DIR__ . '/config/container.php';

$application = $container->get(Application::class);

$application->run();

```

---

Please give advice... Maybe 2 cores for the server are few? Thanks so much for any help!

**Comment by wolfy-j** [comment]
What will happen if you'll try to call worker manually: https://roadrunner.dev/docs/usage-php-workers check Troubleshooting.

**Comment by wolfy-j** [comment]
Can you also profile how long it takes to perform: 

```
$entityManager = $this->getEntityManager();
$entityManager->clear();
$entityManager->getConnection()->close();
```

Maybe this code stuck and did not release the worker?

**Comment by fenric** [comment]
@wolfy-j I could repeat it like this:

```
ab -n 1000000 -c 1000 -H "X-Host: catalog" http://192.168.50.11:8001/test
```

Now I am looking for a problem place in the application...

**Comment by wolfy-j** [comment]
It seems like your application is too slow to handle 1000 concurrent requests over 2 workers. Try to bump number higher (8 workers or similar) or optimize your code a bit.

You can freely have as many workers as your memory allows you on IO bound application.

**Comment by wolfy-j** [comment]
Please let me know if there is anything can be done on RR end.

**Comment by l3lackheart** [comment]
![image](https://user-images.githubusercontent.com/25253808/135194287-fbe72490-cb74-4625-a8b4-05415cb91669.png)
err

**Comment by rustatian** [comment]
@l3lackheart Thanks, site on maintenance, will be available soon.
