### ISSUE TITLE
Http worker router question

### ISSUE THREAD

**Issue by mich4s** [spiral/roadrunner#170]
Is there any plan to provide any routing to yams file? This could also optimize execution by leaving compute heavy parts to Golang and run expected controller omitting php router or use rr as "lambda" runtime

**Comment by wolfy-j** [comment]
As part of generic RR build - no. However, we had some ideas about handling most of JSON REST endpoint processing on golang and communicate with PHP as with a thin service layer... But then we have discovered GRPC and this idea has been de-prioritized.

**Comment by wolfy-j** [comment]
To be honest this can be achieved very easily by adding your own service and http middleware. Considering that you would have to write golang code anyway you might write the middleware by yourself as well. Does it work or you looking for more high level abstraction?

**Comment by mich4s** [comment]
Well, my idea was to make able for full php developers to achieve this goal. I'm using rr as library right now to have my own "fast" router. But this could be done as part of library/plugin so there'll be no need to modify golang code.

**Comment by wolfy-j** [comment]
Well, it can be achieved using some middleware and PSR-7 attribute. I guess if you can provide an example of routing configuration it might help.

**Comment by wolfy-j** [comment]
Closed as a stalled issue.
