### ISSUE TITLE
h2c support in RoadRunner

### ISSUE THREAD

**Issue by filakhtov** [spiral/roadrunner#172]
Hello folks,

Garry here from BigCommerce.

We are currently evaluating RoadRunner as an app-server for some of our internal services and it is looking pretty promising, great job!

As part of our investigation, however it was discovered that RoadRunner does not support non-encrypted HTTP/2 connections (aka h2c). Based on my experience with Golang it is also relatively simple thing to implement, thanks to [x/net/http2/h2c](https://godoc.org/golang.org/x/net/http2/h2c).

There is a number of reasons as to why that can be beneficial such as:
- internal service to service communication can have different ways of securing traffic (such as LinkerD transparent encryption);
- request routing via the service mesh might require unencrypted traffic to make appropriate decisions;
- local development environment won't require a certificate and key to work with;

I'm curious if that is something that you guys will be interested in or is there a reason why it was explicitly avoided in the first place? I might consider contributing back some code to make that happen if there is no strong reason not to.

Implementation wise, my thinking is to add a new configuration option (that is off by default) to enable h2c by wrapping an HTTP/1 handler into the h2c handler. Any thoughts on that?

Cheers!

cc @precariouspanther

**Comment by wolfy-j** [comment]
Hi, we have no objections on adding such functionality. Let us know if you need any assistance on altering HTTP service.

**Comment by wolfy-j** [comment]
Added to `1.4.7`, thanks to @Alex-Bond 

H2C can be enabled via (disabled by default):
```yaml
http:
    http2.h2c: true
```

**Comment by filakhtov** [comment]
👏 thanks a lot!
