### ISSUE TITLE
swoole_pack instead of pack

### ISSUE THREAD

**Issue by morozovsk** [spiral/roadrunner#174]
Около года назад я проводил сравнение [swoole/workerman/roadrunner](https://github.com/morozovsk/webserver-performance-comparison) и roadrunner был медленнее раз в 5-15.
Мне было не совсем понятно, почему он настолько медленнее, пока я не наткнулся в описании, что при взаимодействии php и go используется pack/unpack. Тогда я вспомнил, что в рамках [моего исследования двухгодовалой давности](https://github.com/morozovsk/php-arrays-in-memory-comparison) я заметил, что pack/unpack хоть и даёт лучшие цифры по сжатию, но вот по скорости проигрывает хотя бы тому же swoole_pack где-то в 10 раз.
Было бы не плохо если в roadrunner добавили опцию, которая позволяла переключиться с pack на swoole_pack, что гипотетически должно повысить скорость roadrunner в разы.

**Comment by Alex-Bond** [comment]
Привет!

Из того что я понял - там разные вообще схемы пакования. У свуле она упрощенная.

**Comment by wolfy-j** [comment]
Привет, RR основан на Goridge Relay, так что в теории можно использовать любой метод общения. swoole_pack посмотрим, но пока, по ощущениям, bottleneck находится в pipes, а не в методе упаковки.

Один из вариантов решения - использования кастомного драйвера написанного на C (буквально нужен 1-2 метода), чтобы не тянуть всю свуле. Сейчас активно смотрим на адаптацию https://github.com/phpinnacle/ext-buffer (от @zloyuser)

В теории такой подход позволит серьезно съэкономить время обработки, на локальных бенчах выжимаем до 500к rps (мелкий пакет).

**Comment by FirestarterUA** [comment]
@wolfy-j,  это стало бы очень хорошим бонусом .

**Comment by wolfy-j** [comment]
Закрываю, горидж 3.0 включит опциональное С расширения для максимальной производительности и другие изменения протокола. @zloyuser работает над этим.

**Comment by wuros** [comment]
Вопрос остается открытым, как на горидже 3.0 изменить способ упаковки?

**Comment by wolfy-j** [comment]
Дождаться горидж 3.0.

**Comment by raoptimus** [comment]
Известна дата релиза?

**Comment by 48d90782** [comment]
@raoptimus После РР 2.0 (1Q2021), после него вероятно будем планировать горидж 3.0.

**Comment by raoptimus** [comment]
> @raoptimus После РР 2.0 (1Q2021), после него вероятно будем планировать горидж 3.0.

спасибо
