### ISSUE TITLE
How to run roadrunner as nonroot user? 

### ISSUE THREAD

**Issue by Zolotov88** [spiral/roadrunner#176]
When I'm trtiing to run RR as nonroot I get:
[http]: listen tcp 0.0.0.0:80: bind: permission denied
What can I do with it?

**Comment by Themodem** [comment]
You need to configure the listener with config

[https://roadrunner.dev/docs/intro-config](https://roadrunner.dev/docs/intro-config) will give you an overview

```
# http service configuration.
http:
  # http host to listen.
  address: 0.0.0.0:8080
```

Is the part you are looking for

**Comment by Zolotov88** [comment]
Thx!
