### ISSUE TITLE
Missed REQUEST_URI in server variables

### ISSUE THREAD

**Issue by POPSuL** [spiral/roadrunner#177]
Too many frameworks used `$_SERVER['REQUEST_URI']` variable to determine requested uri (at least symfony and symfony-based FWs).
I though that code https://github.com/spiral/roadrunner/blob/master/src/PSR7Client.php#L137 should contains something like that:

```
$server['REQUEST_URI'] = $rawRequest['ctx']['uri'];
```

**Comment by wolfy-j** [comment]
Feel free to submit PR. We are expecting your code to rely on PSR-7 Uri, but I see the value of adding such fallback.

**Comment by wolfy-j** [comment]
Added in upcoming version.
