### ISSUE TITLE
Add ability to skip the same version downloading with php rr binary downloader

### ISSUE THREAD

**Issue by drefixs** [spiral/roadrunner#179]
**Problem:**
I want to get full control of the version of rr with composer.json package manager.

But it has one little problem when I add it to post install/update composer scripts
```
    "scripts": {
        "update-scripts": [
            "./vendor/bin/rr get -l ./bin",
            "@auto-scripts"
        ],
        "auto-scripts": {
            "cache:clear": "symfony-cmd"
        },
        "post-install-cmd": [
            "@update-scripts"
        ],
        "post-update-cmd": [
            "@update-scripts"
        ]
    },
```

it's re-download the same version of the go binary each time I do composer install/update. 
I want to install rr binary deps with modern way as composer like deps with cache and hash checking.

**Proposal:**
At least we can add an ability to skip the same version downloading and don't do complex solution to download single bin deps file :). I did it with pull request #178. I add php logic to skip the same version downloading.

**FYI:**
Also I tried to add simple version command to go cli but stack with cobra.OnInitialize(... logic that init all container services and gets an error:
```
Error: [http]: key file 'server.key' does not exists
``` 
and stop this solution direction.

**Comment by drefixs** [comment]
I remembered about windows compatibility :) and moved solution from shell awk to Perl based regex.

**Comment by wolfy-j** [comment]
Thank you, the proposal looks good!

**Comment by wolfy-j** [comment]
Are you OK to wait till we will get more features for the next release or this is something which is currently pressing?

**Comment by drefixs** [comment]
It's ok to wait. Thanks you for the merging it to the master.
