### ISSUE TITLE
Reset getting stuck after many refreshes

### ISSUE THREAD

**Issue by samdark** [spiral/roadrunner#185]
Code to reproduce test case: [rr-test.zip](https://github.com/spiral/roadrunner/files/3615460/rr-test.zip)

1. `composer update`
2. `./vendor/bin/rr get`
3. `./rr serve -d -v`
4. Load page in a browser.
5. Edit PHP content of Responder. For example, change "File modified" to "File modified 123".
6. In another terminal do `./rr http:reset`. Check that reload actually happened (in server terminal there should be something like "DEBU[0260] new worker pool").
7. Repeat 4—6 until reset happens but PHP code used isn't refreshed.

OS: Windows 10 x64
PHP: 7.2.20 nts. Opcache turned on. XDebug turned on.

**Comment by samdark** [comment]
One more thing. That is **not** browser cache since in the `Responder` there's current timestamp outputted to make it obvious.

**Comment by Alex-Bond** [comment]
Саш, а можешь чекнуть запускается ли воркер вообще заново? Типа может выводи куда-то в файл какую-то строку перед началом цикла получения запросов.

**Comment by samdark** [comment]
@Alex-Bond yes, worker process ID is updated. Checked with

```php
$body->write('RR worker ID is ' . getmypid() . "\n");
```

**Comment by samdark** [comment]
`./rr http:workers -i` output:

```
+---------+-----------+---------+---------+--------------------+
|   PID   |  STATUS   |  EXECS  | MEMORY  |      CREATED       |
+---------+-----------+---------+---------+--------------------+
|   22752 | ready     |      44 | 24 MB   | 56 seconds ago     |
+---------+-----------+---------+---------+--------------------+
```

**Comment by Alex-Bond** [comment]
@samdark, in this case, I can think only about opcache. RR doesn't cache any finales internally. Reset literally means that RR will kill workers and start workers again (workers are just cli command)

**Comment by samdark** [comment]
Reproduced with Opcache turned off.

**Comment by Alex-Bond** [comment]
@samdark not cool. @wolfy-j any ideas?

**Comment by samdark** [comment]
Reproduced with XDebug turned off.

**Comment by samdark** [comment]
I think I've got an idea...

**Comment by wolfy-j** [comment]
https://www.iis.net/downloads/microsoft/wincache-extension

**Comment by samdark** [comment]
Wincache is to blame.

**Comment by wolfy-j** [comment]
Added to docs: https://github.com/spiral/roadrunner-docs/blob/master/usage/caveats.md
