### ISSUE TITLE
Detached mode support?

### ISSUE THREAD

**Issue by rustamwin** [spiral/roadrunner#186]
there is support for run workers in background?

**Comment by wolfy-j** [comment]
Please elaborate. Do you mean execute some task in background?

**Comment by rustamwin** [comment]
Yes. As `docker-compose up -d` run server in the background

**Comment by wolfy-j** [comment]
Currently, it does not support detached mode but feel free to PR it. RR is already able to stop by remote command so we only have to alter `serve` command handler.

**Comment by alexndr-novikov** [comment]
@rustamwin don't you mean "Start RR when you hit docker-compose up -d command"?
If you mean this - you can easily add this option to your docker-compose.yml for your service:
command: 'bash -c "/var/www/rr serve -d -v"'
where /var/www is path to your project
and RR will work in the background when you launch the container

**Comment by rustamwin** [comment]
> don't you mean "Start RR when you hit docker-compose up -d command"?

@alexndr-novikov No. I don't mean this. I mean start RR in background locally.

**Comment by artemmolotov** [comment]
@rustamwin 
> I mean start RR in the background locally.

Perhaps launching through `screen` is suitable for you? Example:
```
apk add screen
screen -dmS roadrunner -- rr serve -v -d
```
And you can easily attach window later by: `screen -x roadrunner`.

Or as a second (less elegant) way:
`rr serve -v -d >/dev/null 2>&1`
`rr serve -v -d STDOUT>/dev/null STDERR>&STDOUT`

**Comment by 48d90782** [comment]
@rustamwin Thanks for the question. Feel free to re-open this ticket if you have any more questions :smile:
