### ISSUE TITLE
[Feature Request] process metrics per worker

### ISSUE THREAD

**Issue by awprice** [spiral/roadrunner#195]
This is a feature request to add process metrics per worker, which will allow collection of CPU/memory/FD metrics for each worker process.

Currently, the metrics for the roadrunner go process are collected: https://github.com/spiral/roadrunner/blob/a72ccd1b6247a25c90fad317d98c884f3869b623/service/metrics/service.go#L29

Prometheus' processCollector could be used to collect the process metrics for each worker based on the worker's PID. It will need to be modified or copied to handle multiple processes, with the each PID being a metric label.

One issue I can forsee is that the cardinality will be quite high with each PID being a metric label.

**Comment by wolfy-j** [comment]
> One issue I can forsee is that the cardinality will be quite high with each PID being a metric label.

Which is the core issue, unfortunately. I can only suggest something like [min, avg, max]. Where min/max is one of the worse/best workers.

**Comment by wolfy-j** [comment]
Closed as stalled issue.
