### ISSUE TITLE
Error when Command contains spaces

### ISSUE THREAD

**Issue by AndreKR** [spiral/roadrunner#201]
I'm creating a new roadrunner.Server with:
```go
	rrServer := roadrunner.NewServer(
		&roadrunner.ServerConfig{
			Command: "C:\\Users\\John Smith\\Desktop\\roadrunner\\php.exe C:\\Users\\John Smith\\Desktop\\roadrunner\\roadrunner.php",
			Relay:   "pipes",
			Pool: &roadrunner.Config{
				NumWorkers:      int64(2),
				AllocateTimeout: 1 * time.Minute,
				DestroyTimeout:  1 * time.Minute,
			},
		})
```
and I'm getting
> `process error: exec: "C:\\Users\\John": file does not exist`

I tried adding quotes around the command but it doesn't help.

**Comment by wolfy-j** [comment]
Hi,

I see a few issues here:

1) The use of absolute paths and windows is never good combination.
2) You are trying to run roadrunner.php instead of a worker script.

Recommendation:
1) Make sure `php` is available in PATH
2) Run worker.php not roadrunner.exe

**Comment by AndreKR** [comment]
1. Even when PHP is in PATH, there would still be the issue with the space in the path to the worker script. PHP expects the path to the PHP script to be a single argument, but RoadRunner splits it into two. This function either needs to take quotes into account and leave quoted sections as single arguments or it needs to accept an array of arguments instead of parsing a single string:
https://github.com/spiral/roadrunner/blob/b0cedeabded6939acf71cb5e28c3094247110d86/server_config.go#L75-L76

2. `roadrunner.php` *is* my worker script, sorry for not making that clear.

**Comment by wolfy-j** [comment]
Oooops, sorry I've missed the extension. Long day at work. I see now that your folder contains space. Hm...

**Comment by wolfy-j** [comment]
What if I will give you the ability to redefine `makeCommand()` on your own? You only need to return new *exec.Cmd, would that work? Parsing is fine as well, but it will take some for me to dedicate time to fix it unless you want to PR.

**Comment by AndreKR** [comment]
Yes, sure, that'll work and it's also the more idiomatic way than parsing.

**Comment by wolfy-j** [comment]
You can actually create it via `Pool`, which is lower level, worker manager. It exposes all low-level functionality. The server is just a nice wrapper with config friendly API. It might be easier for embedding.

https://github.com/spiral/roadrunner/blob/master/static_pool_test.go#L21

**Comment by AndreKR** [comment]
That works well, thank you.
