### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by coxa** [spiral/roadrunner#211]
Problem 1
    - spiral/roadrunner v1.5.1 requires symfony/console ^2.5.0 || ^3.0.0 || ^4.0.0 -> no matching package found.
    - spiral/roadrunner v1.5.0 requires symfony/console ^2.5.0 || ^3.0.0 || ^4.0.0 -> no matching package found.
    - Installation request for spiral/roadrunner ^1.5 -> satisfiable by spiral/roadrunner[v1.5.0, v1.5.1].

I'm using "symfony/console": "5.0.*",

**Comment by wolfy-j** [comment]
PR will he appreciated. Otherwise, will be patched tomorrow.
