### ISSUE TITLE
Possibility to set cipher suite and TLS version

### ISSUE THREAD

**Issue by bognerf** [spiral/roadrunner#213]
Hi,

I recently SSL-tested some RoadRunner-based microservices (raw, **not** behind any SSL terminating proxy), here is an example:

```
 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      offered (NOT ok)
 TLS 1      offered (deprecated)
 TLS 1.1    offered (deprecated)
 TLS 1.2    offered (OK)
 TLS 1.3    not offered and downgraded to a weaker protocol
 NPN/SPDY   h2, http/1.1 (advertised)
 ALPN/HTTP2 h2, http/1.1 (offered)

 Testing cipher categories 

 NULL ciphers (no encryption)                  not offered (OK)
 Anonymous NULL Ciphers (no authentication)    not offered (OK)
 Export ciphers (w/o ADH+NULL)                 not offered (OK)
 LOW: 64 Bit + DES, RC[2,4] (w/o export)       not offered (OK)
 Triple DES Ciphers / IDEA                     offered (NOT ok)
 Obsolete: SEED + 128+256 Bit CBC cipher       offered
 Strong encryption (AEAD ciphers)              offered (OK)
```
Test was performed usingt the most recent version of testssl.sh, see [https://github.com/drwetter/testssl.sh
](https://github.com/drwetter/testssl.sh
)

As we can see, **SSLv3** and **TripleDES** is offered. I would like to remove such old protocols (ideally, even TLSv1 and TLSv1.1) and insecure cipher suites. Unfortunately,  I was not able to find any hints in the docs. 

Is there a possibility to define protocols and cipher suites via `.rr.yaml` or any other configuration option?

**Comment by wolfy-j** [comment]
Most likely yes, RR is based on net/http and it offers are variety of config options, most of them are simply not exposed.

see https://github.com/spiral/roadrunner/blob/master/service/http/service.go#L141

**Comment by bognerf** [comment]
Well, I can't help implementing this, but I gladly would like to offer my help in testing and verifying whenever you have a (Linux) binary ready.

I would imagine that RR should take allowed protocols (TLSv1.2, _TLSv1.3 if possible_) as well as desired cipher suites. A good starting point to grasp which values make sense may be https://ssl-config.mozilla.org/

So, if I can be of service, drop me a line.

**Comment by wolfy-j** [comment]
The minimum version has been bumped to TLS 1.2, also `Strict-Transport-Security` has been added. I don't want to give a config option yet, as older ciphers considered non-secure anymore.

**Comment by wolfy-j** [comment]
See 1.5.3
