### ISSUE TITLE
Symfony Debug bar: Wrong request processing time

### ISSUE THREAD

**Issue by xepozz** [spiral/roadrunner#215]
I started RR. 
I wait some minutes and do request.

![DeepinScreenshot_выберите-область_20191208141146](https://user-images.githubusercontent.com/6815714/70388576-dbcab200-19c4-11ea-8a61-db04722ce0e6.png)

**Comment by wolfy-j** [comment]
I think the Symfony Debug bar relies on some SERVER value. Not really RR bug but we can set the header if needed.

**Comment by xepozz** [comment]
About half of year ago I was tested Yii2+RoadRunner and has the same problem

**Comment by wolfy-j** [comment]
Because this frameworks was build for dying model, so their debut bars rely on script start time which is not relevant for long running apps.

**Comment by wolfy-j** [comment]
Did you get the answer from @stof ? Can i close this issue now?

**Comment by xepozz** [comment]
Yes, sure.
There is my temporary solution:
```php
class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    public function boot()
    {
        $this->startTime = microtime(true);
        parent::boot();
    }

   /// ...
}
```
