### ISSUE TITLE
Does Roadrunner use multiple threads?

### ISSUE THREAD

**Issue by sikhlana** [spiral/roadrunner#216]
I was just curious if Roadrunner handles all the HTTP requests in a single thread or each request is handled on a different thread?

**Comment by wolfy-j** [comment]
Yes, each worker is an isolated process with its own thread.

**Comment by sikhlana** [comment]
@wolfy-j That I am aware of. I am asking about the main process that passes the HTTP requests to the workers.

**Comment by wolfy-j** [comment]
Yes, it workers over multiple threads.

**Comment by sikhlana** [comment]
Got it. Thanks for the info!
