### ISSUE TITLE
RR binary in Docker

### ISSUE THREAD

**Issue by tarampampam** [spiral/roadrunner#218]
Currently for docker images building that contains RR binary I prefer to use:

```dockerfile
# Github: <https://github.com/512k/roadrunner-docker>
FROM 512k/roadrunner:1.4.6 AS roadrunner

FROM php:7.3.7-alpine

COPY --from=roadrunner /usr/bin/rr /usr/bin/rr

RUN ...
```

It works, but maybe we can create `Dockerfile` in this repository and setup image building _(with RR binary)_ using `hub.docker.com`? If this is possible - I will create an PR

**Comment by tarampampam** [comment]
PR with required changes was made. Ping @spiralscout

**Comment by Reallife** [comment]
@tarampampam @spiralscout Yep, it would be usefull.
