### ISSUE TITLE
ERRO[0000] [metrics]: .... bind: address already in use

### ISSUE THREAD

**Issue by alexey-tester** [spiral/roadrunner#220]
Hello!

When I restart RoadRunner daemon it can not bind to the same port it was opened and returns errors like ERRO[0000] [metrics]: .... bind: address already in use

If i check thoses ports it says
tcp        TIME_WAIT   -

I googled the issues and looks like there's a issue with go lang when it does not reuse ports

https://github.com/nordicdyno/golang-tcp-port-reuse

Tested on linux \ ubuntu

Thank you.

**Comment by wolfy-j** [comment]
Yeah, similar issues are causing some tests to fail periodically. I'm not seeing quick way to fix it yet.
