### ISSUE TITLE
support gzip compression?

### ISSUE THREAD

**Issue by wppd** [spiral/roadrunner#222]
hi, 
I wonder if roadrunner supports gzip compression? conduct a "gzip" search in the reposiotry but no luck.

**Comment by wolfy-j** [comment]
Currently, it does not support it, but it can be achieved using simple http middleware. Like https://github.com/nytimes/gziphandler

**Comment by wolfy-j** [comment]
We can add it as default implementation if someone will send us a PR.

**Comment by wolfy-j** [comment]
Merged, I'll polish the test and add it to the next release.

**Comment by wppd** [comment]
thanks man
