### ISSUE TITLE
Missing $_SERVER['REQUEST_METHOD'], breaks Symfony routes

### ISSUE THREAD

**Issue by codysnider** [spiral/roadrunner#226]
The Symfony PSR-7 bridge requires that `$_SERVER['REQUEST_METHOD']` has the request method (e.g. POST) present to properly match a route when two routes have the same path but different http methods/verbs.

**Comment by codysnider** [comment]
Adding this to the configureServer method of PSR7Client would take care of the Symfony requirements, but it throws out `invalid data found in the buffer`:

```
$server['REQUEST_METHOD'] = $ctx['method'];
```

**Comment by wolfy-j** [comment]
`invalid data found in the buffer` is most likely caused by the error in the Symfony app, it usually caused by error or echo sent to STDOUT. Try switching to UNIX or TCP relay to debug it. I'm fine adding (or accepting PR) to fix it as far as it is not root cause of issue with Symfony.

**Comment by codysnider** [comment]
PR submitted. Tested both with and without and this covers the creation of a `\Symfony\Component\HttpFoundation\Request` for use with the standalone annotation-based router. Otherwise, routes restricted to methods that aren't GET are not matched.

Happy holidays! Let me know if you need anything else on this. For the time being, I'm pointing my composer installation to my fork. Looking forward to pointing back to the main package. :-)

**Comment by wolfy-j** [comment]
Nope, all good! Thank you for your PR. Can't guarantee quick release due to the holidays.

**Comment by codysnider** [comment]
Understood, no rush. Best get to bed, friend. Santa is on the way!
