### ISSUE TITLE
any configuration key to disable logging

### ISSUE THREAD

**Issue by irLinja** [spiral/roadrunner#231]
We are running rr in our k8s cluster and since the INFO log is active, apps generate a useless massive amount of log.
is there any configuration key or cli option to disable the log or maybe filter it to only errors?

**Comment by wolfy-j** [comment]
Do not set “-d” flag.

**Comment by irLinja** [comment]
Seems there is no documents on what actually `-d` do.
also I found that `-d` is present on all examples either in the [Wiki](https://roadrunner.dev/docs/intro-config) or in [project Readme file](https://github.com/spiral/roadrunner#run).

is it going to change anything other than logging behavior?

**Comment by wolfy-j** [comment]
It’s just about exposing extra logs. The description is located in binary itself (-h). It’s safe to turn it off.
