### ISSUE TITLE
[RFC] Make possible for server to listen unix socket as well

### ISSUE THREAD

**Issue by luza** [spiral/roadrunner#234]
Currently, the only way to run RR is to listen regular ports 80, 443 for accepting requests. I would like to have an option to listen unix socket as well. This is useful for cases when RR is set up for running behind an edge nginx.

If community accepts such an initiative, I would be able to prepare a PR.

**Comment by wolfy-j** [comment]
No objections on me, check utils. We already have some base code for setting connection up.

**Comment by 48d90782** [comment]
@luza Hey :) I want to clarify a little bit your request. At the moment you can listen unix sockets via FastCGI option in config. You can replace `TCP` in the sample with `unix://rr.sock`. Is that what you need?
 ``` # HTTP service provides FastCGI as frontend
  fcgi:
    # FastCGI connection DSN. Supported TCP and Unix sockets.
    address: unix://rr.sock
```

**Comment by luza** [comment]
Yes, FastCGI is an option. Already this ticket created, I realised that there is no reason why fcgi socket can't fit my needs.

**Comment by 48d90782** [comment]
@luza Great. Thanks
