### ISSUE TITLE
Fix typo in a link to docs with Symfony integration

### ISSUE THREAD

**Issue by scapital** [spiral/roadrunner#236]
As GitHub does not support PR to Wiki, I leave it here.

Link at [the page](https://github.com/spiral/roadrunner/wiki/Symfony-Framework),
have to be followed 
to https://roadrunner.dev/docs/integration-symfony
instead of https://roadrunner.dev/docs/integrations-symfony

**Comment by wolfy-j** [comment]
Hi, you can click edit this page at top of every article on the website.

**Comment by scapital** [comment]
Only maintainers have permission to do that.

**Comment by wolfy-j** [comment]
We accept PR via forks.

**Comment by scapital** [comment]
Wiki does not support fork.
If there was a way to change the wiki page, I would to do that.

You can unselect "Restrict edits to collaborators only", so, community would have ability to change pages.
https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by wolfy-j** [comment]
Oh yeah, I forgot we still have the Wiki, sorry about that. I fixed the typos. 

FYI, all of the online documentation is driven by this repository: 
https://github.com/spiral/roadrunner-docs

You can create PRs to it and the changes will be delivered to the website.
