### ISSUE TITLE
How to schedule a task?

### ISSUE THREAD

**Issue by persevereVon** [spiral/roadrunner#237]
Recently, I was working on a project to migrate my laravel project to roadrunner. During the migration process, I found a problem, how do I run the `php artisan schedule:run` command on a regular basis, which was previously handled by crond.
Thank you.

**Comment by wolfy-j** [comment]
The Console part of your application will work as it was before, you can keep invoking this command via crontab.

**Comment by persevereVon** [comment]
Ok, I'm wondering if I could not use cron, I wanted to keep my docker image as small as possible.

**Comment by wolfy-j** [comment]
On a later date, we will build cron like a module (create Issue if you interested in adding it sooner), for now, you can use default cron.

**Comment by rauanmayemir** [comment]
There are already two issues including this one: https://github.com/spiral/framework/issues/212

I wonder what would be the proper place to add the scheduler. It has to be a semaphore-like feature to account for multi-instance setups and `spiral/jobs` also needed a coordinator.

RR feels like an appropriate place for a 'source of config' kind of entity. (I mean framework could have cron-like schedule facilities, but RR is the one that has to run it)

**Comment by persevereVon** [comment]
A cron module is a good solution, I try to write it first. After all, I'm a newbie to roadrunner. Thank you @wolfy-j

**Comment by wolfy-j** [comment]
Well, we decide not to do crons. We are going to bring the full-blown workflow engine to roadrunner. See Temporal.io. We will make it portable down the road.

**Comment by butschster** [comment]
Hi @dzvon !

I need someone to test https://github.com/spiral-packages/scheduler package
