### ISSUE TITLE
Dead link to Docker Hub in README.md

### ISSUE THREAD

**Issue by Veratyr** [spiral/roadrunner#239]
In the "[installation](https://github.com/spiral/roadrunner#installation)" section in README.md there is a paragraph with dead link and with the mention of container which currently does not exist on Docker Hub:

> For getting roadrunner binary file you can use our docker image: `spiral/roadrunner:X.X.X` (more information about image and tags can be found [here](https://hub.docker.com/r/spiral/roadrunner/))

**Comment by wolfy-j** [comment]
It should be pushed automatically on next build.

**Comment by tarampampam** [comment]
@Veratyr Previos versions in docker available here: https://github.com/512k/roadrunner-docker

**Comment by tarampampam** [comment]
@wolfy-j Something goes wrong:
![image](https://user-images.githubusercontent.com/7326800/74229087-7dcb8b00-4ce3-11ea-954e-b9b1a9660e87.png)

**Comment by wolfy-j** [comment]
Yeah, we are going to check it. @48d90782

**Comment by tarampampam** [comment]
Any news?

**Comment by 48d90782** [comment]
Not yet. I'll dig into that problem, but a little bit later. I'll keep you posted :)

**Comment by wolfy-j** [comment]
Fixed!

**Comment by 48d90782** [comment]
@tarampampam https://hub.docker.com/r/spiralscout/roadrunner/

**Comment by tarampampam** [comment]
Hell yeah! Great!
