### ISSUE TITLE
Reorganize github labels

### ISSUE THREAD

**Issue by 48d90782** [spiral/roadrunner#244]
We need to have clean and understandable labels.
Samples:
1. https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63
2. https://docs.saltstack.com/en/latest/topics/development/labels.html

**Comment by wolfy-j** [comment]
approved

**Comment by 48d90782** [comment]
@wolfy-j Done
https://github.com/spiral/roadrunner/labels

**Comment by wolfy-j** [comment]
Perfect!
