### ISSUE TITLE
Move symfony/console dependency to require-dev

### ISSUE THREAD

**Issue by dkarlovi** [spiral/roadrunner#269]
Since the `vendor/bin/rr` command (built with Console) is primarily for fetching the binary and to init config, it doesn't make sense to me to have it be a production dependency, it should really be dev-only (it assumes your deployment already has the binary and the config file).

As soon as you have the Golang binary, you no longer need the `symfony/console` (AFAIK?). This also means the change I just did in #268 should move to `require-dev` too.

**Comment by wolfy-j** [comment]
Agreed.

**Comment by dkarlovi** [comment]
Note, this was fixed in #268 but then reverted since Composer will not enforce / install deps from `require-dev`.
