### ISSUE TITLE
Create environment for benchmark testing

### ISSUE THREAD

**Issue by 48d90782** [spiral/roadrunner#286]
We need to have a benchmark testing env in which we could test every commit on performance changes.

**Comment by wolfy-j** [comment]
![Screenshot_43](https://user-images.githubusercontent.com/796136/77349987-e8dd9800-6d4c-11ea-8ea9-c66060a54a09.png)

**Comment by 48d90782** [comment]
@wolfy-j Done via internal server for benchmarking
