### ISSUE TITLE
Wrong values for $_SERVER['REQUEST_TIME'] and $_SERVER['REQUEST_TIME_FLOAT']

### ISSUE THREAD

**Issue by lcobucci** [spiral/roadrunner#29]
Every request has the same value for `$_SERVER['REQUEST_TIME']` (the timestamp of when the `rr` process started). `$_SERVER['REQUEST_TIME_FLOAT']` is similar but the only for the seconds part, the milliseconds is always changing.

Some middleware rely on that value and will misbehave due to the wrong value, e.g.:  https://github.com/middlewares/response-time/blob/0eb140f53365bcda5a88449fda29b818aa95c64a/src/ResponseTime.php#L18-L25

**Comment by wolfy-j** [comment]
Solved as part of v1.1.0 update.
