### ISSUE TITLE
Loading worker after request in development mode

### ISSUE THREAD

**Issue by ramainen** [spiral/roadrunner#299]
Actually this is not a platform issue and I understand why it happens. But there is still some behaviour thats looks not normal.

When I develop app, I use next configuration.

```
pool:
      numWorkers: 1
      maxJobs:  1
```

So, lets look at next scenario: I change code X to code Y and press F5 (command+R) on browser.

1. worker ran with X code
2. I press F5, see X in browser
3. worker reloads and ran with X code
4. I change code to Y
5. I press F5
6. I see X in browser (because worker loaded before code changed)
7. worker reloads and ran with Y code
8. I press F5
9. I see Y in browser

So, my usual workflow is save file - F5 - F5 (double button push). This is OK when I test something simple, but not good for heavy calculations (F5, wait 30 seconds, F5) or danger code (delete correct files for example).

So, I suggest to add new yml option (like `developer_mode: true`) thats force loading worker (`php worker.php`) actually after request is coming (in Golang part), and after PHP started, continue to send request to PHP part. This makes running slower (because creating objects and other PHP work will be started not in background but after pressing F5) but makes working more predictable.

Also this way introduce some side-effect feature: possibility of printing in browser error report if PHP fails with syntax error (for example in first line of worker.php, there is no way to catch this error in this way).

Or, maybe you are already have working workaround. 

P.S. I know about reload after 1s after file changes feature, but I must wait 1 second before doing something alt+tab and F5, plus this is still not predictable way.

**Comment by ramainen** [comment]
I created working fix (works for me).

https://github.com/ramainen/roadrunner/commit/1187f6a5d396b6c584a3d7abee0ca3ffebb1510b

Still not error handling (so this is not actual good for real pull request), but works.

Option must named as developerMode, in http.workers section.

**Comment by wolfy-j** [comment]
That's not a proper way to do that sadly. @48d90782 let's discuss.

**Comment by ramainen** [comment]
Yes, there is issues that I can see:

- No golang errors handling (easiest part).
- No submitting errors to response (free bonus).
- Still unnecessary reloading workers (once after handling, once after getting request). But this can be fixed by setting `maxJobs` to 0 actually.

**Comment by wolfy-j** [comment]
I think we have to approach it at StaticPool level implementation. It would work for all the drivers then.

**Comment by 48d90782** [comment]
done by #376 
Will be in RR 2.0
