### ISSUE TITLE
[Question] Is there a constant RR_BINARY like PHP_BINARY ?

### ISSUE THREAD

**Issue by ncou** [spiral/roadrunner#300]
Hi,

Just a silly question is there a way to get the roadrunner binary path ? using something like the existing PHP_BINARY constant for example ?

I know i can check if the "rr" or "rr.exe" file is present at the root dir, but i am looking for a more clean solution (in case the "--location" param is used in the "get-binary" command).

Keep up the good work.

**Comment by wolfy-j** [comment]
Doable. May I ask for the use case? In an ideal world, the PHP should know nothing about RR binary and relay on RR_RPC address to communicate with the parent server.

**Comment by ncou** [comment]
In our use case it's to have the possibility to start the RR server using a console Command (and i don't want the user to manualy pass the binary path). I used the reference to PHP_BINARY because you can fire the build-in server using someting like `exec(PHP_BINARY . '-S')`. So I was searching for a similar way.

**Comment by wolfy-j** [comment]
Unfortunately, it's not possible to define the ENV variable outside of RR binary process tree. Try to use an OS-specific ENV variable.

**Comment by 48d90782** [comment]
Say in truth it's possible, but not necessary :) @ncou I agree with @wolfy-j, If that solves your problem, you can define ENV variable with `path to RR` and download `RR` into that path (and then use that ENV var). Or you can provide a more relevant sample why do people need this :)

**Comment by ncou** [comment]
Thank you for your feedbacks, I will try to do a workaround. Have a good day.
