### ISSUE TITLE
unable to connect to worker: invalid data found in the buffer (possible echo)

### ISSUE THREAD

**Issue by Umid-Berdiev** [spiral/roadrunner#306]
Hello there!

I've installed roadrunner in two computer in the same way as you instructed in https://packagist.org/packages/spiral/roadrunner. But it works in one of my comps. in another computer i've got only the same error:
Error: [http]: unable to connect to worker: invalid data found in the buffer (possible echo): exit status 1

Any issues, please

**Comment by wolfy-j** [comment]
Hi, make sure to read about troubleshooting here: https://roadrunner.dev/docs/php-worker

**Comment by Umid-Berdiev** [comment]
> 
> 
> Hi, make sure to read about troubleshooting here: https://roadrunner.dev/docs/php-worker

Yes, I've checked this troubleshoot too, worker behaves as expected

**Comment by wolfy-j** [comment]
Do you invoke php directly or via bat/shell file on other machine? Do you have this error immediately after start or after request?

**Comment by 48d90782** [comment]
@Umid-Berdiev What OS do you use?

**Comment by Umid-Berdiev** [comment]
> 
> 
> @Umid-Berdiev What OS do you use?

Windows

**Comment by Umid-Berdiev** [comment]
> 
> 
> Do you invoke php directly or via bat/shell file on other machine? Do you have this error immediately after start or after request?

I've invoked $ php worker.php in windows command-prompt and in the phpstorm terminal and when I press enter btn there coming error logs

**Comment by Umid-Berdiev** [comment]
> 
> 
> Do you invoke php directly or via bat/shell file on other machine? Do you have this error immediately after start or after request?

![image](https://user-images.githubusercontent.com/25151053/79683274-68726000-8242-11ea-8552-6f9054242d76.png)

**Comment by 48d90782** [comment]
@Umid-Berdiev Sorry, we can't verify the problem you are met. Feel free to re-open the ticket and provide more details in case if the problem still exists.
