### ISSUE TITLE
[BUG] Hitting  superfluous response.WriteHeader  during stress test

### ISSUE THREAD

**Issue by andrei-dascalu** [spiral/roadrunner#333]
I tried this code:

Symfony 5 out of the box (then add roadrunner integration) or a simple php router (I can provide access to my repo). Running stress test with autocannon

`autocannon -c 100 -d 40 -p 10 -t 120 http://127.0.0.1:8080`

Seems to be in line with issue #301 

I expected to see this happen:
no logs

Instead, this happened:
```
2020/05/28 16:32:33 http: superfluous response.WriteHeader call from github.com/spiral/roadrunner/service/http.(*Handler).handleError (handler.go:135)
2020/05/28 16:32:33 http: superfluous response.WriteHeader call from github.com/spiral/roadrunner/service/http.(*Handler).handleError (handler.go:135)
```

The version of RR used: 1.8.1

**Comment by 48d90782** [comment]
@andrei-dascalu Thanks for the report. Seems, that I need to deeper investigate this bug :)
Linked: #301

**Comment by andrei-dascalu** [comment]
Hi,

I've made some other tests using RR and might be useful info:
- tried a basic setup with Ubiquity framework (using their integration, though their README is outdated, their CLI tool can do `biquity serve -t=roadrunner` and will setup some sane defaults). They don't seem to setup a relay via socket and using the same stress test I got a much weaker general result, but no such errors across a dozen or so tests.
- Symfony (and my setup) use sockets and got to a much higher request count, always getting some errors)

**Comment by 48d90782** [comment]
@andrei-dascalu Thank you for the information. In high overview I know the root cause of such errors, just need to allocate some time to dig into :)
