### ISSUE TITLE
[Question]: how to add extension, spiral/jobs for example, to roadrunner?

### ISSUE THREAD

**Issue by wppd** [spiral/roadrunner#340]
Didn't find the info in the doc.
If I want to use spiral/jobs extension with roadrunner, do I need to edit cmd/rr/main.go, add spiral/jobs service, and rebuild roadrunner?
thanks.

**Comment by 48d90782** [comment]
@wppd `Jobs` module already contains RR, so, it is a self-sustained module. If you need only Jobs, you can safely use `spiral/jobs`. If you need to add other modules, you can add needed modules to the `spiral/jobs`. 
You can see here a sample of all modules in one place: [Repo](https://github.com/spiral/framework/blob/master/main.go)
Note: we are working on the better module system for the RR 2.0

**Comment by wolfy-j** [comment]
You can also spiral binaries which already include jobs: https://github.com/spiral/framework/releases

**Comment by 48d90782** [comment]
@wppd Feel free to close the ticket if you have no other questions.
