### ISSUE TITLE
[Question] Services timing out

### ISSUE THREAD

**Issue by l0gicgate** [spiral/roadrunner#344]
So after our app runs in production for about 8 hours we start getting timeouts from MySQL and Redis. 

“MySQL server has gone away” but we are still able to connect to the service manually which indicates that the worker’s connection is gettint closed/reset. 

Could this be due to workers staying bootstrapped for too long? What is the default amount of time a worker will stay bootstrapped if you don’t set `allocateTimeout` in the configuration?

Thank you

**Comment by 48d90782** [comment]
@l0gicgate The default timeout for allocateTimeout is one minute.

**Comment by 48d90782** [comment]
>Could this be due to workers staying bootstrapped for too long?
Try to set timeout to some big number, for example, 10000days. In case the issue still presents, the problem is somewhere else.

**Comment by wolfy-j** [comment]
The question and answer to it are way more complex than "what TTL to set", so let me explain:

1) Some databases will close the connection after some IDLE time
2) Some infrastructures MIGHT close connection of firewall level after some IDLE time or some MAGIC time

If you experiencing connection drop after your application is idle for long - set max Idle time option for workers, you can set it as low as 10 minutes as it won't be triggered under load.

However, remember, connections WILL be dropped periodically if you want it or not, it's just too many variables. The only proper way to ensure it - implement proper DBAL which will reconnect for you, in that case, you can remove the TTL constrains.

Some older frameworks do not worry about reconnection and socket error detection (why bother) but you can take a look at our DBAL which handles that: 
https://github.com/spiral/database

If you need to work with legacy code, check this part responsible for error detection (yes, it's a lot of heuristics):
https://github.com/spiral/database/blob/771cdb141b5ff299c0243ae3009d17ec0c2e0bc1/src/Driver/Driver.php#L477
https://github.com/spiral/database/blob/master/src/Driver/MySQL/MySQLDriver.php#L66

**Comment by l0gicgate** [comment]
@wolfy-j thank you for the explanation. Currently we’re using a mix of PDO and Doctrine ad DBAL. If I set the `allocateTimeout` to be `60` that means the workers will only be bootstrapped for 60 seconds correct? That means it would never reach any db idle connection timeouts right? I was reading the default max connection lifetime is like 8 hours for MySQL default settings.. this seems like a really weird issue we’re encountering.

**Comment by wolfy-j** [comment]
No, `allocateTimeout` will control the timeout to the browser when the system is busy. 

You are looking for: https://roadrunner.dev/docs/php-limit

**Comment by l0gicgate** [comment]
So `idleTtl` would be the setting? Sorry if I'm misunderstanding.

**Comment by wolfy-j** [comment]
Yes

**Comment by l0gicgate** [comment]
Awesome, thank you @wolfy-j !

**Comment by l0gicgate** [comment]
The issue was resolve using sensible `idleTtl` and `TTL`!
