### ISSUE TITLE
[Question] Best way to handle PHP sessions

### ISSUE THREAD

**Issue by ramainen** [spiral/roadrunner#346]
Not actual issue, but advice needed.

I write PHP application, and I want to use PHP sessions. I can write it, and modify roadrunner binary, this is not a problem.

PHP sessions in "usual" PHP+apache are blockable, when script one still worked, second tab in this browser will be wait for response, only one PHP program with same session_id can work in same time.

What is correct way to do this in Roadrunner?

First way: check lock file/database record in PHP part, and make simple while(true). This is not best way, because if I have 8 workers, one slow worker, making long computations can just kill server by doing 7 requests. (For example user makes import, and refresh page)

Second way: somewhere in handler.go write and read current session_id from cookie to golang map, and make pause based on golang channels (when another worker done job, unlock session).

Third way: do not use session blocking at all, use database transactions (I am not sure, may be this is production and modern way?)

**Comment by wolfy-j** [comment]
The answer we found - do not open session unless you absolutely need it, and close it right after you don't need it. In many cases using sessions can be avoided, the most horrible example - using sessions for CSRF protection.

We use default PHP session wrapper to make it work - https://github.com/spiral/session
