### ISSUE TITLE
[Question] Can I run roadrunner with php executable via tcp socket?  

### ISSUE THREAD

**Issue by saalexeev** [spiral/roadrunner#347]
Hello, I want to split project into 2 docker containers: php executable, which accessible via tcp://:9000 and roadrunner server. But I can't make roadrunner execute php via tcp socket like nginx. Is it possible? I tried to link containers by network, but roadrunner says: "exec: "php": executable file not found in $PATH"

**Comment by 48d90782** [comment]
Hello @saalexeev. It is not possible at the moment as far as I know. You can try to create volume in the docker with `php` script and make it available for the second container. But I am not sure, if that possible. Also, you can create a RFC and describe feature, that you want to see in the future versions of RR.

**Comment by wolfy-j** [comment]
It is not possible since RR can not longer manage PHP process in remote container.
