### ISSUE TITLE
Example debugging configuration

### ISSUE THREAD

**Issue by evonicgu** [spiral/roadrunner#348]
I have a vagrant VM with php7.4-cli and RoadRunner installed. My /etc/php/7.4/cli/conf.d/20-xdebug.ini looks like:
```
zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_host=10.0.2.2
# I chose 9001 port, because 9000 is used for debugging locally
xdebug.remote_port=9001
xdebug.remote_connect_back=0
xdebug.remote_autostart=1
```

When i start the server with `rr serve -d -v` command and refresh the page nothing happens. Breakpoints are set of course and PHPStorm is tuned right (it listens for 9001 port, accepts external connections and max simultaneous connection amount is set to 20). Where am I wrong?

**Comment by wolfy-j** [comment]
This is the approach we use https://spiral.dev/docs/debug-xdebug

**Comment by evonicgu** [comment]
Tried it and it worked. Thanks a lot.
