### ISSUE TITLE
[FEATURE REQUEST] PCI DSS compliant TLS configuration

### ISSUE THREAD

**Issue by antonydevanchi** [spiral/roadrunner#352]
Roadrunner run with support a few legacy TLS ciphers and not compliant PCI DSS requirements now. 

Changes required to start compliant PCI DSS standard looks like a very simple and «why not?». As bonus Roadrunner will can add «PCI DSS compliant» in marketing things :)

I can't deep dive into Roadrunner code base and request some help from mainteners (@48d90782 ?).

Reference: 

https://www.immuniweb.com/ssl/?id=I4pDyQOr

```
TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA Non-compliant with PCI DSS requirements
TLS_RSA_WITH_3DES_EDE_CBC_SHA Non-compliant with PCI DSS requirements
```

Required changes in `service/metrics/service.go` is `TLSConfig`:

```
s.http = &http.Server{
		Addr:              s.cfg.Address,
		Handler:           promhttp.HandlerFor(s.registry, promhttp.HandlerOpts{}),
		IdleTimeout:       time.Hour * 24,
		ReadTimeout:       time.Minute * 60,
		MaxHeaderBytes:    maxHeaderSize,
		ReadHeaderTimeout: time.Minute * 60,
		WriteTimeout:      time.Minute * 60,
		TLSConfig: &tls.Config{
			CurvePreferences: []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
			CipherSuites: []uint16{
				// TLSv1.3
				tls.TLS_AES_128_GCM_SHA256,
				tls.TLS_CHACHA20_POLY1305_SHA256,
				tls.TLS_AES_256_GCM_SHA384,
				// TLSv1.2
				tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
				tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
				tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
				tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
				tls.TLS_RSA_WITH_AES_128_GCM_SHA256,
				tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
				tls.TLS_RSA_WITH_AES_128_CBC_SHA,
				tls.TLS_RSA_WITH_AES_256_CBC_SHA,
			},
			MinVersion:               tls.VersionTLS12,
			PreferServerCipherSuites: true,
		},
	}
```

I'm not sure that it will serve simple HTTP requests properly.

Please, give me any feedback.

**Comment by 48d90782** [comment]
@antonydevanchi Thanks for the request. I'll take a look and test PCI DSS support.

**Comment by 48d90782** [comment]
@antonydevanchi Also, could you please provide open reference? You need to be registered by provided link.

**Comment by antonydevanchi** [comment]
@48d90782 definitely you not need membership for viewing results, but you can be misled by aggressive pop-ups. I check link from my first post with cell phone / gsm carrier and with private browsing mode on laptop and all things available without any additional credentionals.

Please, try now?

**Comment by 48d90782** [comment]
> @48d90782 definitely you not need membership for viewing results, but you can be misled by aggressive pop-ups. I check link from my first post with cell phone / gsm carrier and with private browsing mode on laptop and all things available without any additional credentionals.
> 
> Please, try now?
> 
> P.S. Also you don't need «Download report». Just scroll down and get profit.

You are right :) I guess that I clicked by some pop-up :)

**Comment by 48d90782** [comment]
@antonydevanchi Could you please try to deploy https://github.com/spiral/roadrunner/pull/353 ?

**Comment by antonydevanchi** [comment]
@48d90782 [in live](https://psknv.ru).

New tests report:
https://www.immuniweb.com/ssl/?id=I4pDyQOr

**Comment by 48d90782** [comment]
@antonydevanchi Nice :)

**Comment by 48d90782** [comment]
@antonydevanchi Ok, it will be in the master and later in the 1.8.3 version. Thanks )
