### ISSUE TITLE
[QUESTION] Is there any way to handle request to a certain subdirectory?

### ISSUE THREAD

**Issue by evonicgu** [spiral/roadrunner#354]
I want to hold my php api and react application on one web domain. Roadrunner accepts all requests on it's port (80). But I want all requests to be handled by react, and only requests to /api subdirectory to be handled by workers. Is there any way to implement it?

**Comment by 48d90782** [comment]
@evonicgu You can bind RR to the different port or redirect `/api` requests to the RR handler from your app.

**Comment by wolfy-j** [comment]
Use ingress server for such purposes. For example Nginx as reverse proxy.

**Comment by evonicgu** [comment]
Ok, thanks, closing issue.
