### ISSUE TITLE
[BUG, RR1] "max allowed memory reached" should not be reported as ERROR

### ISSUE THREAD

**Issue by hugochinchilla** [spiral/roadrunner#359]
When maxMemory is reached a line is written to the logs as ERROR, as the maxMemory is a soft limit it should be treated as an INFO or a NOTICE.

**Comment by 48d90782** [comment]
@hugochinchilla I am going to agree with you. Would you mind to make a PR?

**Comment by hugochinchilla** [comment]
@48d90782 I'm sorry for the late reply, I'm not familiar with golang but this did not prevent me from taking a look at the source code to see if it was possible with my limited knlowledge, sadly I don't know how to do it.

**Comment by 48d90782** [comment]
> @48d90782 I'm sorry for the late reply, I'm not familiar with golang but this did not prevent me from taking a look at the source code to see if it was possible with my limited knlowledge, sadly I don't know how to do it.

Got you 😃 Likely we will update RR 2.0 first and then I return back to the 1.x version. Thanks for the proposal 😃
