### ISSUE TITLE
Config CLI flag seems to be ignored

### ISSUE THREAD

**Issue by andrewmatthews** [spiral/roadrunner#36]
I am trying to set the config file to a different location to where the roadrunner binary is located. When I add the config CLI flag, it seems to be ignored.

When I run:
`vagrant@locahost:/$ /usr/bin/rr --config=/etc/roadrunner/.rr.yaml serve`

I get the following output and the server stops:

`WARN[0000] config: Config File ".rr" Not Found in "[/]"`

**Comment by wolfy-j** [comment]
Fixed in 1.2.1, also now it's easier to run multiple rr instances since PHP process path is relative to the config file.
