### ISSUE TITLE
[FEATURE REQUEST] Add ARM build to the releases

### ISSUE THREAD

**Issue by xxxjio** [spiral/roadrunner#367]
I wanna use linux-arm64

**Comment by 48d90782** [comment]
@xiaohao0416 Thanks for the FR. It's totally not a problem to build a golang binary with ARM/ARM64 support, but I have to test RR on that platform to make sure, that everything goes fine.

**Comment by 48d90782** [comment]
Done, now you can use docker container with the linux/arm64

**Comment by aleksandrmetik** [comment]
(Internal ticket) INFR-1869 "Create a VM with AArch64/ARM64 image" for auto-tests has been added to the scope.
