### ISSUE TITLE
[FEATURE REQUEST] Add possibility to use dynamic modules like in nginx, apache, php, etc.

### ISSUE THREAD

**Issue by bjuri** [spiral/roadrunner#369]
The main idea of the request is to have CORE of the roadrunner with minimal necessary functionality, e.g. http module, or probably more general (logging, monitoring, workers scheduling, ...) and have dynamic pluggable modules for the main roadrunner role.

As result we can have robust core with officially supported main-modules:
1. roadrunner binary with: logging, monitoring, scheduling, ...
2. pluggable part: http.so, grpc.so, jobs.so, ...

**How to plug those modules**
1. Section may have naming like: `load-module: http.so`
2. All module related configs will be parsed on module side

**Comment by 48d90782** [comment]
Duplicate: #474
