### ISSUE TITLE
Too many opened tcp connections on low load

### ISSUE THREAD

**Issue by evonicgu** [spiral/roadrunner#370]
Recently I tried to do some stress testing stuff with my application (works with RR). I used artillery (https://artillery.io) to do this. When I firstly run the tests for 60 seconds with 10 requests/sec everything was fine, but many tcp connections were opened by RR process. On a longer distance (3 minutes) errors start to happen.

```
2020/10/15 11:43:45 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 10ms
2020/10/15 11:43:45 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 20ms
2020/10/15 11:43:45 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 40ms
2020/10/15 11:43:45 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 80ms
2020/10/15 11:43:45 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 160ms
2020/10/15 11:43:46 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 320ms
2020/10/15 11:43:46 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 640ms
2020/10/15 11:43:47 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2020/10/15 11:43:48 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2020/10/15 11:43:49 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2020/10/15 11:43:50 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2020/10/15 11:43:51 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2020/10/15 11:43:52 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2020/10/15 11:43:53 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2020/10/15 11:43:54 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2020/10/15 11:43:55 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2020/10/15 11:43:56 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2020/10/15 11:43:57 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
2020/10/15 11:43:58 http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s
```

`lsof -a -p $(pidof rr)` shows 30 worker pipes, some other connections and loads of tcp connections like `ubuntu2004.localdomain:http->_gateway:58032`. I've found only a temporary solution - increase opened files limit, but I think this is not the root of the problem. Maybe these connections are not closed immediately after the response and I don't know how to fix that.

**Comment by 48d90782** [comment]
@evonicgu I may guess, that this is expected behavior because such load testing frameworks generate a huge number of TCP connections. Each open TCP connection is a file-descriptor (aka open file, active TCP socket). Also, in the case of a TCP4 listener, we use a few optimizations like `SO_REUSEPORT, TCP_DEFER_ACCEPT, and TCP_FASTOPEN` if acceptable. I may guess, that this tool leaves a connection open until the testing will be finished.
But, thanks for the report, I will double-check this.

**Comment by evonicgu** [comment]
Sorry, I forgot to give some more information. RR is running on Ubuntu VM, and the testing framework makes requests not from that VM, so they are separated, and tcp connection overuse is detected on VM only. Maybe, this is an issue with net/http package you are using.

**Comment by 48d90782** [comment]
We are using the standard `net/tcp` package. I am not very familiar with `artillery` framework, but can you please try `wrk` with, let's say 10 number of connections for the same period of time? `wrk -t1 -c10 -d360s http://127.0.0.1:8080/index.html`

**Comment by evonicgu** [comment]
I've tried `wrk`  making requests from VM, but there are still too many connections errors sometimes. `lsof -a -p $(pirof rr)` shows that there are some connections opened. The connection amount doesn't increase, however I don't think, that it is a good result, because when I set `-c` option to `1000` there are nearly 50 opened tcp connections.

**Comment by evonicgu** [comment]
Also, the performance is bad, despite the only thing the worker was doing is making a response and responding.

**Comment by 48d90782** [comment]
> I've tried `wrk` making requests from VM, but there are still too many connections errors sometimes. `lsof -a -p $(pirof rr)` shows that there are some connections opened. The connection amount doesn't increase, however I don't think, that it is a good result, because when I set `-c` option to `1000` there are nearly 50 opened tcp connections.

Could you please provide a PHP script which you are trying to bench (if possible) and your TCP connections limit? I tried to bench with `-t12 -c1000 -d60s` on default worker (from docs) and everything went fine.

**Comment by 48d90782** [comment]
> Also, the performance is bad, despite the only thing the worker was doing is making a response and responding.

There is no bad or good performance. You have to measure and show the stat 😄

**Comment by evonicgu** [comment]
The script is pretty simple:

```PHP
<?php

declare(strict_types=1);

... (import)

require __DIR__ . '/vendor/autoload.php';

$worker = new Worker(new StreamRelay(STDIN, STDOUT));
$psr7 = new PSR7Client($worker, new ServerRequestFactory(), new StreamFactory());

while ($req = $psr7->acceptRequest()) {
    try {
        $response = new Response();
        $response->getBody()->write('index');
        $response->withHeader('Connection', 'Close');
        $psr7->respond($response);
    } catch (Throwable $e) {
        $psr7->getWorker()->error((string) $e);
    }.
}
```

It's very strange, that your benchmark went fine.

**Comment by evonicgu** [comment]
Let me give you benchmark results with your configuration (`-t12 -c1000 -d60s`).

```
./wrk -t12 -c1000 -d60s http://127.0.0.1:80/
Running 1m test @ http://127.0.0.1:80/
  12 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   219.82ms   81.72ms   1.03s    76.69%
    Req/Sec   364.12    196.83     1.38k    64.22%
  253575 requests in 1.00m, 34.82MB read
Requests/sec:   4219.26
Transfer/sec:    593.33KB
```

**Comment by 48d90782** [comment]
@evonicgu Do you use Ubuntu? Send me please your OS details.

**Comment by evonicgu** [comment]
Yep, I use Ubuntu20.04 installed on a VM powered by Vagrant + Virtualbox. Php version is 8.0 RC1. RR version is 1.8.2.

**Comment by 48d90782** [comment]
@evonicgu Few notes: PHP 8.0RC1 is not supported. RR should be 1.8.3. Also, can you please share your `ulimit` stats with max number of TCP connections?

**Comment by evonicgu** [comment]
Just now I'm going to switch my PHP version to 7.4 and update RR. Here is `ulimit -a` output.

```
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7607
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7607
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by evonicgu** [comment]
Tested that benchmark with PHP7.4 and RR 1.8.3. Nothing changed, there are still loads of opened TCP connections.

**Comment by 48d90782** [comment]
`open files (-n) 1024` I will try to test with `-c 100` and open files limit 1024.

**Comment by evonicgu** [comment]
Do you think, that it is ok, that connections are even opened? I think they should be closed just after the response is sent.

**Comment by 48d90782** [comment]
> I think they should be closed just after the response is sent.

That depends. You are making a request to the application. The application listens on a passive TCP socket. When OS handles the incoming TCP connection it will copy the passive socket, and it becomes an active TCP socket (open file in term of Linux). So, you can have only 1 passive socket (for the port, interface) and in your case (or default case) up to `1024` active sockets (in a very ideal world). The active socket not necessary will be closed right after request. It depends on the headers you send, on the application (early I mentioned our options for the TCP)

**Comment by 48d90782** [comment]
Tested on Ubuntu 20.04 with the worker in docs.
```
❯ wrk -t12 -c1000 -d60s http://127.0.0.1:8080/index.html
Running 1m test @ http://127.0.0.1:8080/index.html
  12 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    33.19ms   11.63ms 148.13ms   85.54%
    Req/Sec     2.49k   284.46     3.47k    66.88%
  1783130 requests in 1.00m, 256.78MB read
Requests/sec:  29682.55
Transfer/sec:      4.27MB
```
```
❯ ulimit -n
1024
```

**Comment by 48d90782** [comment]
@evonicgu You can ask for help with your PHP worker from our PHP programmers and community in our Discord channel.

**Comment by evonicgu** [comment]
So, to have all tcp connections closed immediately after response I have to set `Connection` header to `Close` value?

**Comment by evonicgu** [comment]
That seems to be very strange, because my test with that worker was awful. Does the hardware affect the results?

**Comment by 48d90782** [comment]
> That seems to be very strange, because my test with that worker was awful. Does the hardware affect the results?

For sure )

**Comment by evonicgu** [comment]
So, can you give me some info about your VM (RAM, CPU cores)?

**Comment by evonicgu** [comment]
My VM has 2GB RAM and 2 CPU cores.

**Comment by evonicgu** [comment]
By the way, what is in your `.rr.yaml`?

**Comment by 48d90782** [comment]
> My VM has 2GB RAM and 2 CPU cores.

8 CPU cores, 64 Gb of RAM.

Here is my .rr.yaml
```yaml
http:
  address: 0.0.0.0:8080

  http2:
    enabled: true
    h2c: true
    maxConcurrentStreams: 128

  workers:
    command:  "php psr-worker.php"
    relay:    "pipes"
    user: ""
    pool:
      numWorkers: 10
      maxJobs:  0
      allocateTimeout: 60
      destroyTimeout:  60
```

**Comment by evonicgu** [comment]
That's why you have so amazing results)

**Comment by 48d90782** [comment]
> That's why you have so amazing results)

We are not comparing our hardware here. It's obvious, that VM with limited resources will be slower than non virtualized host OS with better hardware.
To summarize: I could not reproduce your issue nor on VM nor on host OS. Feel free to open a new issue with steps to reproduce.

**Comment by littlexiang** [comment]
try to increase open files (-n) to much larger
every tcp connection entering TIME_WAIT takes fd

**Comment by 2ik** [comment]
same error, because I started RR from **root**
Run from **user** and error has disappeared for me)
