### ISSUE TITLE
[BUG] Systemd keeps starting / stopping rr service endlessly

### ISSUE THREAD

**Issue by AnticDroid** [spiral/roadrunner#381]
I am using builded RR service(go build). It was actively tested for several months and it works fine.
Before that I used SCREEN and switched  to systemd...

According to the system logs systemd keeps starting/stopping RR service endlessly and sometime service becomes unavailable(not every time it appear stopped in logs) , where is no any error on php layer and no other duplicated process. 

Can somebody help me with systemd or drop a hint how to daemonize rr service?

**Environment:**
```
Operating System: Ubuntu 18.04.3 LTS
Kernel: Linux 5.4.0
Architecture: x86-64

go version go1.12.7 linux/amd64
PHP 7.2.24-0ubuntu0.18.04.7
spiral/goridge  v2.4.5
spiral/roadrunner v1.8.4
```
**Endless repetition in system log:**
```
Nov  3 20:05:10 ip-*-*-*-* systemd[26165]: rr-cms-api.service: Service hold-off time over, scheduling restart.
Nov  3 20:05:10 ip-*-*-*-* systemd[26165]: rr-cms-api.service: Scheduled restart job, restart counter is at 813.
Nov  3 20:05:10 ip-*-*-*-* systemd[26165]: Stopped CMS HANDBOOK API.
Nov  3 20:05:10 ip-*-*-*-* systemd[26165]: Started CMS HANDBOOK API.
Nov  3 20:05:10 ip-*-*-*-* cms-handbook-api[16530]: #033[31mERRO#033[0m[0000] [rpc]: listen tcp 127.0.0.1:6003: bind: address already in use
Nov  3 20:05:10 ip-*-*-*-* cms-handbook-api[16530]: #033[1;91mError:#033[0m #033[31m[rpc]: listen tcp 127.0.0.1:6003: bind: address already in use#033[0m
Nov  3 20:05:10 ip-*-*-*-* systemd[26165]: rr-cms-api.service: Main process exited, code=exited, status=1/FAILURE
Nov  3 20:05:10 ip-*-*-*-* systemd[26165]: rr-cms-api.service: Failed with result 'exit-code'.
```

**rr.server systemd unit file** use executable (go build) cms-handbook-api
```
[Unit]
Description=CMS HANDBOOK API

[Service]
Type=simple
ExecStart=/var/services/cms-handbook-api/cms-handbook-api serve -c /var/services/cms-handbook-api/.rr.yaml
Restart=always
RestartSec=30

[Install]
WantedBy=default.target
```

**/var/services/cms-handbook-api/.rr.yaml**
```

rpc:
  enable: true
  listen: tcp://127.0.0.1:6003

http:
  address: :8083
  workers:
    command: "/usr/bin/php /var/services/cms-handbook-api/worker.php"
    pool:
      numWorkers: 4
      maxJobs:  0
      allocateTimeout: 60
      destroyTimeout:  60
limit:
  services:
    http:
      maxMemory: 1000
      TTL: 0
      idleTTL: 0
      execTTL: 600
headers:
  response:
    "Cache-Control": "no-cache"
```

**Comment by 48d90782** [comment]
Hey @AnticDroid, nice to meet you.
1. Go version 1.12 is not supported at the moment. It may work, but the minimum supported version is 1.14. [TIP]
2. `#033[31mERRO#033[0m[0000] [rpc]: listen tcp 127.0.0.1:6003: bind: address already in use` Here is the issue, as you see, try to change port 6003 by some other free port (use `netstat -tulpn | grep LISTEN` to see allocated ports).
3. You are using:
```
Restart=always
RestartSec=30
```
It means, that if the process dies, systemd will be trying to restart `rr` process endlessly  -> `Restart=always`. You can read [link](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=) about the `Restart` option (and other options) and choose one that fits your needs better.
4. You may also append `-d` flag after `serve` to turn on debug mode and see more logs.

**Comment by 48d90782** [comment]
Also, try to find all `cms-handbook-api` processes and kill it before enabling  systemd unit file (`ps aux | grep cms-handbook-api`)

**Comment by AnticDroid** [comment]
Thanks for the help

**Comment by 48d90782** [comment]
> Thanks for the help

You are welcome. Feel free to join our discord channel https://discord.gg/TFeEmCs
