### ISSUE TITLE
[FEATURE REQUEST] Configuration reference

### ISSUE THREAD

**Issue by Radiergummi** [spiral/roadrunner#391]
**Is your feature request related to a problem? Please describe.**  
I'm preparing for a migration from a classic php-fpm+nginx setup in Docker to RR. While I'm pretty confident with optimizing FPM configuration for performance and our workload, I'm not sure how well that transfers to Roadrunner: I have a _feeling_ the FPM thread pool size should match `http.workers.pool.maxWorkers` somehow, but I'm not sure of that.  
The [documentation](https://roadrunner.dev/docs/intro-config) doesn't help too much here: A single, sample config file just isn't enough, really. How many workers are efficient? Is there a default? Can I have an automatic worker amount based on CPUs? Are they load balanced using round robin, or something else? And so on.

**Describe the solution you'd like**  
I'd _really_ like to use RR. The performance premise looks super promising, and I'd gladly simplify my Docker setup to a single application, just as it should be. But to do so, I'll need to migrate carefully and this requires having extensive documentation for every feature and configuration directive available.  
Therefore, I'd like to suggest extending the documentation with individual sections for every option, and improving the [production usage page](https://roadrunner.dev/docs/beep-beep-production) (Currently it's really just a list of caveats with some random tips thrown in between; that should be an actual guide with examples). 

**Describe alternatives you've considered**  
I guess to understand everything about how workers work, I'd need to dive into the Go source and figure it out myself. I'd do that for a hobby project, but I simply can't justify that to my company.

**Comment by 48d90782** [comment]
Hey @Radiergummi, nice to meet you.
> How many workers are efficient?  

It really depends. But the general advice is to have the following number - `cpu_cores * 1.5`. It also depends on the type of the cores (Intel HT or real cores). `cpu_cores * 1.5` is to have some processes prepared to do work (let's say in a hot state like with intel HT technology).
> Is there a default?

Yes, the default is the number of CPU cores (with HT cores).

> Can I have an automatic worker amount based on CPUs?

Yes, see the prev. answer.
> Are they load balanced using round robin, or something else?

No at the moment. At the moment workers number are static and behaves like FIFO.

Thanks for the proposal for the documentation. At the moment all our efforts are dedicated to the RR 2.0, but I'll attach this ticket to the RR 2.0 tracking list here: https://github.com/spiral/roadrunner/issues/368

**Comment by Radiergummi** [comment]
Hi @48d90782! Thank you for the detailed answer, that helps a lot in planning. I'll keep an eye on RR 2.0.

**Comment by wolfy-j** [comment]
We will update the documentation with RR2.0 since a lot of configuration will change (for the better).

But in general, there are no direct correlation between the number of FPM childs and RR workers. RR does not destroy workers between requests which is the core of its performance boosts, so you typically don't need that many workers sitting around (only if you have long IO operations). It's recommened to start with number of cores and then analyze the performance.

**Comment by 48d90782** [comment]
@Radiergummi We have updated our documentation (https://roadrunner.dev/), feel free to open a new ticket if some section contains mistakes or confusing.

**Comment by Radiergummi** [comment]
@48d90782 I read the announcement on Discord tonight. Incredible work, kudos to your team! I'll make sure to give it a thorough read later today 🥳

**Comment by 48d90782** [comment]
@Radiergummi Thank you very much :)
