### ISSUE TITLE
[RR2] Abnormal job distribution in 2.0 static pool

### ISSUE THREAD

**Issue by wolfy-j** [spiral/roadrunner#396]
With 2.0 pool it seems that faster job completes - less workers used (it seems to be use FIFO instead of LIFO). This is not a critical issues but might mislead some users.

https://image.prntscr.com/image/IhzTceX3QfW9DzT-gyld6w.png

To reproduce execute 100 jobs with intervals between them enought to return worker to stack.

**Comment by 48d90782** [comment]
Fixed by #462 , removed debug mutex from the ServeHTTP method.
 https://media.discordapp.net/attachments/428563026560679975/791413317197234198/unknown.png

**Comment by wolfy-j** [comment]
> mutex from the ServeHTTP method

This is painful to hear. Good to go.
