### ISSUE TITLE
[BUG] rr-worker.bat - stdout error

### ISSUE THREAD

**Issue by darakanoit** [spiral/roadrunner#410]
Stdout error when running `command: 'php vendor/bin/rr-worker.bat'`
.bat in Windows should run without "php" at the beginning of the command, since there is already a php call inside .bat.
A temporary solution is to run the php worker you need directly,(`command: 'php vendor/spiral/roadrunner-laravel/bin/rr-worker'` [issue](https://github.com/spiral/roadrunner-laravel/issues/19) ) as you constantly need to modify .bat files or change the ability to call.

**Comment by 48d90782** [comment]
Hello @darakanoit. What is the reason to leave a PHP command in the `.bat` file instead of direct command? I'm not sure that we should support such commands thus we may have a lot of different errors with this pattern (for sure we may discuss the use-cases). @wolfy-j What do you think?

**Comment by darakanoit** [comment]
I think these scripts should be removed. And directly call the php worker.

**Comment by wolfy-j** [comment]
Bats will intercept pipes, this method won't work with RR.

**Comment by 48d90782** [comment]
In the RR2, only commands in form of `php <script>.php` will be accepted. Please, feel free to reopen this ticket if you have the reason to run other types of commands. Thanks.
