### ISSUE TITLE
[RR2]  Middlewares by transport

### ISSUE THREAD

**Issue by 48d90782** [spiral/roadrunner#413]
At the moment we have middlewares in RR2 which can be collected by interface from middleware-provider plugins. But we do not have a separation between `http`, `https`, `http2`, `fcgi` middleware. This ticket is RFC to discuss our strategy to handle such cases.

**Comment by wolfy-j** [comment]
I think this ticket can be closed as I can hardly imagine the situation when RR serves multiple endpoints with different middleware at the moment.

**Comment by 48d90782** [comment]
@wolfy-j Yep, agree
