### ISSUE TITLE
[FEATURE REQUEST] make PHP 8 compatible

### ISSUE THREAD

**Issue by cidious** [spiral/roadrunner#417]
**Is your feature request related to a problem? Please describe.**
I cannot update to PHP8 because the composer package requires php: ^7.2 which is not compatible with 8.0

**Describe the solution you'd like**
test against 8.0 and update the requirements

**Comment by leoqbc** [comment]
Hi @cidious I did ```--ignore-platform-reqs``` over composer to get it forced, workeddocker i fine for me, I even got the rr binary to.

Maybe it could be a temporary turn around.

**Comment by wolfy-j** [comment]
https://github.com/spiral/roadrunner/pull/419

**Comment by 48d90782** [comment]
@48d90782 (note) Should be 2 PRs, for RR1 and RR2

**Comment by 48d90782** [comment]
@cidious @leoqbc Now in the `master` branch. `1.9.0` relese expected by end of the week.

**Comment by leoqbc** [comment]
Uou NICE! thanks Valery!
