### ISSUE TITLE
Symfony worker (for inclusion in the wiki)

### ISSUE THREAD

**Issue by dunglas** [spiral/roadrunner#42]
Hi, thanks for this very interesting project!

Here is a worker to serve apps based on the default Symfony skeleton:

```php
<?php
// worker.php
// Install the following mandatory packages:
// composer req spiral/roadrunner symfony/psr-http-message-bridge

ini_set('display_errors', 'stderr');

use App\Kernel;
use Spiral\Goridge\StreamRelay;
use Spiral\RoadRunner\PSR7Client;
use Spiral\RoadRunner\Worker;
use Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory;
use Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory;
use Symfony\Component\Debug\Debug;
use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\HttpFoundation\Request;

require 'vendor/autoload.php';

// The check is to ensure we don't use .env in production
if (!isset($_SERVER['APP_ENV']) && !isset($_ENV['APP_ENV'])) {
    if (!class_exists(Dotenv::class)) {
        throw new \RuntimeException('APP_ENV environment variable is not defined. You need to define environment variables for configuration or add "symfony/dotenv" as a Composer dependency to load variables from a .env file.');
    }
    (new Dotenv())->load(__DIR__.'/.env');
}

$env = $_SERVER['APP_ENV'] ?? $_ENV['APP_ENV'] ?? 'dev';
$debug = (bool) ($_SERVER['APP_DEBUG'] ?? $_ENV['APP_DEBUG'] ?? ('prod' !== $env));

if ($debug) {
    umask(0000);

    Debug::enable();
}

if ($trustedProxies = $_SERVER['TRUSTED_PROXIES'] ?? $_ENV['TRUSTED_PROXIES'] ?? false) {
    Request::setTrustedProxies(explode(',', $trustedProxies), Request::HEADER_X_FORWARDED_ALL ^ Request::HEADER_X_FORWARDED_HOST);
}

if ($trustedHosts = $_SERVER['TRUSTED_HOSTS'] ?? $_ENV['TRUSTED_HOSTS'] ?? false) {
    Request::setTrustedHosts(explode(',', $trustedHosts));
}

$kernel = new Kernel($env, $debug);
$relay = new StreamRelay(STDIN, STDOUT);
$psr7 = new PSR7Client(new Worker($relay));
$httpFoundationFactory = new HttpFoundationFactory();
$diactorosFactory = new DiactorosFactory();

while ($req = $psr7->acceptRequest()) {
    try {
        $request = $httpFoundationFactory->createRequest($req);
        $response = $kernel->handle($request);
        $psr7->respond($diactorosFactory->createResponse($response));
        $kernel->terminate($request, $response);
        $kernel->reboot(null);
    } catch (\Throwable $e) {
        $psr7->getWorker()->error((string)$e);
    }
}
```

And the corresponding `.rr.yaml` file:

```yaml
http:
  address: 0.0.0.0:8080
  workers:
    command: "php test-sf/worker.php"
    pool:
      numWorkers: 4

static:
  dir:   "test-sf/public"
  forbid: [".php", ".htaccess"]
```

Would you mind including it in the wiki?

**Comment by wolfy-j** [comment]
Done! https://github.com/spiral/roadrunner/wiki/Symfony-Framework Let me know if you want to change something in the article. I wonder if GitHub has any protocol for Wiki PRs.

**Comment by wolfy-j** [comment]
FYI, you can define ENV in `env` section of config, these variables would be PHP process specific.

**Comment by dunglas** [comment]
Thanks @wolfy-j. Indeed env vars should probably be moved here. I'll send you the changes when ready.

**Comment by mnavarrocarter** [comment]
Yeap, the folder is pointing to the right direction and exists. Running with `-d` flag shows no output. The error happens at browser level when tries to load the js.

![image](https://user-images.githubusercontent.com/17072441/46355087-7c417b80-c636-11e8-8554-deff5776d39f.png)

**Comment by wolfy-j** [comment]
Does `-d` show any other requests coming to RR?

**Comment by mnavarrocarter** [comment]
Yeap, and found the assets ones. They are answered with 404s.

![image](https://user-images.githubusercontent.com/17072441/46355255-d6dad780-c636-11e8-88ab-dc53c1a99f9a.png)

**Comment by mnavarrocarter** [comment]
Yeah, found it. Is passing the requests for files directly to the application.

**Comment by mnavarrocarter** [comment]
Daaang I'm stupid! The `static` config was not properly indented. 

Sorry for wasting your time @wolfy-j . I'm loving the project already!! :)

**Comment by wolfy-j** [comment]
This is correct behavior if file not found or static service is disabled (identical to nginx `try_files`).

**Comment by wolfy-j** [comment]
> Daaang I'm stupid! The `static` config was not properly indented.
> 
> Sorry for wasting your time @wolfy-j . I'm loving the project already!! :)

Ugh, yaml is really annoying sometimes. Try using json config instead if you run into this problem often. :)

**Comment by ruudk** [comment]
I just tried this example, but it doesn't work. I get this error: `worker error: invalid prefix (checksum)`
This is shown in my PHP error output:
```
[05-Oct-2018 09:50:32 UTC] PHP Fatal error:  Uncaught ErrorException: Warning: unpack(): Type C: not enough input, need 1, have 0 in /var/www/app/vendor/spiral/goridge/php-src/StreamRelay.php:110
Stack trace:
#0 /var/www/app/vendor/spiral/goridge/php-src/StreamRelay.php(76): Spiral\Goridge\StreamRelay->fetchPrefix()
#1 /var/www/app/vendor/spiral/roadrunner/src/Worker.php(51): Spiral\Goridge\StreamRelay->receiveSync(NULL)
#2 /var/www/app/vendor/spiral/roadrunner/src/Worker.php(56): Spiral\RoadRunner\Worker->receive(Array)
#3 /var/www/app/vendor/spiral/roadrunner/src/PSR7Client.php(45): Spiral\RoadRunner\Worker->receive(Array)
#4 /var/www/app/worker.php(51): Spiral\RoadRunner\PSR7Client->acceptRequest()
#5 {main}
  thrown in /var/www/app/vendor/spiral/goridge/php-src/StreamRelay.php on line 110
```

When I change the while loop to this:
```php
while ($req = $psr7->acceptRequest()) {
    try {
        $resp = new \Zend\Diactoros\Response();
        $resp->getBody()->write("hello world");

        $psr7->respond($resp);
    } catch (\Throwable $e) {
        $psr7->getWorker()->error(get_class($e));
        $psr7->getWorker()->error((string)$e);
    }
}
```

it works fine.

What am I doing wrong?

**Comment by wolfy-j** [comment]
Do you echo anything to STDOUT without buffers? There is an option how you can debug it.

Switch RR to work over TCP:

```yaml
workers:
    relay: "tcp://localhost:5000"
```

Use SocketRelay instead of SteamRelay:

```php
$relay = new SocketRelay("localhost", 5000);
```

**Comment by ruudk** [comment]
Weird, now it works. But I don't see anything being echo'd?
```docker@1cbc8a77c410:/var/www/app$ /usr/local/bin/roadrunner serve -d -v
DEBU[0000] [rpc]: started
DEBU[0000] [http]: started
INFO[0002] 172.18.0.1 302 GET http://my-domain.eu.ngrok.io/
INFO[0004] 172.18.0.1 302 GET http://my-domain.eu.ngrok.io/
INFO[0009] 172.18.0.1 200 GET http://my-domain.eu.ngrok.io/_profiler/empty/search/results?limit=10
INFO[0013] 172.18.0.1 200 GET http://my-domain.eu.ngrok.io/_profiler/df487a
INFO[0017] 172.18.0.1 200 GET http://my-domain.eu.ngrok.io/cart/1
INFO[0022] 172.18.0.1 200 GET http://my-domain.eu.ngrok.io/cart/1
INFO[0023] 172.18.0.1 200 GET http://my-domain.eu.ngrok.io/cart/1
INFO[0025] 172.18.0.1 302 GET http://my-domain.eu.ngrok.io/_profiler/search?limit=10
INFO[0025] 172.18.0.1 200 GET http://my-domain.eu.ngrok.io/_profiler/d179e9/search/results?ip=&limit=10
INFO[0027] 172.18.0.1 200 GET http://my-domain.eu.ngrok.io/_profiler/d179e9
INFO[0030] 172.18.0.1 200 GET http://my-domain.eu.ngrok.io/_profiler/d179e9?panel=time
```

**Comment by ruudk** [comment]
I started RR and in a new terminal opened `php worker.php` but it didn't output anything. It's just waiting... Also tried to move the SF kernel->boot to outside the while loop. No difference.

**Comment by ruudk** [comment]
When doing a couple requests, and monitor `rr http:workers` it stays up. So the worker doesn't die.

**Comment by wolfy-j** [comment]
So it's not bootloader issues, sounds like you output something to STDOUT while running your script. Is it possible you have some warnings and `display_errors` points to STDOUT?

Since it's working over sockets I can conclude that your workers are fine, but they definitely use pipes for something which creates conflicts with Goridge relays.

P.S.  `Warning: unpack(): Type C: not enough input, need 1, have 0 in /var/www/app/vendor/spiral/goridge/php-src/StreamRelay.php:110` this error is expected if you start your worker manually without properly formatting your data frames.

**Comment by wolfy-j** [comment]
Do you use any `header` functions? They will write to STDOUT as well.

**Comment by wolfy-j** [comment]
More info added here: https://github.com/spiral/roadrunner/wiki/PHP-Workers

**Comment by ruudk** [comment]
I don't have any header functions in use. Also checked output of `headers_list()` and its empty. Is there a way of capturing the output of the `php worker.php` file?

**Comment by ruudk** [comment]
I'm running this inside Docker btw, not sure if that's related.

**Comment by ruudk** [comment]
Problem solved:
```
env(LOG_STREAM): 'php://stdout'
```

Sorry everybody!

**Comment by ruudk** [comment]
The Symfony example is not performant at all. It's doing a `$kernel->reboot(null);` after every request. Is that really necessary? Why not just do `$kernel->boot();` before the while loop, and then process all the requests without rebooting? Makes it much faster.

**Comment by dunglas** [comment]
Yes it is, some Symfony services are stateful. You must reset their states before handling a different requests to avoid side effects.

**Comment by ruudk** [comment]
Wasn't this fixed with resettable services?

**Comment by BunnyHolder** [comment]
PM has a lot of reseting going on: https://github.com/php-pm/php-pm-httpkernel/blob/master/Bootstraps/Symfony.php 

With reset tag in symfony now, this should be a lot smaller.
