### ISSUE TITLE
[BUG] RPC connection refused

### ISSUE THREAD

**Issue by hugochinchilla** [spiral/roadrunner#425]
Hello, first of all thank you for this software, it's being super useful for me and  my team.

We have been using the prometheus metrics reporter for a while and yesterday I got an error because the RPC server did not accept the connection, here are the logs from the server:

```
Dec 1 19:45:08 production-pt-2030-api-9fd75578d-svm28 2030-api DEBU[0000] [headers]: disabled                          
Dec 1 19:45:08 production-pt-2030-api-9fd75578d-svm28 2030-api DEBU[0000] [health]: disabled                           
Dec 1 19:45:08 production-pt-2030-api-9fd75578d-svm28 2030-api DEBU[0000] [reload]: disabled                           
Dec 1 19:45:08 production-pt-2030-api-9fd75578d-svm28 2030-api DEBU[0000] [rpc]: started                               
Dec 1 19:45:08 production-pt-2030-api-9fd75578d-svm28 2030-api DEBU[0000] [http]: started                              
Dec 1 19:45:08 production-pt-2030-api-9fd75578d-svm28 2030-api DEBU[0000] [metrics]: started                           

// .... some normal traffic

Dec 1 19:53:01 production-pt-2030-api-9fd75578d-svm28 2030-api WARN WARN[0472] 18:53:01 WARNING   [php] Warning: socket_connect(): unable to connect [111]: Connection refused ["exception" => ErrorException { …}] 
Dec 1 19:53:01 production-pt-2030-api-9fd75578d-svm28 2030-api WARN WARN[0472] 18:53:01 ERROR     [app] unable to establish connection tcp://127.0.0.1:6001 ["exception" => Spiral\Goridge\Exceptions\RelayException { …}] 
Dec 1 19:53:01 production-pt-2030-api-9fd75578d-svm28 2030-api DEBU[0473] [http]: stopped                              
Dec 1 19:53:01 production-pt-2030-api-9fd75578d-svm28 2030-api DEBU[0473] [metrics]: stopped
```

The first thing I thought was that the rpc server was failing, but after seeing the logs I'm not sure if maybe this was a timing issue due a pod being restarted for whatever reason kubernetes tought neccessary (I'm still investigating this).

In any case, I think It could be possible to implement some kind of wait between the moment where the http server stops and before the metrics server is stopped, waiting for running connections to be finished.

**Comment by hugochinchilla** [comment]
Another thing I noticed is that there is no logged message fgor the RPC being shut down, for other pods I can see this message being logged on anormal shutdown, I think this may be related because the error ocurred on a slow path and the wait time for a pod to stop after a SIGKILL is too low, so maybe this is a problem of configuration on my own.

If you think the situation I described is well handled in the code feel free to ignore and close this issue.

**Comment by 48d90782** [comment]
Hey @hugochinchilla . Thanks for the detailed description. I'll take a look at this behavior.

**Comment by 48d90782** [comment]
Discussion notes:
1. Make an `http.Serve` method non-blocking (do not wait until all workers started, just provide a channel with errors inside the goroutine).
2. Put pool declaration into the goroutine.
3. Double-check for races.

**Comment by 48d90782** [comment]
Hey @hugochinchilla. I see from your logs, that this issue related to the RR1, am I right?

**Comment by hugochinchilla** [comment]
yes

**Comment by 48d90782** [comment]
> yes

We found a similar issue for the RR2, so, it will be fixed in the RR2 first. Sorry for that, but, RR1 will receive only super urgent fixes at the moment until we move all plugins to RR2.

**Comment by hugochinchilla** [comment]
don't worry, we will update to RR2 soon
