### ISSUE TITLE
New releases and binaries build automation

### ISSUE THREAD

**Issue by 48d90782** [spiral/roadrunner#431]
At the moment we write a RR version on the linking stage with `LDFLAGS` manually. And forming releases also manually. Now, it's time to move forward. The scope of this issue is the following:
1. Support automatic version creation on the CI stage.
2. Automated releases and binaries build.

**Comment by tarampampam** [comment]
Example CI: https://github.com/tarampampam/tinifier/blob/master/.github/workflows/release.yml

**Comment by tarampampam** [comment]
@48d90782 Please, rename this issue to `New releases and binaries build automation` (one task - one issue)
