### ISSUE TITLE
[FEATURE REQUEST] Roadrunner stderr and application log

### ISSUE THREAD

**Issue by Logioniz** [spiral/roadrunner#435]
Hello.

I couldn't find a support channel to ask questions, so I came here.

I want to run roadrunner in a docker container and write application logs to stderr.

Is there a way to output the stderr in roadrunner that is passed by the worker via stderr?

At this point, I found a way to get a stderr by running roadrunner with the -d (debug) flag. In my opinion, this imposes additional overhead on running the [debug server](https://github.com/spiral/roadrunner/blob/master/cmd/rr/cmd/root.go#L129). Also in this mode, roadrunner logs each request (the request itself, its running time and the http method).

It would be nice if it was possible to receive only the application log in the stderr without additional overhead.

**Comment by 48d90782** [comment]
Hi @Logioniz. I guess it's not possible in RR version 1 (@wolfy-j correct me if I wrong). But will be definitely possible with the new RR version 2 which is coming very soon :)

**Comment by wolfy-j** [comment]
The solution for this problem alteady exists in 2.0, so please wait. Though, you'll have to rewrite some of the worker code.

**Comment by Shikachuu** [comment]
@48d90782, I might be mistaken, but this should be closed in favor of #378, right?

**Comment by 48d90782** [comment]
@Shikachuu Yep, you are correct. The fully customizable log will be in the RR2. Unfortunately, it's impossible to do that in the RR1 :(

**Comment by wolfy-j** [comment]
It is partially resolved as now you can isolate the server/application log from the rest of the system. But now we have the possibility to add a separate channel for domain-specific logs.

**Comment by rustatian** [comment]
@Logioniz Done in the RR2 https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L57.
