### ISSUE TITLE
[FEATURE REQUEST] Prometheus metrics. Objectives for summary metrics type.

### ISSUE THREAD

**Issue by fr05t1k** [spiral/roadrunner#439]
Hey guys,

Thanks for your great software.
I have a suggestion. I didn't find ability to specify `objectives` for `summary` metrics type. Did I miss something? 
If there is no ability to specify `objectives` for `summary` then there no different between `histogram` without `buckets` and `summary` without `objectives`.

![image](https://user-images.githubusercontent.com/2131624/101516699-cb3d7680-394d-11eb-93f1-cfe96b324c90.png)
![image](https://user-images.githubusercontent.com/2131624/101516777-e4462780-394d-11eb-9d77-8730ebaecfa5.png)

**Comment by 48d90782** [comment]
Hi @fr05t1k. Thanks for the feature request. You are right, objectives for summary metrics type not presented in the config and `Collector` struct. We are planning a release next week, so, I think I can possibly have `objectives` ready in this release.

**Comment by 48d90782** [comment]
@fr05t1k https://github.com/spiral/roadrunner/releases/tag/v1.9.1

**Comment by helloworld-333** [comment]
Hi, @rustatian. The latest version of the metrics plugin does not have the ability to specify Objectives via an rpc call [(Code)](https://github.com/roadrunner-server/metrics/blob/eaeea81315382b0fb760535a5368cbecf9feb9d5/rpc.go#L225)

**Comment by rustatian** [comment]
Hey @helloworld-333 👋🏻 
Objectives were always used via the configuration. They weren't removed, they just weren't added to the RPC previously. 
Fixed: https://github.com/roadrunner-server/metrics/commit/d304067fb5c2fc8ccd454b1a35ce5c60a63c86c2
Will be in the 2024.3 release.
