### ISSUE TITLE
[WRONG REPO] How to merge two-way lanes based on xodr into 'Freeway' pattern?

### ISSUE THREAD

**Issue by EchoYJJ** [spiral/roadrunner#450]
After importing xodr(OpenDrive file) into Roadrunner, I noticed that lanes in different directions are divided far apart.
![image](https://user-images.githubusercontent.com/75726020/102330442-7b515600-3fc4-11eb-842b-389076c4221b.png)
However, for a more realistic simulation, what I really want is the 'Freeway' pattern provided by roadrunner itself.
![image](https://user-images.githubusercontent.com/75726020/102330718-df741a00-3fc4-11eb-89eb-8ebae012f398.png)
If you know how to merge two-way lanes based on xodr into 'Freeway' pattern, please give me some advices, thanks!

**Comment by wolfy-j** [comment]
I'm pretty sure our product has nothing to do with roads. You have probably mistaken the repository.
