### ISSUE TITLE
[QUESTION] What's the difference between roadrunner and fpm

### ISSUE THREAD

**Issue by lishiling5121** [spiral/roadrunner#461]
The document says, roadrunner  can avoid restarting the PHP worker process once for each request, but the FPM woker process is resident in memory. How to understand the document says ?

**Comment by 48d90782** [comment]
@wolfy-j Could you please describe the differences? :)

**Comment by wolfy-j** [comment]
FPM PHP process is resident in memory but only during the request execution, worker process will be destroyed or memory wiped after every request. RoadRunner avoids that.

**Comment by 48d90782** [comment]
@lishiling5121 Thanks for the question, if you have any other questions, feel free to re-open this issue.
