### ISSUE TITLE
IDE Integration: How to use http:reset when using Docker

### ISSUE THREAD

**Issue by ruudk** [spiral/roadrunner#47]
I'm running roadrunner inside a docker container. How do I instruct my IDE to perform a RR http:reset on file change?

**Comment by ruudk** [comment]
Mind = Blown :D

**Comment by wolfy-j** [comment]
Is a good sense? :)

**Comment by wolfy-j** [comment]
You can also try something like this: https://github.com/radovskyb/watcher

**Comment by ruudk** [comment]
Yep, this works perfectly. Might be good to slightly change the Wiki a bit. 

Use 
```
rpc:
  listen: tcp://:6001
```

make sure to forward / expose port 6001 

Then run `rr http:reset` locally on file change.

**Comment by wolfy-j** [comment]
Done https://github.com/spiral/roadrunner/wiki/IDE-Integration
