### ISSUE TITLE
[Docker] PHP GRPC, Protobuf and Msgpack extensions should be available in base image by default

### ISSUE THREAD

**Issue by wolfy-j** [spiral/roadrunner#488]
These are common extensions required by Temporal, KV, and GRPC plugins. We should enable them by default.

**Comment by 48d90782** [comment]
@rauanmayemir It's a very popular serialization format. Like protobuf or JSON. You can take a look at: https://msgpack.org/index.html

**Comment by wolfy-j** [comment]
It’s alternative format for new RPC codes. It needed to properly pass binary data. It’s optional but provide performance benefits.
