### ISSUE TITLE
Context how to use it?

### ISSUE THREAD

**Issue by Dexus** [spiral/roadrunner#5]
Is there a way to use the Payload Context?

Cant find any info how to use it...

**Comment by wolfy-j** [comment]
```
rsp, err := p.Exec(&rr.Payload{Body: []byte("hello"), Context:  []byte("header")})
```

**Comment by wolfy-j** [comment]
```php
while ($body = $rr->receive($context)) {
```

$context here is a reference, so you can use it inside the loop

**Comment by Dexus** [comment]
But i don‘t get the context from Go inside the PHP script, so where will the context be set?

The example will not set the $context variable

Von meinem iPhone gesendet

**Comment by wolfy-j** [comment]
Are you sure? 

Take a look at this test: https://github.com/spiral/roadrunner/blob/master/static_pool_test.go#L101
https://github.com/spiral/roadrunner/blob/master/tests/head.php#L13

Context is being filled into $ctx variable here.

**Comment by Dexus** [comment]
You are right, I did use the variable to late, and had overwrite it already.

Sorry for the false alarm.
