### ISSUE TITLE
[BUG, RR1] superfluous response in console

### ISSUE THREAD

**Issue by eldario** [spiral/roadrunner#504]
_Hello_,
Maybe I'll repeat #301 and #333 then I'll just share my problem.

I start the server with the settings:
```yml
    pool:
      numWorkers: 5
      maxJobs: 10
      allocateTimeout: 60
      destroyTimeout: 60
```
and this command:
```sh
$ rr serve -c .rr.yaml
```

I begin to conduct a stress test:
```sh
 for i in {0..20}; do ab -n 1000 -c 200 "https://127.0.0.1:8080/" 2>&1 | grep 'per second:'; done
```

During the test and after the end of it, **everything** works properly. I don't see any new lines, since the `-v` `-d` options are off.

I start the test again and after a while I lower `CTRL` + `C` (SIGINT)
And the entire console crashes with messages
```sh
http: superfluous response.WriteHeader call from github.com/spiral/roadrunner/service/http.(*Handler).handleError (handler.go: 158)
```
After enabled options `-v -d`:
```sh
http: superfluous response.WriteHeader call from github.com/spiral/roadrunner/service/http.(*Handler).handleError (handler.go:158)
INFO[0071] 192.168.48.1 {797ms} 500 GET https://127.0.0.1:8080/ error: write tcp 192.168.48.7:443->192.168.48.1:36260: write: broken pipe, during handle this error, ResponseWriter error occurred: write tcp 192.168.48.7:443->192.168.48.1:36260: write: broken pipe 
```

I tried to comment this line in [handler.go](https://github.com/spiral/roadrunner/blob/v1.9.2/service/http/handler.go#L158) and managed to hide this error:

```go
} else {
    // ResponseWriter is ok, write the error code
    // w.WriteHeader(int(h.appErrorCode))
}
```

I expected to see this happen: no new messages, 

Instead, this happened: after each `broken pipe` I see this message

The version of RR used: **1.9.2**
</p>
</details>

**Comment by 48d90782** [comment]
Thanks for the report @eldario. I'll dig into this problem and notify you, when this issue will be fixed.

**Comment by 48d90782** [comment]
@eldario I had a look at this issue.  The connection, which RR processes at the moment interrupts when you hit `CTRL+C` during the testing. But, in the RR this connection is still in the handler `ServeHTTP`. Then when RR sees the error (can't respond back, because the connection is broken) it tries to write to the closed `ResponseWriter` which leads to this issue. This is not something critical, but I agree, that we should print some user-friendly message instead of a message from stdlib.

**Comment by 48d90782** [comment]
@eldario You can also try RR2 RC build. I tried your test and didn't see any issues.

**Comment by eldario** [comment]
@rustatian 

I apologize for the fact that my issue is still open.

Using `rr` version `2.2.1` - this problem is no longer observed.

Thanks a lot.

Close it, please.

**Comment by rustatian** [comment]
Thanks @eldario 😃
