### ISSUE TITLE
example setup

### ISSUE THREAD

**Issue by marcelloh** [spiral/roadrunner#51]
IS there an example setup somewhere (that runs straight away?)

**Comment by wolfy-j** [comment]
https://github.com/spiral/roadrunner/wiki/PHP-Workers

**Comment by marcelloh** [comment]
So I save this:
```
http:
  address:    0.0.0.0:8080
  workers:
    command:  "php psr-worker.php"
    pool:
      numWorkers: 4
```
in .rr.yaml, right?

then I start rr (on Windows), but it still give me the same help.

**Comment by wolfy-j** [comment]
rr have set of sub-commands `serve` is one you want, so `rr serve`. In order to see more debug info `rr serve -v -d`

**Comment by wolfy-j** [comment]
You can read more about server commands here: https://github.com/spiral/roadrunner/wiki/Server-Commands

**Comment by marcelloh** [comment]
command:  "php psr-worker.php" does not work for me, because I have no php in my path,
so I want to use the exact location where it php is installed.

Then it gives me an error:
WARN[0000] config: While parsing config: yaml: line 4: found unknown escape character

so I changed all backslashes into forward slashes, but now it gives me:
RRO[0000] [http]: unable to connect to worker: unexpected response, header is missing: exit status 1

**Comment by wolfy-j** [comment]
Sounds like you have invalid characters in your yaml (this format is very picky about indents), try json:

```json
{
  "http": {
    "address": "0.0.0.0:8080",
    "workers": {
      "command": "path-to-php/php psr-worker.php",
      "pool": {
        "numWorkers": 4
      }
    }
  }
}
```

**Comment by wolfy-j** [comment]
If you still get an error, try to invoke your php script manually and see what happen:

```bash
php psr-worker.php
```

It should not die and must wait.

**Comment by marcelloh** [comment]
Ok, was missing the psr-worker.php.

Now it complains about not having a vendor folder....
Nothing states a composer action.... hmmm... now what to do?

**Comment by wolfy-j** [comment]
Composer action is first in a list, please check how to install and configure composer here: https://getcomposer.org/download/

**Comment by marcelloh** [comment]
hmm.. missed that (it was on top of page, sorry)
Now it works without any messages  (except the hello world)

Thanx for the patience

**Comment by wolfy-j** [comment]
NP :)
