### ISSUE TITLE
[FEATURE REQUEST] Graceful Shutdown

### ISSUE THREAD

**Issue by changwuf31** [spiral/roadrunner#555]
**Is your feature request related to a problem? Please describe.**
Graceful shutdown of temporal workers if requested

**Describe the solution you'd like**
When SIGTERM is sent, then I'd like for roadrunner to:
- stop receiving jobs
- process all pooled jobs
- shutdown workers after all pooled jobs has been processed.

**Describe alternatives you've considered**

**Additional context**
This is a continuation of https://github.com/temporalio/roadrunner-temporal/issues/34

**Comment by 48d90782** [comment]
I am going to implement a graceful shutdown like in the Kubernetes. First CTRL+C (SIGINT, SIGTERM) hit will stop the execution but wait for the requests which already came to the RR. The second hit will force RR to exit.
