### ISSUE TITLE
[RR2] TTL, MaxMemory, Idle_ttl should be perceived as soft errors

### ISSUE THREAD

**Issue by 48d90782** [spiral/roadrunner#558]
Supervisors options like `ttl`, `max_memory`, and `idle_ttl` are soft errors. That means if a worker consumes `max_memory+1mb` over allowed memory it should be marked as invalid and stopped after the job will be done. This also applies to the `idle_ttl` and `ttl` options.
1. Update supervisor_pool.go. Use `worker[i].Status().Set(worker.Invalid)` instead of `sp.pool.RemoveWorker(workers[i])`.
2. Update tests for the supervisor

**Comment by wolfy-j** [comment]
ref #368
