### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by estahn** [spiral/roadrunner#56]
Are there some form of metrics exposed?

**Comment by wolfy-j** [comment]
Not in a default build. But it's extremelly easy to add middleware using https://github.com/prometheus/client_golang and https://github.com/spiral/roadrunner/wiki/Middlewares

**Comment by wolfy-j** [comment]
@estahn let me know if you have any particular requirements for this feature, I will close this ticket till then. Thank you

**Comment by wolfy-j** [comment]
@estahn FYI, this feature is now available since 1.4.5
