### ISSUE TITLE
[BUG] v2.0.0-RC.4 not buildable

### ISSUE THREAD

**Issue by steffendietz** [spiral/roadrunner#563]
I tried building the project using:
```shell
git checkout v2.0.0-RC.4
go mod download
make
```

I expected to see this happen: to get a built `rr` binary as per the `build` target of the `Makefile`.

Instead, this happened: I received an error:
```shell
/app/roadrunner # make
CGO_ENABLED=0 go build -trimpath -ldflags "-s" -o ./rr ./cmd/main.go
stat /app/roadrunner/cmd/main.go: directory not found
make: *** [Makefile:15: build] Error 1

```

The version of RR used: v2.0.0-RC.4

Further detail:
The changelog of `v2.0.0-RC.4` specifically mentions: 
* :construction_worker: Add static, headers, status, gzip plugins to the `main.go`.

But I couldn't find the `main.go` in the whole project.

I looked through past (pre-)releases of the `v2.0.0` trying to find where the file went and noticed something odd going on with the releases:
* version [`v2.0.0-RC.3`](https://github.com/spiral/roadrunner/tree/51d0f10096614bb300c439d5f973a805987fe4be) same as `RC.4` missing `cmd/main.go`.
* version [`v2.0.0-RC.2`](https://github.com/spiral/roadrunner/tree/bd6bcb28d25e98eff7c95edda1260640f6c6dd72) has a completely different tree structure than the current `v2.0.0-RC.4` release. The `cmd/main.go` is present, but the `cmd` folder is the only folder existing.
There is also a [message](https://github.com/spiral/roadrunner/commit/bd6bcb28d25e98eff7c95edda1260640f6c6dd72) at the top:
**This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.**
* version [`v2.0.0-RC.1`](https://github.com/spiral/roadrunner/tree/8f6cafdc0948a5ea13bf9a811b576aa4b3ef7e4a) source tree is more similar to `RC.3` and `RC.4` again. (`cmd` folder gone, other folders back)
* version [`v2.0.0-beta.25`](https://github.com/spiral/roadrunner/tree/480340464b44aec64661bc9c50357a72a19a4cdc) similar to `v2.0.0-RC.2` completely different source tree again, `cmd/main.go` present.

I'm not to familiar with the project, but I thought the pre-releases should build up to the final release and be more iterative changes. The `v2.0.0` pre-releases sometimes contain completely different source trees.

**Comment by 48d90782** [comment]
Hey @steffendietz. RR2 repository does not contain `main.go` and thus can't be built. I'll remove the `build` target in the Makefile. To build your own RR2 binary or download release, please take a look at the https://github.com/spiral/roadrunner-binary repository.

**Comment by 48d90782** [comment]
ref: #564

**Comment by 48d90782** [comment]
@steffendietz `main.go` mentioned in the commit related to the `roadrunner-binary` repository. Sorry for the confusion, we will cover that case in the documentation.

**Comment by steffendietz** [comment]
Got it. Thanks for clearing it up. :+1:

**Comment by steffendietz** [comment]
If you click through the mentioned tags above, there could still be some undesired artifacts. Namely that not all RC or beta releases of the `spiral/roadrunner` repository sharing the same ancestry.

**Comment by 48d90782** [comment]
This is because earlier was a branch called `roadrunner-binary` related to those commits in this repository. We deleted it and thus you see this message. Thanks to your observation looks :+1:

**Comment by steffendietz** [comment]
I still seem to have trouble finding the changes (static, headers, status, gzip plugins) to the `main.go` file mentioned in the changelog.
I mean they are not in the `spiral/roadrunner-binary` repository.

Also, one could argue that this changelog entry would belong to the `CHANGELOG.md` of the `spiral/roadrunner-binary` repository entirely.

**Comment by 48d90782** [comment]
@steffendietz You are right. These changes are still in progress (but prepared from the RR2 core library). Will be in the `roadrunner-binary` soon.

**Comment by steffendietz** [comment]
Alright. Things are still heavily in flux, obviously. I just had to wrap my head around them.

I'll try importing and registering the plugins in my clone of the `roadrunner-binary` repo as a personal excercise.

Thank you, for your help so far. :+1:

**Comment by 48d90782** [comment]
You are welcome) Also, you can take my `main.go` as a temporary solution:
```go
package main

import (
	"log"

	endure "github.com/spiral/endure/pkg/container"
	"github.com/spiral/roadrunner/v2/plugins/gzip"
	"github.com/spiral/roadrunner/v2/plugins/headers"
	"github.com/spiral/roadrunner/v2/plugins/static"
	"github.com/spiral/roadrunner/v2/plugins/status"

	// plugins
	"github.com/spiral/roadrunner/v2/cmd/cli"
	httpPlugin "github.com/spiral/roadrunner/v2/plugins/http"
	"github.com/spiral/roadrunner/v2/plugins/informer"
	"github.com/spiral/roadrunner/v2/plugins/logger"
	"github.com/spiral/roadrunner/v2/plugins/metrics"
	"github.com/spiral/roadrunner/v2/plugins/reload"
	"github.com/spiral/roadrunner/v2/plugins/resetter"
	"github.com/spiral/roadrunner/v2/plugins/rpc"
	"github.com/spiral/roadrunner/v2/plugins/server"
	"github.com/temporalio/roadrunner-temporal/activity"
	temporalClient "github.com/temporalio/roadrunner-temporal/client"
	"github.com/temporalio/roadrunner-temporal/workflow"
)

func main() {
	var err error
	cli.Container, err = endure.NewContainer(nil, endure.SetLogLevel(endure.ErrorLevel), endure.RetryOnFail(false))
	if err != nil {
		log.Fatal(err)
	}

	err = cli.Container.RegisterAll(
		// logger plugin
		&logger.ZapLogger{},
		// metrics plugin
		&metrics.Plugin{},
		// http server plugin
		&httpPlugin.Plugin{},
		// reload plugin
		&reload.Plugin{},
		// informer plugin (./rr workers, ./rr workers -i)
		&informer.Plugin{},
		// resetter plugin (./rr reset)
		&resetter.Plugin{},
		// rpc plugin (workers, reset)
		&rpc.Plugin{},
		// server plugin (NewWorker, NewWorkerPool)
		&server.Plugin{},

		// static
		&static.Plugin{},
		// headers
		&headers.Plugin{},
		// checker
		&status.Plugin{},
		// gzip
		&gzip.Plugin{},

		// temporal plugins
		&activity.Plugin{},
		&workflow.Plugin{},
		&temporalClient.Plugin{},
	)
	if err != nil {
		log.Fatal(err)
	}

	cli.Execute()
}
```
