### ISSUE TITLE
[BUG, RR1] Proxy IP logged instead of client IP when requests fails due to an internal error

### ISSUE THREAD

**Issue by hugochinchilla** [spiral/roadrunner#568]
I have noticed that when an error ocurrs the IP logged is from the ingress-controller and not the one from the client.

Here is an extract of the logs (ips redacted for privacy concerns):

```
Feb 25 14:29:27 production-es-2030-api-58db7dc845-fpdsc 2030-api INFO INFO[7514] 85.119.0.0 {425ms} 200 GET http://2030-api.habitissimo.es/v1/professionals/availability/jobType/6c968ffb-19ad-51b0-9939-2ee24bdcbd5f/postalCode/07004 
Thursday, Feb 25th 2021, 2:29pm
Feb 25 14:29:28 production-it-2030-api-6d7d8f5d66-x7frz 2030-api INFO INFO[1123] 192.168.81.95 {365.4s} 500 POST http://2030-api.habitissimo.it/v1/serviceRequest worker error: EOF 
Feb 25 14:29:28 production-it-2030-api-6d7d8f5d66-x7frz 2030-api ERRO[1123] worker.258 signal: killed 
Feb 25 14:29:28 production-it-2030-api-6d7d8f5d66-x7frz 2030-api INFO INFO[1123] 192.168.81.95 {336.6s} 500 POST http://2030-api.habitissimo.it/v1/serviceRequest worker error: EOF 
Feb 25 14:29:28 production-it-2030-api-6d7d8f5d66-x7frz 2030-api ERRO[1123] worker.302 write tcp 127.0.0.1:7000->127.0.0.1:58086: write: broken pipe 
Feb 25 14:29:28 production-it-2030-api-6d7d8f5d66-x7frz 2030-api ERRO[1123] worker.302 signal: killed 
```

As you can see the first request is logging the client IP, the followig lines show the IP of the pod running the ingress-controller.

I think the problem originates here:

```go
        // plugins/http/handler.go

	req, err := NewRequest(r, h.uploads)
	if err != nil {
		h.handleError(w, r, err, start)
		return
	}

	// proxy IP resolution
	h.resolveIP(req)
```

The code checks for errors and invokes handleError before calling `resolveIP`.

**Comment by 48d90782** [comment]
Hello @hugochinchilla. Nice catch, thanks. I'll take a look.

**Comment by hugochinchilla** [comment]
Hi, I'm looking at the code trying to provide a fix but I'm having trouble understanding how everything works (I don't know golang actually). 

My first thought was what I explained in the issue description, but taking a look at the code, this would be the cause only if the error happens while creating the request object, but that doesn't seem to be the case, the problem I'm encountering seems to happend at the worker level, at this point `resolveIp` seems to have been already executed:


```
        // plugins/http/handler.go

	// proxy IP resolution
	h.resolveIP(req)

	req.Open(h.log)
	defer req.Close(h.log)

	rsp, err := h.pool.Exec(p)
	if err != nil {
		h.handleError(w, r, err, start)
		return
	}

	resp, err := NewResponse(rsp)
	if err != nil {
		h.handleError(w, r, err, start)
		return
	}
```

Can you offer some guidance to me? I would like to try to fix this issue.

**Comment by wolfy-j** [comment]
Quick question: did you set the trusted proxies list?

**Comment by 48d90782** [comment]
And also, what version do you use? It seems, that logs from the 1.9.2, but code sample from 2.0.

**Comment by hugochinchilla** [comment]
@wolfy-j I don't have the trusted proxies set, but for what I could see in the code it's automatically populated if not present with good default values.

@48d90782 you are right, I was navigating the code in the master branch, I will look again in the proper version and update you if I need any help.

**Comment by rustatian** [comment]
Thanks, @hugochinchilla for the report. RR1 will be completely deprecated since `v2.5.0` which is almost arrived. Only security bugs for the v1 should be filed.
