### ISSUE TITLE
How to try it?

### ISSUE THREAD

**Issue by morozovsk** [spiral/roadrunner#57]
I have .rr.yaml:
```
http:
  address: 0.0.0.0:8080
  workers:
    command: "php psr-worker.php"
    pool:
      numWorkers: 4
```
I've put the code of your example inside psr-worker.php:
```
<?php
ini_set('display_errors', 'stderr');
include "vendor/autoload.php";

$relay = new Spiral\Goridge\StreamRelay(STDIN, STDOUT);
$psr7 = new Spiral\RoadRunner\PSR7Client(new Spiral\RoadRunner\Worker($relay));


while ($req = $psr7->acceptRequest()) {
    try {
        $resp = new \Zend\Diactoros\Response();
        $resp->getBody()->write("hello world");

        $psr7->respond($resp);
    } catch (\Throwable $e) {
        $psr7->getWorker()->error((string)$e);
    }
}
```
I installed composer. (but you dont have info about it)

I tried:

> ./rr serve -v -d

I have errors:

> DEBU[0000] [static]: disabled                           
> DEBU[0000] [rpc]: started                               
> DEBU[0000] [http]: started                              
> ERRO[0000] [http]: unable to connect to worker: PHP Warning:  include(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/test/roadrunner/psr-worker.php on line 3
> PHP Stack trace:
> PHP   1. {main}() /var/www/test/roadrunner/psr-worker.php:0
> 
> Warning: include(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/test/roadrunner/psr-worker.php on line 3
> 
> Call Stack:
>     0.0001     400184   1. {main}() /var/www/test/roadrunner/psr-worker.php:0
> 
> PHP Warning:  include(): Failed opening 'vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/test/roadrunner/psr-worker.php on line 3
> PHP Stack trace:
> PHP   1. {main}() /var/www/test/roadrunner/psr-worker.php:0
> 
> Warning: include(): Failed opening 'vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/test/roadrunner/psr-worker.php on line 3
> 
> Call Stack:
>     0.0001     400184   1. {main}() /var/www/test/roadrunner/psr-worker.php:0
> 
> PHP Fatal error:  Uncaught Error: Class 'Spiral\Goridge\StreamRelay' not found in /var/www/test/roadrunner/psr-worker.php:5
> Stack trace:
> #0 {main}
>   thrown in /var/www/test/roadrunner/psr-worker.php on line 5
> 
> Fatal error: Uncaught Error: Class 'Spiral\Goridge\StreamRelay' not found in /var/www/test/roadrunner/psr-worker.php on line 5
> 
> Error: Class 'Spiral\Goridge\StreamRelay' not found in /var/www/test/roadrunner/psr-worker.php on line 5
> 
> Call Stack:
>     0.0001     400184   1. {main}() /var/www/test/roadrunner/psr-worker.php:0
>  
> DEBU[0000] [rpc]: stopped

What else I need to do for starting your "product"?
Could you please make convenient instructions for running the simplest example.
It is not user friendly now.

**Comment by wolfy-j** [comment]
You can find all the required information including composer commands at this page https://github.com/spiral/roadrunner/wiki/PHP-Workers

**Comment by wolfy-j** [comment]
I have added another link to this page into README.md, I hope it helps.

**Comment by morozovsk** [comment]
thank you. now it works but [too slowly](https://github.com/morozovsk/webserver-performance-comparison).

**Comment by wolfy-j** [comment]
Too slow for what? You are comparing different execution models. Also, running RR with one worker and 10 concurrency does not make any sense.

**Comment by morozovsk** [comment]
> Running RR with one worker is unpractical as IPC overhead would be higher than actual gain.

I also used 4 workers. It was 1.5-2 (with and without keep-alive) times faster but still slow.

>P.S. Also I can't recreate your benchmark as it does not have all the required deps in it. :(

It is inside php files.

For example:

[swooole](https://github.com/morozovsk/webserver-performance-comparison/blob/master/swoole.php):
install: pecl install swoole
run: php swoole.php

[roadrunner](https://github.com/morozovsk/webserver-performance-comparison/blob/master/roadrunner.php):
install roadrunner
config roadrunner
```
.rr.yml:
http:
  address: :1080
  workers:
    command: "php roadrunner.php"
    pool:
      numWorkers: 1
```
run: ./rr serve -v

So I would like to wait for PSR-7 support by swoole or workerman.
