### ISSUE TITLE
[BUG] Can not run php with xdebug or any arguments for php

### ISSUE THREAD

**Issue by sudevva** [spiral/roadrunner#573]
I tried this code:

```go
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php -dzend_extension=xdebug.so bin/console baldinof:roadrunner:worker"
  relay: "unix://var/roadrunner.sock"

http:
  address: "0.0.0.0:8080"
  pool:
    num_workers: 4

<code>
```

We have basic image with xdebug. We disable it by default for performance reason.

I expected to see this happen: run php with xdebug extension, in earlier version < 2.0.0 it was running as expected

Instead, this happened: server_plugin_cmd_factory: stat : no such file or directory

The version of RR used: 2.0.0

Errortrace, Backtrace or Panictrace
```
2021/03/04 12:29:18 handle_serve_command: Serve error:
        endure_start:
        endure_serve_internal: Function call error:
        endure_call_serve_fn: got initial serve error from the Vertex http.Plugin, stopping execution, error: http_plugin_serve:
        server_plugin_new_worker_pool:
        server_plugin_cmd_factory: stat : no such file or directory

<backtrace>
```
Mb it is no sense of checking for file existing?
</p>
</details>

**Comment by 48d90782** [comment]
@sudevva Yeah, I guess I'll lay on the provided command without limitation.

**Comment by sudevva** [comment]
Thank you!

**Comment by 48d90782** [comment]
You are welcome :+1:

**Comment by 48d90782** [comment]
@sudevva Done https://github.com/spiral/roadrunner/releases/tag/v2.0.1
