### ISSUE TITLE
Question: Is it possible to write example of event listener service?

### ISSUE THREAD

**Issue by Alex-Bond** [spiral/roadrunner#58]
Hi!

Is it possible to show an example of how to connect to RabbitMQ in RoadRunner and call PHP when you receiving new event?

**Comment by wolfy-j** [comment]
Hi, 

you can use use this guide https://github.com/spiral/roadrunner/wiki/Standalone-usage

Or take a look at this repository: https://github.com/spiral/jobs (AWS SQS, Local, Beanstalk), we are planning to add RabbitMQ bridge early next year. You can find examples of usage in tests.

**Comment by Alex-Bond** [comment]
> Hi,
> 
> you can use use this guide https://github.com/spiral/roadrunner/wiki/Standalone-usage
> 
> Or take a look at this repository: https://github.com/spiral/jobs (AWS SQS, Local, Beanstalk), we are planning to add RabbitMQ bridge early next year. You can find examples of usage in tests.

Awesome! Thank you for links and looking forward into next year's cool things :)
