### ISSUE TITLE
[RR2, HTTP] Stange error message when request size is too large

### ISSUE THREAD

**Issue by tarampampam** [spiral/roadrunner#584]
RoadRunner config contains:

```yaml
http:
  max_request_size: 1
```

And when I try to send request with size more then 1 Mb - I got next response (500 status code):

```
1 error occurred:
    * http_plugin_serve_http: request body max size is exceeded

"OK"
```

So, my questions is:

- Why this error messaage contains `"OK"` at the end on the line
- RR logs does not contains any error message (`logs.mode: "development"`)

**Comment by 48d90782** [comment]
Notes:
1. "OK" message likely passed from this place https://github.com/spiral/roadrunner/blob/b3cb0cd2428f1bfdd959ea8f3461e2992b6acdb2/plugins/http/handler.go#L167.
2. Errors from the app and the RR should be split. (TODO: Create separate ticket)

**Comment by 48d90782** [comment]
`http_handler_max_size: request body max size is exceeded` message should arrive without "OK" or other weird responses.
