### ISSUE TITLE
Update zendframework/zend-diactoros to 2.x

### ISSUE THREAD

**Issue by alexpts** [spiral/roadrunner#59]

**Comment by wolfy-j** [comment]
I guess it's a side-effect of using https://packagist.org/packages/http-interop/http-factory-diactoros

This library must be patched to support `zendframework/zend-diactoros` 2.x

**Comment by wolfy-j** [comment]
I need a advice, there is 2 options how this issue can be solved:
1) Patch for http-interop/http-factory-diactoros to support `zendframework/zend-diactoros` 2.x which will bump minimal required version of PHP to7.1
2) Keep dependency with https://packagist.org/packages/psr/http-factory only (BC)

**Comment by alexpts** [comment]
Http Factory Diactors use only class PSR7Client.

You can replace package `http-interop/http-factory-diactoros` to  `zendframework/zend-diactoros`.
Zend component has impementation for `UploadedFileFactoryInterface`, `StreamFactoryInterface`, `RequestFactoryInterface`.

After replace package you can remove deps `http-interop/http-factory-diactoros`

**Comment by alexpts** [comment]
I can check it and prepare PR for replace

**Comment by wolfy-j** [comment]
Check #45 :)

**Comment by alexpts** [comment]
I don`t understand why need `http-interop`. It is proxy for `zend-diactoros`. 

See impementasion:
1) https://github.com/http-interop/http-factory-diactoros/blob/master/src/RequestFactory.php
2) https://github.com/zendframework/zend-diactoros/blob/master/src/ResponseFactory.php
I don`t see extra logic. It is empty wrapper for delegate work to zend.

1) https://github.com/http-interop/http-factory-diactoros/blob/master/src/StreamFactory.php
2) https://github.com/zendframework/zend-diactoros/blob/master/src/StreamFactory.php
Only proxy to zend.

1) https://github.com/http-interop/http-factory-diactoros/blob/master/src/UploadedFileFactory.php
2) https://github.com/zendframework/zend-diactoros/blob/master/src/UploadedFileFactory.php
Only proxy to zend.

`roadrunner` -> (PSR-7) `http-interop` -> (PSR-7) `zend`
`roadrunner` ->  (PSR-7) `zend`

I think don`t need add concret vendor for PSR-7. But need examples for integration with some PSR-7 vendor

**Comment by wolfy-j** [comment]
Apparently Slim uses its own implementation of PSR7 per #45 removing PSR-7 in order to use PSR-17 is not a that bad idea due to possible decoupling from Zend D (though it's still there by default).
  
For right now I believe the best option is to use RR specific `http-factory` implementation with default dependency on Zend D 1.x|2.x

I'll try to work it out after dealing with other work.

**Comment by wolfy-j** [comment]
fixed in 1.3.0
