### ISSUE TITLE
[QUESTION] Websocket example.

### ISSUE THREAD

**Issue by alxbndrs** [spiral/roadrunner#593]
Hello there! I want to implement some kind of backend chat service. And I want to make it using PHP and RR. But I didn't find any documentation about WS in the RR. Maybe you have any code-example how to deal with WS in RR ? Or maybe you can forward me to some documentation instead ?

Thank you in advance!

**Comment by 48d90782** [comment]
Hey @alxbndrs. It's a pleasure to meet you. You can have a look at the documentation here: https://spiral.dev/docs/broadcast-websockets
But please, note, that at the moment we didn't update `broadcast` and `broadcast-ws` to the RR v2, so, you have to use v1.9.2.

**Comment by alxbndrs** [comment]
Thanks! I'm already using rr 1.* on the production, so it's not a problem. =)
