### ISSUE TITLE
[QUESTION] What can cause roadrunner to respond with a 502 status code? [1.9.2]

### ISSUE THREAD

**Issue by hugochinchilla** [spiral/roadrunner#595]
Hi, I'm trying to debug some issues I'm having with my app and I have stumbled upon some logs I can't explain with RR docs in hand, maybe you can help me understand what's happening.

Redacted for clarity:
```
nginx-ingress-controller 0.0.0.0 - [0.0.0.0] - - [15/Mar/2021:08:56:50 +0000] "GET /v1/categories HTTP/2.0" 502 565 "Referrer...." "User agent..." 360 40.004 [service-name] [] 192.168.92.152:8080, 192.168.92.152:8080, 192.168.92.152:8080 0, 0, 0 20.004, 20.000, 0.000 503, 503, 502 d701be9a1bb74941036ee80aab8085d5
```
What you can see here is a line of my ingress retrying 3 times a request, the relevant part from the log line is at the end:

```
20.004, 20.000, 0.000 503, 503, 502
```

this are the 3 response times from the three retries, then the three status codes from each retry.

The first two failures are because all workers are busy and `allocateTimeout` was reached (20 seconds in my config, with `internalErrorCode: 503`), the last response was a `502` and was an immediate response, I know for sure nothing in my code returns a 502 so it may be originating somewhere inside roadrunner, I tried to look for it but searching for 502 or gateway did not throw any results.

**Comment by 48d90782** [comment]
@hugochinchilla Hey. Is that possible to provide steps to reproduce this behavior? Because RR doesn't send 502 error code until it set in the config as the `internal_error_code`: https://github.com/spiral/roadrunner/blob/v1.9.2/service/http/handler.go#L69:2

**Comment by hugochinchilla** [comment]
I don't know how to reproduce it, I'm starting to suspect it may be generated from nginx side, but as far as I know the response status logged at the end of the line is the response from the upstream server. If you know for sure that RR does not respond with a 502 in any case, and I know for sure neither does my app, it may be some obscure corner case inside nginx which causes the problem.

The issue I'm having is that my app is heavily IO bound, mainly a proxy API to a legacy application, when the legacy application takes too much time to respond under heavy load the RR workers get saturated and I start to see many 503 errors (due to internal_error_code) caused by the `allocateTimeout`, under such circumstances the ingress retries the request with other pods before giving up, if all the pods where unavailable, nginx would reply with as 502 because not having available upstream servers.

In the specific case I showed, the ingress retied 3 times with the same pod, (maybe the others where unavailable, or just bad luck in the rotation algorithm, assuming is random instead of round robing). If that pod was saturated, I would expect 3 times to get a 503 error, but having 2 times a 503 and then a 502 is something I can't explain.

**Comment by 48d90782** [comment]
I can give you the advice to use `Wireshark` to track the network connection and find a place where this code arrived. Also, you can use `tcpdump` as a little bit low-level solution. Because 502 Bad Gateway not related to the RR, because it's HTTP service working as a proxy between a worker and a browser (for example) and hasn't own error codes except for the internal errors which are equal to `500` by default.

**Comment by 48d90782** [comment]
Also, for the server without GUI you can use `tshark` as a terminal clone of the `Wireshark` (or tcpdump).

**Comment by hugochinchilla** [comment]
I'm not sure how could I use this inside a kubernetes cluster to dump network info because of the SDN, but I will talk to the sysadmin team, maybe they can help me put tools in place to make this easier, I know [itsio](https://istio.io/) has tools with this kind of situations in mind.

**Comment by hugochinchilla** [comment]
I think the problem I have is something to ask in stack exchange as it's very niche. I will put it here just for context, maybe will be useful for someone later.

* I have a deployment in kubernetes with 2 replicas
* One service to expose the nodes trough DNS discovery
* nginx ingress controller queries the individual pods behind the service to build an upstream list
* A readiness probe checks the RR builtin healthcheck to detect when a pod has no available workers and temporarily remove it from the upstreams list.
* If the upstreams lists gets empty because all pods are failing the readiness probe nginx will respond with a 502 because there is no upstreams available.
* The RR internal healthcheck is failing to detect when no available workers (I will test 2.0 before opening a bug for this one) so I know for sure this is not the cause for the 502 I'm seeing.
* Nginx ingress will retry failed request up to three times trying different upstream servers if possible (in the trace I showed it the same pod three times).
* Each retry adds to the logs the IP of the upstream server, the response size, the response status (by the upstream) and the response time.
* The log file indicates 3 responses: 503, 503, 502
* For what I know about nginx this 502 should represent the status code returned by RR, but doesn't seem to come from there.

As I said, this is probably too niche for being asked here, but I wanted to post it anyway for the sake of being helpful to other people investigating similar issues, I will post this on stack exchange later.

If you are curious about my findings when testing the internal healthcheck while load testing I can open a ticket anyway before testing it in 2.0.

**Comment by 48d90782** [comment]
Thank you very much for the detailed explanation.
As I see, you are using the internal RR1 healthcheck endpoint. This endpoint has its own HTTP server inside which sends 500 status if there are no alive workers in the pool (https://github.com/spiral/roadrunner/blob/v1.9.2/service/health/service.go#L87).
> The RR internal healthcheck is failing to detect when no available workers

1. You mean, that RR1 healthcheck failed itself by some reason?
2. I guess (I might be wrong), but golang `http.Server` in the RR1 HTTP service might return that code bypassing the RR1 logs. In the RR2 we override golang `http.Server` internal logger to see the messages in the RR2 logs.

**Comment by hugochinchilla** [comment]
- I created a test endpoint which sleeps for 2 seconds and then responds with a 200 status.
- I serve the controller with RR using 4 workers and 20 secs allocateTimeout
- I monitor the workers status with `rr http:workers -i`
- I use bombardier to generate 100 concurrent requests for 10 seconds

While I can see all workers busy and bombarider receiving 503 errors because RR can't allocate workers I still get a 200 response from the healthcheck endpoint.

**Comment by 48d90782** [comment]
Thus when the RR checks the worker state, this is not related to the actual load made by the external load-testing tool except all the workers fall in the error state.

**Comment by hugochinchilla** [comment]
Well, that explains it. I will request the feature then. It would be very useful to have this to use with the readinessProbe in kubernetes.

**Comment by 48d90782** [comment]
There is one problem with a such request. Imagine the following situation:
1. You made a request to the healthcheck (HC) endpoint.
2. HC endpoint return 200OK, because there is at least 1 worker in the state `Ready` at this particular moment.
3. Based on this information you are trying to send a request, but receive a 503 (for example) response. 

How is this possible?
Between p2 and p3 other user made a request and allocate a worker which was previously free. So, your information is outdated because healthcheck can't guarantee, that after you receive a response, workers will still be available.

**Comment by hugochinchilla** [comment]
Yeah, I know it's not perfect, but it's a best effort to handle heavy loads with limited resources, when this happens ingress will retry against other RR isntance, the problem with retries is that you have to wait up to allocateTimeout before you know you need to retry.

With this mechanism you can proactively try to detect this situations and stop sending new traffic to the instance, waiting for it to become responsive again before adding to the instance pool. Note that a readinessProbe is not the same as a livenessProbe.

```
          readinessProbe:
            httpGet:
              path: /
              port: 2114
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 1
            timeoutSeconds: 1
```

With a configuration like this I can detect within 3 seconds I have an instance struggling to keep up with demand, and offload it, the cluster can also react to this creating more instances handle the increased load. During a brief time some clients will experience degraded performance because they have to wait until the first instance of RR returns an internal error before the nginx ingress controller can retry against other instance, but after 3 seconds the cluster will start taking measures to counteract this situation.

For me the biggest benefit of RR is how well it integrates with the docker idiosyncrasy, a single container being able to serve static content and execute php scripts in an efficient manner with native support for prometheus reporting, RR is a great tool, having the ability to know when it's struggling with load will make it even better.

**Comment by 48d90782** [comment]
Thank you 😄 
I completely understand what are you trying to achieve. Could you please then create an RFC with the proposal on the behavior of the `healthcheck` endpoint? Please, keep in mind, that at the moment we support the RR1 version only for security issues and some destructive bugs.
