### ISSUE TITLE
Is Laravel Supported?

### ISSUE THREAD

**Issue by uwascan** [spiral/roadrunner#60]
Can this be used to host a Laravel 5.7 web app?

**Comment by wolfy-j** [comment]
Yes, try this article 
https://www.ctolib.com/amp/topics-132962.html

**Comment by wolfy-j** [comment]
@uwascan please let me know if you can verify this approach. I would update Wiki then.

**Comment by Alex-Bond** [comment]
@wolfy-j i tested and it works with one fix:
`composer require spiral/roadrunner symfony/psr-http-message-bridge`
Zend Lib conflicts and not required.

Actual psr-worker.php fine:
```
<?php

require __DIR__ . "/vendor/autoload.php";

use Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory;
use Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory;

$relay = new Spiral\Goridge\StreamRelay(STDIN, STDOUT);
$psr7 = new Spiral\RoadRunner\PSR7Client(new Spiral\RoadRunner\Worker($relay));

$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

while ($req = $psr7->acceptRequest()) {
    try {
        $httpFoundationFactory = new HttpFoundationFactory();
        $request = Illuminate\Http\Request::createFromBase($httpFoundationFactory->createRequest($req));

        $response = $kernel->handle($request);

        $psr7factory = new DiactorosFactory();
        $psr7response = $psr7factory->createResponse($response);
        $psr7->respond($psr7response);
    } catch (\Throwable $e) {
        $psr7->getWorker()->error((string)$e);
    }
}
```

**Comment by wolfy-j** [comment]
Most likely cos Laravel have heavier bootload than SF, heaver bootload => more performance gain you can get using RoadRunner.

I'm adding this details to Wiki.

**Comment by wolfy-j** [comment]
https://github.com/spiral/roadrunner/wiki/Laravel-Framework

**Comment by wolfy-j** [comment]
@Alex-Bond can you clarify `Zend Lib conflicts and not required.`? I would like to solve this issue as well.

**Comment by MohamedPHP** [comment]
Hello Dears,

I've an issue regarding the Laravel installation,

I followed the steps, but there is no request body being sent to laravel app for POST, PUT ... etc

Any recommendation ?

**Comment by wolfy-j** [comment]
Are you transferring data over JSON?

**Comment by alash3al** [comment]
Body data lose is here too, and yeah, I'm transferring json encoded data

**Comment by Alex-Bond** [comment]
@alash3al @MohamedPHP can you lett Laravel version? I did additional tests and in all tests, I receive data (Laravel 5.7).

**Comment by Alex-Bond** [comment]
Updated worker file to 5.7 (looks like they changed bootstrap sequence in last versions)
```php
<?php

require __DIR__ . "/vendor/autoload.php";

use Symfony\Bridge\PsrHttpMessage\Factory\DiactorosFactory;
use Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory;

$relay = new Spiral\Goridge\StreamRelay(STDIN, STDOUT);
$psr7 = new Spiral\RoadRunner\PSR7Client(new Spiral\RoadRunner\Worker($relay));

$app = require_once __DIR__ . '/bootstrap/app.php';

while ($req = $psr7->acceptRequest()) {
    try {
        $httpFoundationFactory = new HttpFoundationFactory();
        $request = Illuminate\Http\Request::createFromBase($httpFoundationFactory->createRequest($req));

        $kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

        $response = $kernel->handle(
            $request = $request
        );

        $psr7factory = new DiactorosFactory();
        $psr7response = $psr7factory->createResponse($response);
        $psr7->respond($psr7response);

        $kernel->terminate($request, $response);
    } catch (\Throwable $e) {
        $psr7->getWorker()->error((string)$e);
    }
}

```

**Comment by Alex-Bond** [comment]
When i was working on Yii integration i found an interesting thing - Yii doesn't see body if i don't rewind body object before passing to it.
@alash3al  @MohamedPHP  can you try to call `$req->getBody()->rewind();` after `try {`?

**Comment by Alex-Bond** [comment]
@tectiv3 can you send em version of Laravel with Example or request and expected response? I need a little more debug info.

**Comment by tectiv3** [comment]
```
POST /api/users/login HTTP/1.1
Host: localhost:8000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:8080/signin
Content-Type: application/json;charset=utf-8
Content-Length: 70
Origin: http://localhost:8080
DNT: 1
Connection: keep-alive
```
```
{"user":{"email":"user@local","password":"password","language":"en"}}
```
well, currently response is - `missing required data`, cause request data is empty.
And laravel version is `5.7.20`

**Comment by Alex-Bond** [comment]
Good news - i found the problem. Laravel removing headers. Investigating reason.
