### ISSUE TITLE
[RFC, RR2] RedinessProbe oriented health check

### ISSUE THREAD

**Issue by hugochinchilla** [spiral/roadrunner#601]
Current health check passes if there is at least one worker ready or running, this is good to know the application is not in a broken state, however when we have a pool of many servers running roadrunner and a load balancer it would be handy to have another supported mode of operation for the health check, in such mode the health check would only pass if at least one worker is ready to accept new connections and fail if all workers are busy.

### Limitations

The usefulness of this health check is limited, quoting @48d90782 on #595 :

> There is one problem with a such request. Imagine the following situation:
> 
> 1. You made a request to the healthcheck (HC) endpoint.
> 2. HC endpoint return 200OK, because there is at least 1 worker in the state `Ready` at this particular moment.
> 3. Based on this information you are trying to send a request, but receive a 503 (for example) response.
> 
> How is this possible?
> Between p2 and p3 other user made a request and allocate a worker which was previously free. So, your information is outdated because healthcheck can't guarantee, that after you receive a response, workers will still be available.

### Why then?

Some times an application may behave in a way that all workers get stuck on some long running processes, this is not an ideal situation and can cause a bad user experience. When roadrunner has all of it's workers busy a new request will wait an amount of time for a worker to be allocated (defined by `allocateTimeout`), if no worker can attend the request in that time, an error is returned. You can instruct your load balancer to retry the request with another roadrunner instance. In such cases the request may succeed in the end, but the user has experienced a very long time for the request to be answered. If we can detect when a node is busy and stop sending traffic to it until the health check passes again we will be providing a better user experience because we can proactively reduce the number of request that need to fail before being retried by skipping the bad node in the first place.

You can read the [original comment](https://github.com/spiral/roadrunner/issues/595#issuecomment-800261284) where this idea was discussed.

**Comment by 48d90782** [comment]
Thanks for the request @hugochinchilla. I've been thinking since our last discussion about that case. In the RR2 I'll add an additional mode for the workers to return only workers, which are in the `Ready` state. At the moment, we have a query like that `health?plugin=plugin1&plugin=plugin2` to check the state (`Ready` + `Working`), I'll add an additional endpoint `/health/ready?plugin=http&plugin=plugin2`. Is that something that helps you?

**Comment by hugochinchilla** [comment]
Yes, that would work for me! Thanks for being so open to new ideas :)

**Comment by 48d90782** [comment]
@hugochinchilla You are open :) Planned for the 2021-04-06 SPRINT

**Comment by hugochinchilla** [comment]
Amazing work, thank you!

**Comment by 48d90782** [comment]
@hugochinchilla Thanks 👍🏻 You can now update to the v2.0.4 and try this feature. Will be glad to hear your feedback.

**Comment by hugochinchilla** [comment]
Thanks!, I will need some time before putting 2.x in production, I started testing it today and found some issues, probably my fault, I will need more time to test it. I will keep you updated.

**Comment by hugochinchilla** [comment]
Hi @rustatian, sorry for all this time without any feedback, I left the company in which I was working and I'm no longer developing any php application so I can't provide the feedback you requested. At some point I will have an opportunitty to do so, I'm sorry I didn't have the opportunity to try this after all the noise I made requesting it :sweat:. As always, thank you for your work it was awesome to use this application and collaborate with you.

**Comment by rustatian** [comment]
Hey @hugochinchilla. Sad to hear that 😞 . Thank you very much for your work on the RoadRunner. It was a pleasure working with you. You are awesome; good luck to you man 👍🏻 
Feel free to join my twitch streams about GO and Rust development 😃

**Comment by hugochinchilla** [comment]
Hey @rustatian I can't find your twitch channel. Can you link it here?

**Comment by wolfy-j** [comment]
You can find twitch announcements here - https://discord.gg/fngxpTmB

**Comment by rustatian** [comment]
> Hey @rustatian I can't find your twitch channel. Can you link it here?

`https://www.twitch.tv/rustatian`
