### ISSUE TITLE
[FEATURE REQUEST] Create new counter for internal errors

### ISSUE THREAD

**Issue by hugochinchilla** [spiral/roadrunner#607]
This issue is derived from #602 

It would be nice to have a separate counter for internal errors as the only way available now is to look into `rr_http_request_total{status="500"}` and you can't tell which errors are from your application and which ones are from road runner itself.

Also if `internalErrorCode` is set it should be used to increment `rr_http_request_total` with that code instead of incrementing always with 500.

**Comment by rustatian** [comment]
Fixed for the RR2.
