### ISSUE TITLE
Need a way to update wiki using MD docs

### ISSUE THREAD

**Issue by wolfy-j** [spiral/roadrunner#63]
Updating GitHub wiki is pretty painful now. Need an app which can sync wiki content and some specific repo content where people can push their PR into.

**Comment by wolfy-j** [comment]
Similar to https://github.com/palantir/godel/wiki/GitHub-wiki

**Comment by Alex-Bond** [comment]
@wolfy-j maybe move docs to separate service and save only md files in repo?
