### ISSUE TITLE
[FEATURE REQUEST, RR2] AWS Lambda Documentation

### ISSUE THREAD

**Issue by rockfreak** [spiral/roadrunner#630]
In V1 you had a guide for deploying on aws lambda https://github.com/spiral/roadrunner-docs/blob/1.0/library/aws-lambda.md

On the features section of the roadrunner.dev site it says that AWS Lambda is supported.

It would be great to have some examples on such a setup on v2.

**Comment by 48d90782** [comment]
@rockfreak Hello, good point. We will update our documentation, thanks.

**Comment by 48d90782** [comment]
@rockfreak https://github.com/spiral/roadrunner-docs/pull/57
This is not tested yet, but, should work :)
