### ISSUE TITLE
How to run wordpress with this server?

### ISSUE THREAD

**Issue by Gelembjuk** [spiral/roadrunner#64]
This software looks very interesting and promising.
However, i didn't find some dock that explains how to use it with php apps .

For example, if i want to run wordpress with it. What should i do?
As i understand, i have to create a worker. But it is not clean what should be in that worker. Just require("wordpress/index.php")  ?

Also, as i understand PHP must be installed separately. It is not part of this code. What are requirements for PHP intallation?
What are requirements fro PHP on different platforms?

My aim is to understand  if i can use this tool to make a desktop version of my PHP application. I want to make installation package with my PHP code, some web server and PHP itself

**Comment by Alex-Bond** [comment]
Hey!

I don't think its possible to run WP behind RR. You need PSR7 compatible system.

About PHP installation - it can be any PHP version. As long as it runs from the console.

**Comment by nvtv15** [comment]
Wordpress works with mysql ok. There is a lot of plugin for example,woocommerce or other similar ( mycred  https://wordpress.org/plugins/mycred/  )  plugin saves transactions in mysql. Is it possible to use part with this db, that tables carrying transactions from mysql partly go into blockchain?

**Comment by wolfy-j** [comment]
If you are talking about Golang to PHP SDK to communicate with blockchain - yes, it is possible.

**Comment by nvtv15** [comment]
> If you are talking about Golang to PHP SDK to communicate with blockchain - yes, it is possible.
My site galonet.eu/wallet. It's a little harder to sign in because I put in double e-mail because of spammers. When you first sign up you get 8000 dolars, there are options to send to another user. I'd like to put that transaction in the blockchain.

**Comment by wolfy-j** [comment]
You can implement it using Golang SDK, there are examples in roadrunner docs how to create your own service.

**Comment by lkraav** [comment]
> I don't think its possible to run WP behind RR. You need PSR7 compatible system.

...

> Wordpress works with mysql ok.

I'm confused - RR does or does not require a strictly PSR7-compatible app, or can you run any PHP script with it?

**Comment by wolfy-j** [comment]
RoadRunner is not only a web server but an application server. This means you can move some of your functionality to golang and still serve the app using the classing PHP-FPM method. 

In this case, it makes sense to move Blockchain communication methods to Golang.

On another end, RoadRunner does not require PSR-7 (you can use low-level HTTP protocol instead).
But it does require your application to be capable of running in stateless mode. Unfortunately, WordPress did everything it can to build architecture incapable of running in stateless mode.

**Comment by lkraav** [comment]
> Unfortunately, WordPress did everything it can to build architecture incapable of running in stateless mode.

I am not sure I understand. WP's only "state" mechanism is cookies. It doesn't use sessions, or anything else. How is this "incapable of running in stateless mode" claim determined?

**Comment by wolfy-j** [comment]
You are not able to pass more than one request through the WP. Since WP treats the request as a global instance it will cache its values inside the config and other functions. This makes impossible to reuse already initiated application. This is caused by the fact that WP does not use any request/response abstraction.

**Comment by connerbw** [comment]
Someone got it running under Swoole. 
README in `Wordpress-PSR/swoole` explains ideas that could (maybe) work for Roadrunner.
Non-trivial, experimental.

- https://github.com/WordPress-PSR/request-handler/
- https://github.com/Wordpress-PSR/swoole

**Comment by rustatian** [comment]
Closing due to the https://github.com/spiral/roadrunner/issues/64#issuecomment-586931926.

**Comment by itorz7** [comment]
Is it available now ??

**Comment by rustatian** [comment]
> Is it available now ??

No, see comments above.

**Comment by rustatian** [comment]
> Is it available now ??

No, see comments above.
