### ISSUE TITLE
[RFC] Scan `server.command` for the possible path to the PHP/script/binary file

### ISSUE THREAD

**Issue by rustatian** [spiral/roadrunner#658]
Currently, error handling when the wrong path is provided in the `server.command` is terrible and leads to a bad UX. Consider the following approach:
1. Scan the `command` and try to find the `*.php` pattern to treat it as a path.
2. If the path is found, try to stat it, and in case of a wrong path provided, print a user-friendly message.
3. Because it is heuristic, do not panic on the wrong path; print a message.
4. We could apply the same way of handling other patterns like `.sh` or `.ps`.

**Comment by treadmillian** [comment]
Can you confirm if this is why I see this error?

`scan command {"error": "server_command_scan: scan failed, possible path not found"}`

**Comment by rustatian** [comment]
> Can you confirm if this is why I see this error?
> 
> `scan command {"error": "server_command_scan: scan failed, possible path not found"}`

Yep, but actually, this is an `info` level message: 
https://github.com/spiral/roadrunner/blob/master/plugins/server/plugin.go#L100
Could you please show the command you use? I'll try to improve the scanner.

**Comment by mmalessa** [comment]
Hi!
I have the same problem.
Command: `php bin/console baldinof:roadrunner:worker` - baldinof/roadrunner-bundle
Temporary workaround: `cp ./bin/console ./bin/console.php` ..but that shouldn't be the target solution ;-)
Regards!

**Comment by rustatian** [comment]
> Hi!
> I have the same problem.
> Command: `php bin/console baldinof:roadrunner:worker` - baldinof/roadrunner-bundle
> Temporary workaround: `cp ./bin/console ./bin/console.php` ..but that shouldn't be the target solution ;-)
> Regards!

This is not an issue, I mean, the message `scan command {"error": "server_command_scan: scan failed, possible path not found"}` only notify the user, about the scan result. If a possible path will be found and `stat` syscall will be unsuccessful, it will point you to the problem with the path to the script/worker.
But, I see that this solution raises questions, I'll try to improve it, thanks for the report.
