### ISSUE TITLE
[FEATURE REQUEST] Overriding default error page

### ISSUE THREAD

**Issue by shyim** [spiral/roadrunner#659]
**Is your feature request related to a problem? Please describe.**
If an error happens I see as a client the error. This should be only shown in the development environment

**Describe the solution you'd like**

Idk something like Internal Server Error like in Apache / Nginx

**Describe alternatives you've considered**
I am unsure that's possible to catch 

![image](https://user-images.githubusercontent.com/6224096/117041060-d7660e00-ad0a-11eb-8c7a-b8c6ec53be18.png)

**Additional context**

**Comment by 48d90782** [comment]
Hey @shyim. Yep, we did such override in the RR1 by separating RR errors and application errors. I agree with you. I will plan this update for the next sprint.

**Comment by 48d90782** [comment]
ref: https://github.com/spiral/roadrunner/discussions/689
