### ISSUE TITLE
No UserAgent set in $_SERVER when using PSR7Client

### ISSUE THREAD

**Issue by agentd00nut** [spiral/roadrunner#66]
If you dump the contents of the `$ctx` and `$_SERVER` right before `$this->configureServer($ctx)` during ` acceptRequest() ` in `PSR7Client.php` to different files, you'll see that the context contains a "User-Agent" in its headers but its not yet set in the `$_SERVER`, which is fine.

However `configureServer` does not attempt to set the User_Agent and does not appear to set it anywhere else.

Adding 

```
if(isset($ctx['headers']['User-Agent']))
            $server['HTTP_USER_AGENT'] = $ctx['headers']['User-Agent'][0];
``` 

to `configureServer` in the `PSR7Client.php` file fixes this issue.

**Comment by wolfy-j** [comment]
If you can provide the PR and test for that I would appreciate it, if not I will allocate a bit of time later.

**Comment by wolfy-j** [comment]
See release 1.27
