### ISSUE TITLE
[BUG, RR2] Makefile is broken

### ISSUE THREAD

**Issue by eldario** [spiral/roadrunner#668]
Hi!

> Thanks for `RR v2`.

I cannot understand if this is a **bug** or if something is not working for me.

I tried this code:

```sh
$ make build
```
I expected to see this happen: `build successfull`

Instead, this happened: 
```sh
CGO_ENABLED=0 go build -trimpath -ldflags "-s" -o ./rr ./cmd/main.go
stat /proj/spiral/roadrunner/cmd/main.go: directory not found
Makefile:15: recipe for target 'build' failed
make: *** [build] Error 1
```

I do not see the `cmd` directory

thanx a lot.

**Comment by 48d90782** [comment]
Hey @eldario. Use rr-binary (https://github.com/spiral/roadrunner-binary) to build the RR. This repo is not buildable. I'll remove this target, thanks :)

**Comment by eldario** [comment]
Thanx a lot
