### ISSUE TITLE
Unsupported HTTP protocol version "2.0" 

### ISSUE THREAD

**Issue by bognerf** [spiral/roadrunner#67]
I recently upgraded from RoadRunner 1.2.4 to the currently latest version 1.2.6, including upgrading composer requirements to `"spiral/roadrunner": "1.2.6"`

Since 1.2.5 `src/PSR7Client.php` uses `withProtocolVersion(substr($ctx['protocol'], 5))` (Line 87) 

Unfortunately this results - if RoadRunner's https-Support is active - in a string `2.0` which won't validate against zend-diactoros (v.1.8.6) `MessageTrait::validateProtocolVersion($version)`

```php
[...]
  // HTTP/1 uses a "<major>.<minor>" numbering scheme to indicate
        // versions of the protocol, while HTTP/2 does not.
        if (! preg_match('#^(1\.[01]|2)$#', $version)) {
            throw new InvalidArgumentException(sprintf(
                'Unsupported HTTP protocol version "%s" provided',
                $version
            ));
        }
[...]
```
which only accepts *1.0*, *1.1* and **2**.

```

Fatal error: Uncaught InvalidArgumentException: Unsupported HTTP protocol version "2.0" provided in /home/bof09595/PhpstormProjects/rr/vendor/zendframework/zend-diactoros/src/MessageTrait.php on line 371

InvalidArgumentException: Unsupported HTTP protocol version "2.0" provided in /home/bof09595/PhpstormProjects/rr/vendor/zendframework/zend-diactoros/src/MessageTrait.php on line 371

Call Stack:
    0.0002     395832   1. {main}() /home/bof09595/PhpstormProjects/rr/psr-worker.php:0
    0.0110     583008   2. Spiral\RoadRunner\PSR7Client->acceptRequest() /home/bof09595/PhpstormProjects/rr/psr-worker.php:18
    2.2204     759960   3. Zend\Diactoros\ServerRequest->withProtocolVersion() /home/bof09595/PhpstormProjects/rr/vendor/spiral/roadrunner/src/PSR7Client.php:87
    2.2204     759960   4. Zend\Diactoros\ServerRequest->validateProtocolVersion() /home/bof09595/PhpstormProjects/rr/vendor/zendframework/zend-diactoros/src/MessageTrait.php:84
```

This behavior renders **https** support useless for the moment.

**Comment by wolfy-j** [comment]
Did you update the binaries as well? I believe this error has been addressed on Golang end. Let me double check.

**Comment by wolfy-j** [comment]
Anyway, I think the PHP fix is good improvement. I will make a release this week, let me know if you need it sooner.

**Comment by bognerf** [comment]
The sooner, the better, but I won't push pressure on you. Thanks for this very cool piece of software, btw.

I'm glad I could be of service to the project, even only with the tiniest of contributions!

**Comment by wolfy-j** [comment]
Check the release **1.2.7**
