### ISSUE TITLE
[BUG] rr workers not working in Laravel Octane

### ISSUE THREAD

**Issue by litan1106** [spiral/roadrunner#686]
I tried the rr command with Laravel Octane

###rr reset
```
rr reset -o rpc.listen=tcp://localhost:6001
```
expected result
Resetting plugin: [http] ∙∙●

###rr workers
```
rr workers -o rpc.listen=tcp://localhost:6001
```
expected result
workers table

instead I got an error
show_workers: informer_plugin_workers: no such service: server; informer_plugin_workers: no such service: server

The version of RR used: rr version 2.2.1 (build time: 2021-05-13T18:00:32+0000, go1.16.4)

Discussion
https://github.com/spiral/roadrunner/discussions/684

pinged @48d90782

**Comment by 48d90782** [comment]
TODO: 
1. `Informer.List` after the #611 returned all available plugins, but not plugins, which fit the `Informer` interface.
2. Create a new RPC call: `Informer.Workers`, which should return plugins with workers.
3. Update rr-binary `informerList` constant.

**Comment by litan1106** [comment]
@rustatian thanks for the quick fixed. it worked in v2.3.0-beta.2
```
rr workers -o rpc.listen=tcp://localhost:6001
```
