### ISSUE TITLE
Wrong build.sh file permissions

### ISSUE THREAD

**Issue by mrsuh** [spiral/roadrunner#69]
File has changed permissions
https://github.com/spiral/roadrunner/commit/ea60c3e1eba96cd140e4c89b710de3a98f523f43#diff-0b83f9dedf40d7356e5ca147a077acb4

build.sh 100755 → 100644

And now its error
```
make
make: ./build.sh: Permission denied
make: *** [all] Error 1
```

**Comment by mrsuh** [comment]
https://github.com/spiral/roadrunner/pull/70

**Comment by wolfy-j** [comment]
Thank you.
