### ISSUE TITLE
[BUG, NEED VERIFICATION] $worker->getWorker()->error((string)$e); cause a force kill and lost error msg

### ISSUE THREAD

**Issue by drefixs** [spiral/roadrunner#691]
When I created my own worker process and use the code example for the push error to the rr server for workers

```
    } catch (\Throwable $e) {
        $worker->getWorker()->error((string)$e);
    }
```

I don't see my original error only the next errors:
```
2021-05-26T16:35:46.711+0300    DEBUG   server          server/plugin.go:225    worker destructed       {"pid": 24906}
2021-05-26T16:35:46.725+0300    ERROR   server          server/plugin.go:238    worker_watcher_wait: signal: killed; process_wait: signal: killed
github.com/spiral/roadrunner/v2/plugins/server.(*Plugin).collectEvents
        github.com/spiral/roadrunner/v2@v2.2.1/plugins/server/plugin.go:238
github.com/spiral/roadrunner/v2/pkg/events.(*HandlerImpl).Push
        github.com/spiral/roadrunner/v2@v2.2.1/pkg/events/general.go:37
github.com/spiral/roadrunner/v2/pkg/worker_watcher.(*workerWatcher).wait
        github.com/spiral/roadrunner/v2@v2.2.1/pkg/worker_watcher/worker_watcher.go:235
github.com/spiral/roadrunner/v2/pkg/worker_watcher.(*workerWatcher).addToWatch.func1
        github.com/spiral/roadrunner/v2@v2.2.1/pkg/worker_watcher/worker_watcher.go:260
2021-05-26T16:35:47.278+0300    DEBUG   server          server/plugin.go:223    worker constructed      {"pid": 24965}
```

I expected to see my (string)$e in the rr logs

Instead, i see that worker process was force killed

I create a simple fix for my issue: #690

**Comment by 48d90782** [comment]
Hey @drefixs. Thanks for the report. Could you please send the whole `.rr.yaml` you used and the PHP (your) worker sample to reproduce your problem?

**Comment by drefixs** [comment]
Hi @48d90782 thanks for the quick responce:

1.
```
server:
   command: "php bin/console baldinof:roadrunner:worker"

http:
  address: 0.0.0.0:80
  middleware: [ "static", "gzip" ]
  pool:
    num_workers: 4
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "web"
    forbid: [ ".php", ".htaccess" ]

logs:
  mode: production
  encoding: console
  channels:
    http:
      mode: production
      level: debug
      encoding: console
      output: stdout
      err_output: stderr

rpc:
  listen: tcp://127.0.0.1:6001
```
Also I noticed that if you change http.pool.debug=true it starts to work normally without force killing the process with log


2. OSX(Darwin)(x86) and Docker Alpine linux (x86) on server

**Comment by drefixs** [comment]
May be i found the reason 
https://github.com/spiral/roadrunner/blob/master/pkg/pool/static_pool.go#L267
this part of the code first in the else condition try to do sp.ww.Push(w) for the process that send frame ERROR

after that it try again to do graceful termination with w.Stop()

**Comment by 48d90782** [comment]
First of all, please, provide a worker you used and full steps on how to reproduce this issue. I'll definitely take into account your investigation, thanks 👍🏻

**Comment by 48d90782** [comment]
@drefixs Am I right, that you are expecting to see smt like this in the logs output?:
![image](https://user-images.githubusercontent.com/8040338/120614019-75aad800-c45f-11eb-9079-898e8a6d9477.png)

**Comment by 48d90782** [comment]
Or, I guess, that would be better to see smt like this (without RR specific error wrapping):
![image](https://user-images.githubusercontent.com/8040338/120615281-c7079700-c460-11eb-820f-6f724a6f092b.png)

**Comment by 48d90782** [comment]
Fixed, will be as on the second screenshot.
