### ISSUE TITLE
[FEATURE REQUEST] Can roadrunner work with other languages?

### ISSUE THREAD

**Issue by easysoft** [spiral/roadrunner#696]
Hello,

Can roadrunner work with other languages a the same time? We developped an system mainly in PHP and our customer want to customize it by other language for example Java.

So is it possiable to combined PHP and Java at the same time by roadrunner?

Thanks a lot.

**Comment by 48d90782** [comment]
Hey @easysoft. That's a great question. Sure, RR can work with other languages redirecting HTTP, RPC, etc., requests to your JAVA application. I'll show that on todays' Twitch stream )
