### ISSUE TITLE
[RR2, Beta] Question regarding flatbuffers in websockets

### ISSUE THREAD

**Issue by MaximilianKresse** [spiral/roadrunner#708]
I'm relativly new to roadrunner and wanted to test the reimplemented websockets feature in the 2.3-beta version.

My problem is with sending informations from the php workers to the websockets.

If I figured it out correctly how it can be used I have to go over RPC:
```
$rpc->call('websockets.PublishAsync', $payload)
```

My main problem is the $payload. The $payload here should be a Flatbuffers Messages structure. But how can I generate Flatbuffers in PHP? I've tried to use the official PHP implementation but this just seems to be dead - [as there is no maintainer](https://github.com/google/flatbuffers/issues/6684#issuecomment-856076838).

**Comment by wolfy-j** [comment]
We are planning to release an SDK till the end of this week. Don't worry, we do not like torturing our users. 

But if you want to read more about flatbuffers - https://google.github.io/flatbuffers/

You have to compile a message based on provided schema - https://github.com/spiral/roadrunner/blob/master/pkg/pubsub/message.fbs

**Comment by wolfy-j** [comment]
We will have to check the PHP version of FlatBuffers library...

**Comment by rustatian** [comment]
@MaximilianKresse We have switched to the `protobuf`.
#712
