### ISSUE TITLE
[KV, WEBSOCKETS] Switch from the `flatbuffers` to the `protobuf`

### ISSUE THREAD

**Issue by rustatian** [spiral/roadrunner#711]
Unfortunately, `flatbuffers` port for the PHP programming language is quite unpopular and unmaintained for the last 3 years. Dealing with `flatbuffers` for the PHP we de-facto should also start to maintain the PHP part of the `flatbuffers` which is quite costly for us in terms of developer resources.
- Move schema from the flatbuffers format to the proto-format.
- Update KV, WS implementations from the FB -> Proto.

**Comment by rauanmayemir** [comment]
I generally like the idea considering I already use protobuf.

But I feel like it might become an even bigger burden especially since protobuf and grpc versioning is a mess and we might end up being stuck with a certain version of an outdated protoc because roadrunner is not upgraded to support newer one.

Have you considered something else, like msgpack or cbor?

**Comment by rustatian** [comment]
> I generally like the idea considering I already use protobuf.
> 
> But I feel like it might become an even bigger burden especially since protobuf and grpc versioning is a mess and we might end up being stuck with a certain version of an outdated protoc because roadrunner is not upgraded to support newer one.
> 
> Have you considered something else, like msgpack or cbor?

RR will always be using the most recent stable version, no worries 😃 
msgpack or cbor are much slower than protobuf. Protobuf schema supports a lot of features to version it, like deprecated fields, package names (kv.v1, kv.v2 etc). I don't know, why do you think, that grpc and especially protobuf versioning is a mess)

Our old grpc plugin will be updated to the RR2 ecosystem and will support all new features.

**Comment by rustatian** [comment]
@rauanmayemir You can take a look at the `pkg/proto` to see how we version our proto schemes. A good description about our approach you may found here: https://github.com/uber/prototool/blob/dev/style/README.md
