### ISSUE TITLE
[Question] Debugging invalid buffer

### ISSUE THREAD

**Issue by grachevko** [spiral/roadrunner#72]
How to debug this error? `worker error: invalid data found in the buffer (possible echo)`

**Comment by wolfy-j** [comment]
Try to start your worker manually. This error is about invading data send to the pipe. 99% it’s about echo/header  in your code. :(

You can also connect to worker over Unix or TCP socket.

**Comment by wolfy-j** [comment]
Let me know if this helps or if I need to add more info into Wiki.

**Comment by grachevko** [comment]
This error shows only on specific pages (errors pages), i don't understand why i don't understand how to debug it. 
I don't see a real reason to change connect to socket for now.

**Comment by wolfy-j** [comment]
What is rendering these pages? There is a possibility that exception handler echoes or error_log points to STDOUT.

**Comment by grachevko** [comment]
This pages render our html with information for user. But this error i catch only on one project, but another project render his error pages correctly.

**Comment by grachevko** [comment]
@wolfy-j maybe should in debug mode print to stdout invalid data recieved from worker? 
Or another way to catch what worker return?

**Comment by wolfy-j** [comment]
@grachevko it's not that easy to capture error buffer content cos worker communication is streamed. I have to think about potential ideas using some temporary buffer and redirecting STDOUT to STDERR.

**Comment by grachevko** [comment]
@wolfy-j you mean redirect incorrect data to STDERR until receiving correct data?
Looks like good idea.

**Comment by grachevko** [comment]
I found my bug. *facepalm*

```php
monolog:
    handlers:
        stdout:
            type: stream
            path: "php://stdout"
            level: warning
```
