### ISSUE TITLE
[Discussion] Any other potential frameworks/libraries to use with

### ISSUE THREAD

**Issue by Alex-Bond** [spiral/roadrunner#75]
Hi everyone!

We already have Symfony and Laravel in wiki and Slim waiting for independent tests.
What about any other frameworks/libraries/CMS/CMF? Any success in connection RR to them?

**Comment by wolfy-j** [comment]
Zend Expressive works, Spiral supports it on kernel level in 2.0.

**Comment by FirestarterUA** [comment]
Alex, can you  show slim integration, please?
And nginx as frontend.

**Comment by FirestarterUA** [comment]
Can you show, how to use Roadrunner in Docker?

**Comment by Alex-Bond** [comment]
> Can you show, how to use Roadrunner in Docker?

Good idea. We should add RR to Docker Hub. Question is which version of PHP to use or how made it with all major versions.

**Comment by wolfy-j** [comment]
Well, the Docker installation is to trivial so Wiki page might be enough for now. We have used PHP 7.x Apline CLI, copied RR binary in it and made it and enter-point. That's it :)

**Comment by grachevko** [comment]
Docker image may sense this only for quick start guide, but as it also require install dependencies from composer i think image not make sense. Especial after solve https://github.com/spiral/roadrunner/issues/71

**Comment by wolfy-j** [comment]
Also, i found this https://github.com/n1215/roadrunner-docker-skeleton

**Comment by Alex-Bond** [comment]
> Also, i found this https://github.com/n1215/roadrunner-docker-skeleton

Here is my vision of it - https://gist.github.com/Alex-Bond/849156fae6ccc9d6b853b7132f8e5f0c
About debug - its possible, but in this case, it gonna require entry point and small Bash script with env/parameter checker.

**Comment by wolfy-j** [comment]
I would close this issue due being stalled (the rest of conversation can be moved to Discord). All of the links added here are moved into Wiki. The only framework which is missing from this list is Spiral and it will be added as separate section later.
