### ISSUE TITLE
[FEATURE REQUEST] Multi tenancy (multiple sites/projects)

### ISSUE THREAD

**Issue by binaryfire** [spiral/roadrunner#756]
Hi guys,

Is there any way to use a single instance of Roadrunner on a server with multiple Laravel projects (sites)? Each one will have a different domain / SSL cert. Perhaps in conjunction with an NGINX reverse proxy or something?

If not, I'd love to see a feature like this.

**Comment by rustatian** [comment]
Hey @binaryfire. Unfortunately, this is not possible at the time. I don't think, that this is even possible to implement via 1 RR instance. Because it can be easily solved by running multiply RR instances (bash script). Only 1 thing you'll need to maintain - RR configuration files.
