### ISSUE TITLE
[Feature Request] AccessLog

### ISSUE THREAD

**Issue by grachevko** [spiral/roadrunner#77]
RR not have enough features to be complete web server for now. 
The one of required is a access log.

My suggestions about access log feature:
 - included out of the box
 - configurable log format
 - support all fields of [Apache Combined Log Format](https://httpd.apache.org/docs/2.4/logs.html#combined)
 - support additional fields:
 - - Custom headers (for example to print custom request id to track in logs)
 - - The time taken to serve the request
 - - Node name (/etc/hostname)
 - - Environment variable
 - - Worker ID (UUID?)
 - - Worker execution count
 - - Worker execution time
 - - Worker memory usage

**Comment by wolfy-j** [comment]
Combined with #124

**Comment by 48d90782** [comment]
Merged with #124

**Comment by alexeyshockov** [comment]
So was it implemented or just closed? Both issues point one to another at the moment, both are closed, but looks like nothing was implemented.

**Comment by wolfy-j** [comment]
See #208
