### ISSUE TITLE
[Question] Is spiral/jobs deprecated?

### ISSUE THREAD

**Issue by fabis94** [spiral/roadrunner#786]
I can see that the `spiral/jobs` repo is archived: https://github.com/spiral/jobs

Does this mean that Jobs are no longer supported or maintained?

**Comment by rustatian** [comment]
Hey @fabis94 . https://github.com/spiral/jobs package works only with RR1. New RR2 contains an updated jobs plugin with all drivers supported by the old jobs. Thus, old https://github.com/spiral/jobs was deprecated in the flavor of new RR2 jobs.
