### ISSUE TITLE
[BUG] Please update Issue 798

### ISSUE THREAD

**Issue by stl-victor-sudakov** [spiral/roadrunner#800]
You were too quick to close it. We have worked out an equation of success for https://github.com/spiral/roadrunner/issues/798, can you please update it. Here is the equation:

`Conns/sec / num_workers * request_duration < allocation_time`

E.g. with the default allocation_time=60s and request duration=2.9s
`300/15*2.9=58`
these are the numbers which will still work without errors. 

https://github.com/spiral/roadrunner/issues/798

**Comment by rustatian** [comment]
I moved the ticket to the discussion. Please, put your comment to the discussion.

**Comment by rustatian** [comment]
https://github.com/spiral/roadrunner/discussions/799
