### ISSUE TITLE
[Feature Request] Watchers

### ISSUE THREAD

**Issue by grachevko** [spiral/roadrunner#81]
Watchers - jobs generating special request from RR to workers. 
This feature may useful for keep/close connection in workers, or many other custom jobs.

Suggestions:
 - Configure any counts of watchers
 - Worker must recieve information about watcher his called (to know whitch jobs to run)
 - 3 types of triggers
 - - Triggered once after specific idle time
 - - Triggered periodicaly by specific timer
 - - Triggered periodicaly by specific timer only in idle state

**Comment by wolfy-j** [comment]
I have an idea about that, i can create another service to watch any specif RR server (GRPC, Jobs or PSR) with ability to control workers.

**Comment by wolfy-j** [comment]
Available in 1.4.0, see sample config: 
https://github.com/spiral/roadrunner/blob/master/.rr.yaml#L65
