### ISSUE TITLE
[FEATURE REQUEST] print received frame with CRC error at the `debug` log level

### ISSUE THREAD

**Issue by rustatian** [spiral/roadrunner#829]
There are cases when some applications send debug data to the `stdout`. It's very hard to predict or even debug, who is sending this data having only `CRC validation error` output.
Would be good for the RR to allow debugging such output, so, the user will see particular output instead of a generic `CRC validation failed error`.
TODO:
1. Add debug logging to the worker's receive frame.
2. Limit the logging data ?? (up to 1mb ??).
3. Add option to skip invalid frame (can cause freezes, should be only in the methods with timeouts)???

**Comment by tezhm** [comment]
What options do I have for debugging this error? I am currently getting the following:

```
{"level":"error","ts":1636435566.565323,"logger":"server","msg":"sync_worker_exec_worker_with_timeout: Network:\n\tsync_worker_exec_payload:\n\tgoridge_frame_receive: CRC verification failed"}
{"level":"debug","ts":1636435566.5668693,"logger":"server","msg":"worker process exited","reason":"signal: killed; process_wait: signal: killed","reasonCauses":[{"error":"signal: killed"},{"error":"process_wait: signal: killed"}]}
```

**Comment by tezhm** [comment]
Ok, I've found what is happening locally for me - my php instance was throwing on an assertion and the stack trace was getting swallowed by the worker and not emitted out of roadrunner.
