### ISSUE TITLE
[FEATURE REQUEST] Use roadrunner as `php -S 0.0.0.0:3000` server

### ISSUE THREAD

**Issue by batara666** [spiral/roadrunner#849]

**Comment by rustatian** [comment]
@batara666 Hey, please, make a proper description of the FR. Why this feature will be useful for the PHP devs, how to use it.

**Comment by batara666** [comment]
Alright

I'm not daily PHP user, but my boss told me to install some open source software made in PHP

And i found the most easiest way to run and serve a php fiile was via [PHP Development Server](https://www.php.net/manual/en/features.commandline.webserver.php)

But I remember about roadrunner, then I give a try to use roadrunner, and It's not as easy as it's should be....

I hope in near time, I'm able to run roadrunner just like `PHP -S bind:port` (I will 100% sure will use roadrunner for production after this)

**Comment by rustatian** [comment]
RR already has an `http` plugin to allocate a port and run on it.

**Comment by rustatian** [comment]
https://roadrunner.dev/docs/http-https

**Comment by batara666** [comment]
But how to use it to be as easy as `php -S 0.0.0.0:4000` ?

**Comment by rustatian** [comment]
Please, read the docs first.

**Comment by batara666** [comment]
Is the .yaml file mandatory?

**Comment by rustatian** [comment]
Yes

**Comment by rustatian** [comment]
Since the RR already supports this via the HTTP plugin, I'm closing this FR.

**Comment by batara666** [comment]
isi there any plug-and-play way?

**Comment by rustatian** [comment]
Yes
1. Read the docs
2. Install RR
3. Enjoy
