### ISSUE TITLE
[Suggestion] Slack/Telegram channel

### ISSUE THREAD

**Issue by Alex-Bond** [spiral/roadrunner#87]
Hey!

How about some Slack or Telegram channel for all quick tasks?

**Comment by wolfy-j** [comment]
Yeah, i'm talking to my devops to deploy forum for this tool. Telegram or Discord channel will work fine as well, i'll think about it.

**Comment by wolfy-j** [comment]
You can use https://discord.gg/TFeEmCs in meantime.
