### ISSUE TITLE
Laravel - sessions don't work (cookies problem)

### ISSUE THREAD

**Issue by Ostap34JS** [spiral/roadrunner#91]
# Steps to reproduce
- `composer create-project --prefer-dist laravel/laravel laravel57`
- `cd laravel57`
- edit env file - database connection
- `php artisan make:auth`
- `php artisan migrate`
- do this steps: https://github.com/spiral/roadrunner/wiki/Laravel-Framework
- `rr -v -d`
- Open browser and go to http://0.0.0.0:8080/register, fill out the form, submit and see the 419 ERROR
# Environment
- PHP 7.3
- Laravel 5.7

### How to fix it? thanks

**Comment by wolfy-j** [comment]
Can it be related to https://github.com/spiral/roadrunner/issues/18 ?

**Comment by Ostap34JS** [comment]
@wolfy-j maybe yes

**Comment by Alex-Bond** [comment]
@wolfy-j  @Ostap34JS I think it caused by #93

**Comment by Ostap34JS** [comment]
@Alex-Bond wow, Thank you for fix!
Then i`m wait to pull request will be merged

**Comment by wolfy-j** [comment]
Merged and released.

**Comment by Ostap34JS** [comment]
Coool, ok - i`m go to try new changes

**Comment by Ostap34JS** [comment]
i`m go to my roadrunner cloned directory, run `git pull`, and `sudo make`
and run my laravel project - sessions also not work.

**Comment by wolfy-j** [comment]
The fix is actually in composer dependency not rr binary.

**Comment by Ostap34JS** [comment]
oh yes, csrf token exists, but it always change if page refreshed

**Comment by Ostap34JS** [comment]
the problem is that the csrf token is not saving and always updated

**Comment by Alex-Bond** [comment]
@Ostap34JS i love Laravel. Not it doesn't see cookies... in some cases.

**Comment by Ostap34JS** [comment]
it's bad (

**Comment by Alex-Bond** [comment]
@Ostap34JS  actually now its working, but i didnt change anything.

**Comment by Ostap34JS** [comment]
You mean in your computer it works?

**Comment by Alex-Bond** [comment]
@Ostap34JS yeap.
Sorry for russian :)

Проверил в инкогнито и обычном режиме - вс еок. Дает зарегаться и залогинится.
Но столкнулся с странным поведением когда я делаю логаут, но он не логаутит. Это я уже хз что за фигня. Возможно где-то не донастроил сесии в ларе.

**Comment by wolfy-j** [comment]
А при логауте как он удаляет куки?

**Comment by Ostap34JS** [comment]
@Ostap34JS у меня кстати тоже такое было, но потом вообще перестало логинить

**Comment by Alex-Bond** [comment]
@wolfy-j при логауте согласно коду он просто обнуляет сессию (атрибуты в []). Но вместе с этим он создает новую сессию и отправляет новую куку с сессией.
А дальше начинается веселая часть - при ребуте он то считает что я залогинен, то нет. Такое чувство что прописывает что то в $_SESSION и $_COOKIE, но при дебаге все чисто.
Не пойму откуда эта скотина берет не те данные.

**Comment by Alex-Bond** [comment]
Меня еще сильно ссмущает то что он шлет set-cookie 2 раза подряд.

**Comment by wolfy-j** [comment]
Если он прописывает что-то в $_SESSION и $_COOKIE то однозначно утекают данные в следующий запрос... Трудно сказать, мы не пользуемся Ларавел (

**Comment by wolfy-j** [comment]
А ядро Ларавела перезагружается между запросами?

**Comment by wolfy-j** [comment]
А если maxJobs = 1 то работает стабильно?

**Comment by Alex-Bond** [comment]
@wolfy-j  сделал numWorkers: 1 и все стало стабильно. 100% глобалка гдето. Осталось понять где!

**Comment by Alex-Bond** [comment]
Нащупал что то интерестное. \Illuminate\Auth\SessionGuard не обнуляется при выставлении нового запроса. Теперь надо придумать как его поправить.

**Comment by Alex-Bond** [comment]
Так. Мне вроде удалось решить проблему. Завтра я попробую это оформить по человечески.

**Comment by Alex-Bond** [comment]
@wolfy-j @Ostap34JS 
So, a small update in English because i feel like i figure out a problem.
Looks like Laravel doesn't reset few components with terminate() call and we have to reset it manually.
In order to do that, i have to create a wrapper around an application like https://github.com/php-pm/php-pm-httpkernel have.
Its already 4AM (4:00) at my place, so i will look into this before the end of the week.

**Comment by barbushin** [comment]
I think, for complete Laravel/Lumen integration with best performance, it will be great to implement same service providers and DI instances resets logic as here https://github.com/swooletw/laravel-swoole/blob/master/config/swoole_http.php#L92-L120

**Comment by wolfy-j** [comment]
Please refer to https://github.com/spiral/roadrunner/issues/96

**Comment by wolfy-j** [comment]
@barbushin this story has been addressed by #96. Can you please put your ideas/links regarding performance optimizations into separate story so we can avoid loosing it?

Thank you :)
