### ISSUE TITLE
Custom HTTP methods treated as GET

### ISSUE THREAD

**Issue by acelot** [spiral/roadrunner#92]
**RR version:** 1.3.1
**PHP:** 7.3

I noticed that custom methods (like `VOTE`) interpreted by rr like `GET` method and rr omits message body.

```php
$worker = new RoadRunner\Worker(new Goridge\StreamRelay(STDIN, STDOUT));
$client = new RoadRunner\PSR7Client($worker);

while ($request = $client->acceptRequest()) {
    $client->respond(new JsonResponse($request->getBody()->getContents()));
}
```

When I send a `VOTE` request, it returns me an empty body:
```bash
curl -X VOTE \
  http://localhost \
  -H 'Content-Type: application/json' \
  -d '{"test: "true"}'
```

And when I send `POST` request, it returns a correct body:
```bash
curl -X POST \
  http://localhost \
  -H 'Content-Type: application/json' \
  -d '{"test: "true"}'
```

How to make `rr` not to lose the message body?

**Comment by Alex-Bond** [comment]
@acelot pull request created. Hopefully, today will be merged.
