### ISSUE TITLE
Not debud and verbose after cli ./rr http:reset

### ISSUE THREAD

**Issue by dimkabelkov** [spiral/roadrunner#95]
php code

`while ($req = $psr7->acceptRequest()) {`
`    try {`
`        error_log('log first run'); //log`
`        $resp->getBody()->write("hello world");`
`    } catch (\Throwable $e) {`
`        $psr7->getWorker()->error((string)$e);`
`    }`
`}`

`./rr server -d -v`

`DEBU[0000] [static]: disabled`
`DEBU[0000] [rpc]: started`
`DEBU[0000] [http]: started`
`INFO[0004] 172.19.0.1 {3.73ms} 200 GET http://notifier.local/`
`WARN[0005] log first run`

Change php file:

error_log('log first run'); -> error_log('log reset run');

`./rr http:reset`

`DEBU[0261] new worker pool`
`INFO[0343] 172.19.0.1 {3.55ms} 200 GET http://notifier.local/ `
`INFO[0345] 172.19.0.1 {3.55ms} 200 GET http://notifier.local/ `

After reload workers, error_log not logging in STDOUT

**Comment by dimkabelkov** [comment]
./rr
RoadRunner, PHP Application Server:
Version: 1.3.0, 2019-01-05T16:40:15+0300

**Comment by wolfy-j** [comment]
I'm not able to reproduce this bug. Have you tried 1.3.1 (the part regarding error log forwarding did not changed since 1.2.8 but thought).

http://prntscr.com/m8bl0o

**Comment by dimkabelkov** [comment]
dated to 1.3.1, everything works
