### ISSUE TITLE
Installation documentation error

### ISSUE THREAD

**Issue by AlexPravdin** [spiral/roadrunner#99]
Hello.
I'm using this page https://github.com/spiral/roadrunner/wiki/Installation as manual for RR installation. I've copied RR sources under the `/go/src` directory and run the `go get ./...` command to obtain dependencies. But it doesn't end successfully:

```
go get: no install location for directory /go/src outside GOPATH
        For more details see: 'go help gopath'
```
But anyway, RR build runs successfully after that. But I can't automate this process as command end with non-zero return code. How to solve this?

**Comment by wolfy-j** [comment]
How are you trying to install it? Are you using `go install`? Please try `make install` instead.

**Comment by AlexPravdin** [comment]
I'm copying sources into the clear golang docker image, and the next command is `go get ./...`. Should I run `make install` instead? I was tried to run `make` and it failed with many arrors on non-existing dependencies.

**Comment by wolfy-j** [comment]
What go version do you use? 1.11 should automatically download them all. Anyway i recommend use `go mod` instead of `go get` as it will pull correct dependencies.

**Comment by AlexPravdin** [comment]
I was using the last golang 1.10 official docker image.
Please update the docs to avoid stucks from users who don't know golang details but just wants to compile RR.

**Comment by wolfy-j** [comment]
I think 1.10 is valid version but i will bump it up to 1.11 just in case.

**Comment by wolfy-j** [comment]
Let me know if you managed to solve your build issue. I have updated Wiki.
